// AUTO-GENERATED by scripts/internal/extract_externs.py - do not edit by hand.
//
// Externs for every data symbol the ExportDelinker'd target objects
// reference but don't define.  Including this file lets a hand-matched
// stub write `return &DAT_xxxx;` and produce a relocation that pairs
// against the original .obj.
//
// All entries are declared as `unsigned char` so the resulting COFF
// relocation type is a plain 32-bit absolute DIR32 in both objects.
// Cast the address in the function body to whatever type the function
// actually returns: `return reinterpret_cast<T*>(&DAT_xxxx);`.

#ifndef BULANCI_EXTERNS_H
#define BULANCI_EXTERNS_H

#ifdef __cplusplus
extern "C" {
#endif

/* DAT_ (657) */
extern unsigned char DAT_00401bb1;
extern unsigned char DAT_00401c4b;
extern unsigned char DAT_00401fea;
extern unsigned char DAT_0040a64d;
extern unsigned char DAT_0041d3d6;
extern unsigned char DAT_004237aa;
extern unsigned char DAT_0042abc9;
extern unsigned char DAT_0042b3ab;
extern unsigned char DAT_0042b487;
extern unsigned char DAT_00431848;
extern unsigned char DAT_00431ae3;
extern unsigned char DAT_00447144;
extern unsigned char DAT_0047de40;
extern unsigned char DAT_0047f214;
extern unsigned char DAT_0047f624;
extern unsigned char DAT_0047f628;
extern unsigned char DAT_0047f644;
extern unsigned char DAT_0047f648;
extern unsigned char DAT_0047f654;
extern unsigned char DAT_0047f658;
extern unsigned char DAT_0047f660;
extern unsigned char DAT_0047f7d8;
extern unsigned char DAT_0047f7e0;
extern unsigned char DAT_004804ec;
extern unsigned char DAT_00480504;
extern unsigned char DAT_004814c4;
extern unsigned char DAT_004814e8;
extern unsigned char DAT_0048150c;
extern unsigned char DAT_00481560;
extern unsigned char DAT_00481964;
extern unsigned char DAT_00481968;
extern unsigned char DAT_00481978;
extern unsigned char DAT_00481a50;
extern unsigned char DAT_00481a60;
extern unsigned char DAT_00481d38;
extern unsigned char DAT_00481d50;
extern unsigned char DAT_004827d4;
extern unsigned char DAT_004827d8;
extern unsigned char DAT_004827f4;
extern unsigned char DAT_00482820;
extern unsigned char DAT_00482908;
extern unsigned char DAT_00482910;
extern unsigned char DAT_00482918;
extern unsigned char DAT_00482928;
extern unsigned char DAT_0048292c;
extern unsigned char DAT_00482948;
extern unsigned char DAT_0048294c;
extern unsigned char DAT_00482968;
extern unsigned char DAT_004829a8;
extern unsigned char DAT_004829b0;
extern unsigned char DAT_004829b4;
extern unsigned char DAT_004829d0;
extern unsigned char DAT_004829d4;
extern unsigned char DAT_00482b04;
extern unsigned char DAT_00482b10;
extern unsigned char DAT_00482b1c;
extern unsigned char DAT_00482b28;
extern unsigned char DAT_0048336c;
extern unsigned char DAT_00483378;
extern unsigned char DAT_00483384;
extern unsigned char DAT_00483390;
extern unsigned char DAT_004838b8;
extern unsigned char DAT_00486cd0;
extern unsigned char DAT_00486ce0;
extern unsigned char DAT_00486cf0;
extern unsigned char DAT_00486cf4;
extern unsigned char DAT_00486cf8;
extern unsigned char DAT_00486cfc;
extern unsigned char DAT_00486d00;
extern unsigned char DAT_00486d04;
extern unsigned char DAT_00486d08;
extern unsigned char DAT_00486d0c;
extern unsigned char DAT_00486d10;
extern unsigned char DAT_00486d20;
extern unsigned char DAT_00486d30;
extern unsigned char DAT_00486d40;
extern unsigned char DAT_00486d50;
extern unsigned char DAT_00486d60;
extern unsigned char DAT_00486d70;
extern unsigned char DAT_00487094;
extern unsigned char DAT_00489584;
extern unsigned char DAT_0048971a;
extern unsigned char DAT_0048971c;
extern unsigned char DAT_00489ca0;
extern unsigned char DAT_00489ca4;
extern unsigned char DAT_00489ce8;
extern unsigned char DAT_00489cf0;
extern unsigned char DAT_0048ae30;
extern unsigned char DAT_0048af54;
extern unsigned char DAT_0048af70;
extern unsigned char DAT_0048af78;
extern unsigned char DAT_0048af80;
extern unsigned char DAT_0048af88;
extern unsigned char DAT_0048af90;
extern unsigned char DAT_0048af98;
extern unsigned char DAT_0048afa0;
extern unsigned char DAT_0048afa8;
extern unsigned char DAT_0048afb4;
extern unsigned char DAT_0048afdc;
extern unsigned char DAT_0048b770;
extern unsigned char DAT_0048b778;
extern unsigned char DAT_0048b780;
extern unsigned char DAT_0048b788;
extern unsigned char DAT_0048b790;
extern unsigned char DAT_0048b798;
extern unsigned char DAT_0048b7a0;
extern unsigned char DAT_0048b7a8;
extern unsigned char DAT_0048b7b4;
extern unsigned char DAT_0048b8a4;
extern unsigned char DAT_0048b91c;
extern unsigned char DAT_0048b924;
extern unsigned char DAT_0048b938;
extern unsigned char DAT_0048bb38;
extern unsigned char DAT_0048bb39;
extern unsigned char DAT_0048bb58;
extern unsigned char DAT_0048bb64;
extern unsigned char DAT_0048bb70;
extern unsigned char DAT_0048bb7c;
extern unsigned char DAT_0048bb88;
extern unsigned char DAT_0048bb94;
extern unsigned char DAT_0048bec4;
extern unsigned char DAT_0048bec5;
extern unsigned char DAT_0048bee0;
extern unsigned char DAT_0048bee4;
extern unsigned char DAT_0049bf64;
extern unsigned char DAT_0049bf74;
extern unsigned char DAT_0049bf94;
extern unsigned char DAT_0049bfb8;
extern unsigned char DAT_0049c048;
extern unsigned char DAT_0049c04c;
extern unsigned char DAT_0049c0d8;
extern unsigned char DAT_0049c0f0;
extern unsigned char DAT_0049c108;
extern unsigned char DAT_0049c120;
extern unsigned char DAT_0049c128;
extern unsigned char DAT_0049c1a0;
extern unsigned char DAT_0049c1a4;
extern unsigned char DAT_0049c1c8;
extern unsigned char DAT_0049c1cc;
extern unsigned char DAT_0049c308;
extern unsigned char DAT_0049c54c;
extern unsigned char DAT_0049c550;
extern unsigned char DAT_0049d69c;
extern unsigned char DAT_0049d798;
extern unsigned char DAT_0049d898;
extern unsigned char DAT_0049d998;
extern unsigned char DAT_0049d9b0;
extern unsigned char DAT_0049da54;
extern unsigned char DAT_0049da68;
extern unsigned char DAT_0049da74;
extern unsigned char DAT_0049da88;
extern unsigned char DAT_0049db2c;
extern unsigned char DAT_0049db40;
extern unsigned char DAT_0049db50;
extern unsigned char DAT_0049db54;
extern unsigned char DAT_0049dc50;
extern unsigned char DAT_0049dc90;
extern unsigned char DAT_0049dcd0;
extern unsigned char DAT_0049dd10;
extern unsigned char DAT_0049dd50;
extern unsigned char DAT_0049dd90;
extern unsigned char DAT_0049dd92;
extern unsigned char DAT_0049de10;
extern unsigned char DAT_0049de18;
extern unsigned char DAT_0049de20;
extern unsigned char DAT_0049de28;
extern unsigned char DAT_0049de38;
extern unsigned char DAT_0049de40;
extern unsigned char DAT_0049de48;
extern unsigned char DAT_0049de50;
extern unsigned char DAT_0049df50;
extern unsigned char DAT_0049e0e0;
extern unsigned char DAT_0049e0e2;
extern unsigned char DAT_0049e0e4;
extern unsigned char DAT_0049e0e6;
extern unsigned char DAT_0049e158;
extern unsigned char DAT_0049e288;
extern unsigned char DAT_0049e2fc;
extern unsigned char DAT_0049e310;
extern unsigned char DAT_0049e3d8;
extern unsigned char DAT_0049e858;
extern unsigned char DAT_0049e8d0;
extern unsigned char DAT_0049e9d0;
extern unsigned char DAT_0049ead0;
extern unsigned char DAT_0049ebd0;
extern unsigned char DAT_0049ec48;
extern unsigned char DAT_0049ecf8;
extern unsigned char DAT_0049ed78;
extern unsigned char DAT_0049edf8;
extern unsigned char DAT_0049ee70;
extern unsigned char DAT_0049efd8;
extern unsigned char DAT_0049efdc;
extern unsigned char DAT_0049efe0;
extern unsigned char DAT_0049efe4;
extern unsigned char DAT_004a5698;
extern unsigned char DAT_004a56a8;
extern unsigned char DAT_004a598c;
extern unsigned char DAT_004aaa70;
extern unsigned char DAT_004ab2ec;
extern unsigned char DAT_004ab3fc;
extern unsigned char DAT_004ab468;
extern unsigned char DAT_004ab4d4;
extern unsigned char DAT_004ab7c0;
extern unsigned char DAT_004abf0c;
extern unsigned char DAT_004ac520;
extern unsigned char DAT_004ac540;
extern unsigned char DAT_004ac560;
extern unsigned char DAT_004ac57c;
extern unsigned char DAT_004ac5d0;
extern unsigned char DAT_004ac5f0;
extern unsigned char DAT_004ac610;
extern unsigned char DAT_004ac630;
extern unsigned char DAT_004ac650;
extern unsigned char DAT_004ac678;
extern unsigned char DAT_004ac698;
extern unsigned char DAT_004ac6b8;
extern unsigned char DAT_004ac6d8;
extern unsigned char DAT_004ac6f8;
extern unsigned char DAT_004ac718;
extern unsigned char DAT_004ac738;
extern unsigned char DAT_004ac760;
extern unsigned char DAT_004ac788;
extern unsigned char DAT_004ac800;
extern unsigned char DAT_004ac828;
extern unsigned char DAT_004ac848;
extern unsigned char DAT_004ac864;
extern unsigned char DAT_004ac8a0;
extern unsigned char DAT_004ac8c0;
extern unsigned char DAT_004ac8e0;
extern unsigned char DAT_004ac900;
extern unsigned char DAT_004ac920;
extern unsigned char DAT_004ac940;
extern unsigned char DAT_004ac960;
extern unsigned char DAT_004ac980;
extern unsigned char DAT_004ac9a0;
extern unsigned char DAT_004ac9c0;
extern unsigned char DAT_004ac9e0;
extern unsigned char DAT_004aca00;
extern unsigned char DAT_004aca20;
extern unsigned char DAT_004aca40;
extern unsigned char DAT_004acaa8;
extern unsigned char DAT_004ae008;
extern unsigned char DAT_004ae3f0;
extern unsigned char DAT_004ae404;
extern unsigned char DAT_004ae408;
extern unsigned char DAT_004ae418;
extern unsigned char DAT_004ae5a0;
extern unsigned char DAT_004ae5c4;
extern unsigned char DAT_004ae5ed;
extern unsigned char DAT_004ae604;
extern unsigned char DAT_004ae605;
extern unsigned char DAT_004ae60c;
extern unsigned char DAT_004ae6f0;
extern unsigned char DAT_004ae6f8;
extern unsigned char DAT_004ae6fc;
extern unsigned char DAT_004ae708;
extern unsigned char DAT_004ae748;
extern unsigned char DAT_004ae788;
extern unsigned char DAT_004ae798;
extern unsigned char DAT_004aea34;
extern unsigned char DAT_004aeaa8;
extern unsigned char DAT_004aeab0;
extern unsigned char DAT_004aeab4;
extern unsigned char DAT_004aead8;
extern unsigned char DAT_004aeadc;
extern unsigned char DAT_004aeb20;
extern unsigned char DAT_004aef24;
extern unsigned char DAT_004aef88;
extern unsigned char DAT_004aef98;
extern unsigned char DAT_004aefa8;
extern unsigned char DAT_004aefb8;
extern unsigned char DAT_004aeff8;
extern unsigned char DAT_004af008;
extern unsigned char DAT_004af2dc;
extern unsigned char DAT_004af2ec;
extern unsigned char DAT_004af774;
extern unsigned char DAT_004af900;
extern unsigned char DAT_004af90c;
extern unsigned char DAT_004af910;
extern unsigned char DAT_004af914;
extern unsigned char DAT_004af918;
extern unsigned char DAT_004af91c;
extern unsigned char DAT_004af920;
extern unsigned char DAT_004af924;
extern unsigned char DAT_004af934;
extern unsigned char DAT_004af940;
extern unsigned char DAT_004afce4;
extern unsigned char DAT_004b0030;
extern unsigned char DAT_004b0050;
extern unsigned char DAT_004b020c;
extern unsigned char DAT_004b0214;
extern unsigned char DAT_004b021c;
extern unsigned char DAT_004b0224;
extern unsigned char DAT_004b08c8;
extern unsigned char DAT_004b09c8;
extern unsigned char DAT_004b0ac8;
extern unsigned char DAT_004b0bc8;
extern unsigned char DAT_004b0cc8;
extern unsigned char DAT_004b0e44;
extern unsigned char DAT_004b0e48;
extern unsigned char DAT_004b0ea0;
extern unsigned char DAT_004b0eb0;
extern unsigned char DAT_004b1018;
extern unsigned char DAT_004b101c;
extern unsigned char DAT_004b1038;
extern unsigned char DAT_004b103c;
extern unsigned char DAT_004b1158;
extern unsigned char DAT_004b115c;
extern unsigned char DAT_004b1198;
extern unsigned char DAT_004b13b8;
extern unsigned char DAT_004b14c0;
extern unsigned char DAT_004b15c8;
extern unsigned char DAT_004b15cc;
extern unsigned char DAT_004b15d8;
extern unsigned char DAT_004b16bc;
extern unsigned char DAT_004b16c0;
extern unsigned char DAT_004b16c8;
extern unsigned char DAT_004b17b0;
extern unsigned char DAT_004b17b8;
extern unsigned char DAT_004b1898;
extern unsigned char DAT_004b1910;
extern unsigned char DAT_004b1914;
extern unsigned char DAT_004b191c;
extern unsigned char DAT_004b1920;
extern unsigned char DAT_004b1950;
extern unsigned char DAT_004b1a70;
extern unsigned char DAT_004b1a74;
extern unsigned char DAT_004b1a78;
extern unsigned char DAT_004b1a7c;
extern unsigned char DAT_004b1a80;
extern unsigned char DAT_004b1a84;
extern unsigned char DAT_004b1a88;
extern unsigned char DAT_004b1a8c;
extern unsigned char DAT_004b1a90;
extern unsigned char DAT_004b1a94;
extern unsigned char DAT_004b1a98;
extern unsigned char DAT_004b1a9c;
extern unsigned char DAT_004b1aa0;
extern unsigned char DAT_004b1c00;
extern unsigned char DAT_004b2100;
extern unsigned char DAT_004b2128;
extern unsigned char DAT_004b2130;
extern unsigned char DAT_004b2188;
extern unsigned char DAT_004b21a0;
extern unsigned char DAT_004b21a4;
extern unsigned char DAT_004b21a8;
extern unsigned char DAT_004b31a8;
extern unsigned char DAT_004b32a8;
extern unsigned char DAT_004b3300;
extern unsigned char DAT_004b3314;
extern unsigned char DAT_004b3334;
extern unsigned char DAT_004b3348;
extern unsigned char DAT_004b335c;
extern unsigned char DAT_004b3370;
extern unsigned char DAT_004b3384;
extern unsigned char DAT_004b33a4;
extern unsigned char DAT_004b33b8;
extern unsigned char DAT_004b33cc;
extern unsigned char DAT_004b33e0;
extern unsigned char DAT_004b33f4;
extern unsigned char DAT_004b3414;
extern unsigned char DAT_004b3428;
extern unsigned char DAT_004b343c;
extern unsigned char DAT_004b3450;
extern unsigned char DAT_004b3488;
extern unsigned char DAT_004b34c0;
extern unsigned char DAT_004b34d4;
extern unsigned char DAT_004b34e8;
extern unsigned char DAT_004b34fc;
extern unsigned char DAT_004b3510;
extern unsigned char DAT_004b3524;
extern unsigned char DAT_004b3538;
extern unsigned char DAT_004b3558;
extern unsigned char DAT_004b356c;
extern unsigned char DAT_004b358c;
extern unsigned char DAT_004b35a0;
extern unsigned char DAT_004b35b4;
extern unsigned char DAT_004b35c8;
extern unsigned char DAT_004b35dc;
extern unsigned char DAT_004b35f0;
extern unsigned char DAT_004b3604;
extern unsigned char DAT_004b3618;
extern unsigned char DAT_004b362c;
extern unsigned char DAT_004b3640;
extern unsigned char DAT_004b3654;
extern unsigned char DAT_004b3668;
extern unsigned char DAT_004b367c;
extern unsigned char DAT_004b3690;
extern unsigned char DAT_004b36a4;
extern unsigned char DAT_004b36b8;
extern unsigned char DAT_004b36cc;
extern unsigned char DAT_004b36ec;
extern unsigned char DAT_004b3700;
extern unsigned char DAT_004b372c;
extern unsigned char DAT_004b3730;
extern unsigned char DAT_004b3734;
extern unsigned char DAT_004b3754;
extern unsigned char DAT_004b3768;
extern unsigned char DAT_004b3788;
extern unsigned char DAT_004b37a8;
extern unsigned char DAT_004b37bc;
extern unsigned char DAT_004b37dc;
extern unsigned char DAT_004b37f0;
extern unsigned char DAT_004b3804;
extern unsigned char DAT_004b3818;
extern unsigned char DAT_004b3838;
extern unsigned char DAT_004b384c;
extern unsigned char DAT_004b386c;
extern unsigned char DAT_004b3880;
extern unsigned char DAT_004b3894;
extern unsigned char DAT_004b38c0;
extern unsigned char DAT_004b38d4;
extern unsigned char DAT_004b38e8;
extern unsigned char DAT_004b3914;
extern unsigned char DAT_004b3928;
extern unsigned char DAT_004b393c;
extern unsigned char DAT_004b3950;
extern unsigned char DAT_004b3970;
extern unsigned char DAT_004b3984;
extern unsigned char DAT_004b3998;
extern unsigned char DAT_004b39b8;
extern unsigned char DAT_004b39bc;
extern unsigned char DAT_004b39c0;
extern unsigned char DAT_004b39c4;
extern unsigned char DAT_004b39c8;
extern unsigned char DAT_004b39cc;
extern unsigned char DAT_004b39d0;
extern unsigned char DAT_004b39d4;
extern unsigned char DAT_004b39d8;
extern unsigned char DAT_004b39dc;
extern unsigned char DAT_004b39e0;
extern unsigned char DAT_004b39e4;
extern unsigned char DAT_004b39e8;
extern unsigned char DAT_004b39ec;
extern unsigned char DAT_004b39f0;
extern unsigned char DAT_004b39f4;
extern unsigned char DAT_004b39f8;
extern unsigned char DAT_004b39fc;
extern unsigned char DAT_004b3a00;
extern unsigned char DAT_004b3a04;
extern unsigned char DAT_004b3a08;
extern unsigned char DAT_004b3a1c;
extern unsigned char DAT_004b3a30;
extern unsigned char DAT_004b3a44;
extern unsigned char DAT_004b3a64;
extern unsigned char DAT_004b3ab4;
extern unsigned char DAT_004b3ae0;
extern unsigned char DAT_004b3b18;
extern unsigned char DAT_004b3b1c;
extern unsigned char DAT_004b3b20;
extern unsigned char DAT_004b3b34;
extern unsigned char DAT_004b3b54;
extern unsigned char DAT_004b3b74;
extern unsigned char DAT_004b3b88;
extern unsigned char DAT_004b3b8c;
extern unsigned char DAT_004b3b90;
extern unsigned char DAT_004b3b94;
extern unsigned char DAT_004b3b9c;
extern unsigned char DAT_004b3ba0;
extern unsigned char DAT_004b3ba4;
extern unsigned char DAT_004b3ba8;
extern unsigned char DAT_004b3bac;
extern unsigned char DAT_004b3bd8;
extern unsigned char DAT_004b3bdc;
extern unsigned char DAT_004b3be0;
extern unsigned char DAT_004b7be0;
extern unsigned char DAT_004b7be4;
extern unsigned char DAT_004b7be8;
extern unsigned char DAT_004b7bec;
extern unsigned char DAT_004b7bf0;
extern unsigned char DAT_004b7bf4;
extern unsigned char DAT_004b7bf8;
extern unsigned char DAT_004b7bfc;
extern unsigned char DAT_004b7c10;
extern unsigned char DAT_004b7c14;
extern unsigned char DAT_004b7c20;
extern unsigned char DAT_004b7c28;
extern unsigned char DAT_004b7c30;
extern unsigned char DAT_004b7c38;
extern unsigned char DAT_004b7c40;
extern unsigned char DAT_004b7c50;
extern unsigned char DAT_004b7c58;
extern unsigned char DAT_004b7c60;
extern unsigned char DAT_004b7c80;
extern unsigned char DAT_004b7c94;
extern unsigned char DAT_004b7c98;
extern unsigned char DAT_004b7cb8;
extern unsigned char DAT_004b7cd8;
extern unsigned char DAT_004b7ce0;
extern unsigned char DAT_004b7ce4;
extern unsigned char DAT_004b7ce8;
extern unsigned char DAT_004b7cfc;
extern unsigned char DAT_004b7d34;
extern unsigned char DAT_004b7d60;
extern unsigned char DAT_004b7d80;
extern unsigned char DAT_004b7dc4;
extern unsigned char DAT_004b7e08;
extern unsigned char DAT_004b7e4c;
extern unsigned char DAT_004b7e78;
extern unsigned char DAT_004b7eb0;
extern unsigned char DAT_004b7edc;
extern unsigned char DAT_004b7ef0;
extern unsigned char DAT_004b7f04;
extern unsigned char DAT_004b7f0c;
extern unsigned char DAT_004b7f14;
extern unsigned char DAT_004b7f28;
extern unsigned char DAT_004b7f48;
extern unsigned char DAT_004b7f80;
extern unsigned char DAT_004b7fbc;
extern unsigned char DAT_004b81c0;
extern unsigned char DAT_004b81d4;
extern unsigned char DAT_004b81e8;
extern unsigned char DAT_004b81fc;
extern unsigned char DAT_004b8210;
extern unsigned char DAT_004b8248;
extern unsigned char DAT_004b8268;
extern unsigned char DAT_004b826c;
extern unsigned char DAT_004b8270;
extern unsigned char DAT_004b82b4;
extern unsigned char DAT_004b82c8;
extern unsigned char DAT_004b82dc;
extern unsigned char DAT_004b82fc;
extern unsigned char DAT_004b8304;
extern unsigned char DAT_004b830c;
extern unsigned char DAT_004b832c;
extern unsigned char DAT_004b834c;
extern unsigned char DAT_004b836c;
extern unsigned char DAT_004b8370;
extern unsigned char DAT_004b8374;
extern unsigned char DAT_004b8378;
extern unsigned char DAT_004b837c;
extern unsigned char DAT_004b8380;
extern unsigned char DAT_004b8384;
extern unsigned char DAT_004b8388;
extern unsigned char DAT_004b83a0;
extern unsigned char DAT_004b83c0;
extern unsigned char DAT_004b83c4;
extern unsigned char DAT_004b83c8;
extern unsigned char DAT_004b83dc;
extern unsigned char DAT_004b83fc;
extern unsigned char DAT_004b8410;
extern unsigned char DAT_004b843c;
extern unsigned char DAT_004b8468;
extern unsigned char DAT_004b847c;
extern unsigned char DAT_004b84a8;
extern unsigned char DAT_004b84bc;
extern unsigned char DAT_004b84c0;
extern unsigned char DAT_004b84f8;
extern unsigned char DAT_004b84fc;
extern unsigned char DAT_004b8510;
extern unsigned char DAT_004b853c;
extern unsigned char DAT_004b8574;
extern unsigned char DAT_004b8588;
extern unsigned char DAT_004b8590;
extern unsigned char DAT_004b85b0;
extern unsigned char DAT_004b85bc;
extern unsigned char DAT_004b85c4;
extern unsigned char DAT_004b85c8;
extern unsigned char DAT_004b85d0;
extern unsigned char DAT_004b85d4;
extern unsigned char DAT_004b85d8;
extern unsigned char DAT_004b85dc;
extern unsigned char DAT_004b85e0;
extern unsigned char DAT_004b85e4;
extern unsigned char DAT_004b85e8;
extern unsigned char DAT_004b8738;
extern unsigned char DAT_004b873c;
extern unsigned char DAT_004b8740;
extern unsigned char DAT_004b8744;
extern unsigned char DAT_004b8748;
extern unsigned char DAT_004b874c;
extern unsigned char DAT_004b8750;
extern unsigned char DAT_004b8754;
extern unsigned char DAT_004b8758;
extern unsigned char DAT_004b8760;
extern unsigned char DAT_004b8764;
extern unsigned char DAT_004b876c;
extern unsigned char DAT_004b87b0;
extern unsigned char DAT_004b87b8;
extern unsigned char DAT_004b8844;
extern unsigned char DAT_004b8848;
extern unsigned char DAT_004b884c;
extern unsigned char DAT_004b8850;
extern unsigned char DAT_004b8854;
extern unsigned char DAT_004b8858;
extern unsigned char DAT_004b885c;
extern unsigned char DAT_004b8860;
extern unsigned char DAT_004b8864;
extern unsigned char DAT_004b8868;
extern unsigned char DAT_004b886c;
extern unsigned char DAT_004b8870;
extern unsigned char DAT_004b8874;
extern unsigned char DAT_004b8878;
extern unsigned char DAT_004b887c;
extern unsigned char DAT_004b8880;
extern unsigned char DAT_004b8a84;
extern unsigned char DAT_004b8a8c;
extern unsigned char DAT_004b8a90;
extern unsigned char DAT_004b8a94;
extern unsigned char DAT_004b8a98;
extern unsigned char DAT_004b8a9c;
extern unsigned char DAT_004b8aa0;
extern unsigned char DAT_004b8aa4;
extern unsigned char DAT_004b8aac;
extern unsigned char DAT_004b8abc;
extern unsigned char DAT_004b8ac4;
extern unsigned char DAT_004b8ac8;
extern unsigned char DAT_004b8acc;
extern unsigned char DAT_004b8ad0;
extern unsigned char DAT_004b8ad4;
extern unsigned char DAT_004b8ae0;
extern unsigned char DAT_004b8ae4;
extern unsigned char DAT_004b8ae8;
extern unsigned char DAT_004b8aec;
extern unsigned char DAT_004b8b10;
extern unsigned char DAT_004b8b18;
extern unsigned char DAT_004b8b31;
extern unsigned char DAT_004b8c35;
extern unsigned char DAT_004b8e2c;
extern unsigned char DAT_004b8e34;
extern unsigned char DAT_004b8e38;
extern unsigned char DAT_004b8f3c;
extern unsigned char DAT_004b8f40;
extern unsigned char DAT_004b8f80;
extern unsigned char DAT_004b8f84;
extern unsigned char DAT_004b8f88;
extern unsigned char DAT_004b8f8c;
extern unsigned char DAT_004b8f90;
extern unsigned char DAT_004b8f98;
extern unsigned char DAT_004b8f9c;
extern unsigned char DAT_004b8fa0;
extern unsigned char DAT_004b8fa8;
extern unsigned char DAT_004b8fac;
extern unsigned char DAT_004b8fb0;
extern unsigned char DAT_004b8fb4;
extern unsigned char DAT_004b8fb8;
extern unsigned char DAT_004b8fbc;
extern unsigned char DAT_004b8fc0;
extern unsigned char DAT_004b8fc4;
extern unsigned char DAT_004b8fc8;
extern unsigned char DAT_004ba0a4;
extern unsigned char DAT_004ba0a8;
extern unsigned char DAT_004ba0c0;
extern unsigned char DAT_004ba1c0;
extern unsigned char DAT_004ba1c4;
extern unsigned char DAT_004ba1c8;
extern unsigned char DAT_004ba1cc;
extern unsigned char DAT_004ba1d0;
extern unsigned char DAT_004ba1d8;
extern unsigned char DAT_004ba1dc;
extern unsigned char DAT_004ba1e0;
extern unsigned char DAT_004ba1e4;
extern unsigned char DAT_004ba1e8;
extern unsigned char DAT_004ba1ec;
extern unsigned char DAT_004ba1f0;
extern unsigned char DAT_004ba1f4;
extern unsigned char DAT_004ba1f8;

/* IMAGE_DOS_HEADER_ (1) */
extern unsigned char IMAGE_DOS_HEADER_00400000;

/* LAB_ (552) */
extern unsigned char LAB_00408fd0;
extern unsigned char LAB_00408ff0;
extern unsigned char LAB_00409010;
extern unsigned char LAB_004097d0;
extern unsigned char LAB_004097e0;
extern unsigned char LAB_0040abd0;
extern unsigned char LAB_00418bc2;
extern unsigned char LAB_004288eb;
extern unsigned char LAB_00431440;
extern unsigned char LAB_00431470;
extern unsigned char LAB_00431480;
extern unsigned char LAB_004314b0;
extern unsigned char LAB_004314e0;
extern unsigned char LAB_00431550;
extern unsigned char LAB_00431570;
extern unsigned char LAB_004315c0;
extern unsigned char LAB_00431630;
extern unsigned char LAB_00431880;
extern unsigned char LAB_00431950;
extern unsigned char LAB_00431990;
extern unsigned char LAB_004342f0;
extern unsigned char LAB_0043ab40;
extern unsigned char LAB_0043b4c0;
extern unsigned char LAB_004478cd;
extern unsigned char LAB_00449672;
extern unsigned char LAB_0044ab3b;
extern unsigned char LAB_0044d68f;
extern unsigned char LAB_0044d6e5;
extern unsigned char LAB_0044d719;
extern unsigned char LAB_0044d727;
extern unsigned char LAB_0044e98a;
extern unsigned char LAB_0044fc1c;
extern unsigned char LAB_0044fd40;
extern unsigned char LAB_0045fe40;
extern unsigned char LAB_004604a0;
extern unsigned char LAB_00460ab0;
extern unsigned char LAB_00460b20;
extern unsigned char LAB_00460cc0;
extern unsigned char LAB_004613e0;
extern unsigned char LAB_00461590;
extern unsigned char LAB_004617f0;
extern unsigned char LAB_00462320;
extern unsigned char LAB_00462e20;
extern unsigned char LAB_00463590;
extern unsigned char LAB_00464130;
extern unsigned char LAB_004642d0;
extern unsigned char LAB_004643c0;
extern unsigned char LAB_004643d0;
extern unsigned char LAB_004644c0;
extern unsigned char LAB_00464520;
extern unsigned char LAB_00464590;
extern unsigned char LAB_00464b80;
extern unsigned char LAB_00464c10;
extern unsigned char LAB_00464c40;
extern unsigned char LAB_00465060;
extern unsigned char LAB_00465080;
extern unsigned char LAB_00465140;
extern unsigned char LAB_004652d0;
extern unsigned char LAB_00465570;
extern unsigned char LAB_00466670;
extern unsigned char LAB_004667c0;
extern unsigned char LAB_00466d90;
extern unsigned char LAB_00467440;
extern unsigned char LAB_004675b0;
extern unsigned char LAB_00468740;
extern unsigned char LAB_00469370;
extern unsigned char LAB_00469430;
extern unsigned char LAB_00469660;
extern unsigned char LAB_00469940;
extern unsigned char LAB_00469c40;
extern unsigned char LAB_0046a050;
extern unsigned char LAB_0046a7f0;
extern unsigned char LAB_0046afb0;
extern unsigned char LAB_0046bae0;
extern unsigned char LAB_0046bb40;
extern unsigned char LAB_0046c880;
extern unsigned char LAB_0046c9a0;
extern unsigned char LAB_0046cec0;
extern unsigned char LAB_0046d2a0;
extern unsigned char LAB_0046d830;
extern unsigned char LAB_0046dfc0;
extern unsigned char LAB_0046e9f0;
extern unsigned char LAB_00471280;
extern unsigned char LAB_00473f59;
extern unsigned char LAB_00473f90;
extern unsigned char LAB_00473fb8;
extern unsigned char LAB_00473ff9;
extern unsigned char LAB_0047403b;
extern unsigned char LAB_00474073;
extern unsigned char LAB_004740c4;
extern unsigned char LAB_004740e8;
extern unsigned char LAB_00474118;
extern unsigned char LAB_00474148;
extern unsigned char LAB_00474170;
extern unsigned char LAB_0047419b;
extern unsigned char LAB_00474219;
extern unsigned char LAB_0047424e;
extern unsigned char LAB_0047428b;
extern unsigned char LAB_004742c9;
extern unsigned char LAB_00474330;
extern unsigned char LAB_00474382;
extern unsigned char LAB_004743ab;
extern unsigned char LAB_004743db;
extern unsigned char LAB_00474421;
extern unsigned char LAB_00474458;
extern unsigned char LAB_0047449e;
extern unsigned char LAB_004744c8;
extern unsigned char LAB_00474503;
extern unsigned char LAB_0047454f;
extern unsigned char LAB_00474578;
extern unsigned char LAB_004745a8;
extern unsigned char LAB_004745d8;
extern unsigned char LAB_0047460b;
extern unsigned char LAB_00474638;
extern unsigned char LAB_00474668;
extern unsigned char LAB_0047469b;
extern unsigned char LAB_004746d3;
extern unsigned char LAB_004746f8;
extern unsigned char LAB_00474749;
extern unsigned char LAB_00474778;
extern unsigned char LAB_004747dd;
extern unsigned char LAB_00474808;
extern unsigned char LAB_0047483b;
extern unsigned char LAB_0047486b;
extern unsigned char LAB_0047489b;
extern unsigned char LAB_004748cb;
extern unsigned char LAB_004748fb;
extern unsigned char LAB_0047492b;
extern unsigned char LAB_00474979;
extern unsigned char LAB_004749c9;
extern unsigned char LAB_004749fb;
extern unsigned char LAB_00474a38;
extern unsigned char LAB_00474a68;
extern unsigned char LAB_00474aae;
extern unsigned char LAB_00474adb;
extern unsigned char LAB_00474b36;
extern unsigned char LAB_00474b68;
extern unsigned char LAB_00474bbf;
extern unsigned char LAB_00474bf0;
extern unsigned char LAB_00474c20;
extern unsigned char LAB_00474c4b;
extern unsigned char LAB_00474c94;
extern unsigned char LAB_00474cb8;
extern unsigned char LAB_00474ceb;
extern unsigned char LAB_00474d3b;
extern unsigned char LAB_00474d96;
extern unsigned char LAB_00474dde;
extern unsigned char LAB_00474e3f;
extern unsigned char LAB_00474e89;
extern unsigned char LAB_00474ec6;
extern unsigned char LAB_00474efb;
extern unsigned char LAB_00474f2b;
extern unsigned char LAB_00474f58;
extern unsigned char LAB_00474f93;
extern unsigned char LAB_00474fc3;
extern unsigned char LAB_00474ff3;
extern unsigned char LAB_00475018;
extern unsigned char LAB_0047506f;
extern unsigned char LAB_004750a3;
extern unsigned char LAB_004750cb;
extern unsigned char LAB_004750fb;
extern unsigned char LAB_00475136;
extern unsigned char LAB_00475194;
extern unsigned char LAB_004751b8;
extern unsigned char LAB_00475210;
extern unsigned char LAB_00475238;
extern unsigned char LAB_00475281;
extern unsigned char LAB_004752f2;
extern unsigned char LAB_00475330;
extern unsigned char LAB_00475392;
extern unsigned char LAB_004753b8;
extern unsigned char LAB_004753e8;
extern unsigned char LAB_0047542e;
extern unsigned char LAB_00475460;
extern unsigned char LAB_00475490;
extern unsigned char LAB_004754b8;
extern unsigned char LAB_004754e8;
extern unsigned char LAB_00475518;
extern unsigned char LAB_0047554b;
extern unsigned char LAB_00475578;
extern unsigned char LAB_004755a8;
extern unsigned char LAB_004755d8;
extern unsigned char LAB_00475608;
extern unsigned char LAB_0047563b;
extern unsigned char LAB_00475686;
extern unsigned char LAB_004756e4;
extern unsigned char LAB_00475734;
extern unsigned char LAB_00475758;
extern unsigned char LAB_004757e3;
extern unsigned char LAB_00475808;
extern unsigned char LAB_0047587a;
extern unsigned char LAB_004758ab;
extern unsigned char LAB_004758d8;
extern unsigned char LAB_00475913;
extern unsigned char LAB_004759bc;
extern unsigned char LAB_004759fe;
extern unsigned char LAB_00475a33;
extern unsigned char LAB_00475a84;
extern unsigned char LAB_00475aa8;
extern unsigned char LAB_00475aee;
extern unsigned char LAB_00475b1b;
extern unsigned char LAB_00475b4b;
extern unsigned char LAB_00475b7b;
extern unsigned char LAB_00475bab;
extern unsigned char LAB_00475bdb;
extern unsigned char LAB_00475c0b;
extern unsigned char LAB_00475c3b;
extern unsigned char LAB_00475c6b;
extern unsigned char LAB_00475c9b;
extern unsigned char LAB_00475ccb;
extern unsigned char LAB_00475cfb;
extern unsigned char LAB_00475d2b;
extern unsigned char LAB_00475d5b;
extern unsigned char LAB_00475d8b;
extern unsigned char LAB_00475dbb;
extern unsigned char LAB_00475deb;
extern unsigned char LAB_00475e1b;
extern unsigned char LAB_00475e4b;
extern unsigned char LAB_00475e7b;
extern unsigned char LAB_00475eb0;
extern unsigned char LAB_00475edb;
extern unsigned char LAB_00475f13;
extern unsigned char LAB_00475f38;
extern unsigned char LAB_00475f70;
extern unsigned char LAB_00475fc9;
extern unsigned char LAB_00476006;
extern unsigned char LAB_0047603b;
extern unsigned char LAB_00476073;
extern unsigned char LAB_004760b3;
extern unsigned char LAB_004760db;
extern unsigned char LAB_00476113;
extern unsigned char LAB_00476143;
extern unsigned char LAB_00476173;
extern unsigned char LAB_004761bc;
extern unsigned char LAB_004762c5;
extern unsigned char LAB_0047632c;
extern unsigned char LAB_00476445;
extern unsigned char LAB_004764ac;
extern unsigned char LAB_0047650f;
extern unsigned char LAB_0047653b;
extern unsigned char LAB_00476568;
extern unsigned char LAB_00476598;
extern unsigned char LAB_004765cb;
extern unsigned char LAB_004765f8;
extern unsigned char LAB_00476628;
extern unsigned char LAB_00476658;
extern unsigned char LAB_00476688;
extern unsigned char LAB_004766dc;
extern unsigned char LAB_0047670b;
extern unsigned char LAB_00476738;
extern unsigned char LAB_0047676b;
extern unsigned char LAB_00476798;
extern unsigned char LAB_004767c8;
extern unsigned char LAB_00476885;
extern unsigned char LAB_0047696d;
extern unsigned char LAB_004769b9;
extern unsigned char LAB_00476a59;
extern unsigned char LAB_00476a9b;
extern unsigned char LAB_00476ac0;
extern unsigned char LAB_00476af8;
extern unsigned char LAB_00476b28;
extern unsigned char LAB_00476b58;
extern unsigned char LAB_00476b88;
extern unsigned char LAB_00476bb8;
extern unsigned char LAB_00476c04;
extern unsigned char LAB_00476c51;
extern unsigned char LAB_00476c7b;
extern unsigned char LAB_00476ca0;
extern unsigned char LAB_00476ccb;
extern unsigned char LAB_00476cfb;
extern unsigned char LAB_00476d2b;
extern unsigned char LAB_00476d66;
extern unsigned char LAB_00476d98;
extern unsigned char LAB_00476dcb;
extern unsigned char LAB_00476e06;
extern unsigned char LAB_00476e46;
extern unsigned char LAB_00476e86;
extern unsigned char LAB_00476ec6;
extern unsigned char LAB_00476ef8;
extern unsigned char LAB_00476f4f;
extern unsigned char LAB_00476f78;
extern unsigned char LAB_00476fab;
extern unsigned char LAB_00476fdb;
extern unsigned char LAB_0047700b;
extern unsigned char LAB_0047703b;
extern unsigned char LAB_00477068;
extern unsigned char LAB_004770b1;
extern unsigned char LAB_0047711d;
extern unsigned char LAB_0047715b;
extern unsigned char LAB_00477261;
extern unsigned char LAB_0047728b;
extern unsigned char LAB_004772bb;
extern unsigned char LAB_004772eb;
extern unsigned char LAB_0047731b;
extern unsigned char LAB_0047734b;
extern unsigned char LAB_0047737b;
extern unsigned char LAB_004773d1;
extern unsigned char LAB_004773fb;
extern unsigned char LAB_00477464;
extern unsigned char LAB_00477488;
extern unsigned char LAB_004774b8;
extern unsigned char LAB_004774f0;
extern unsigned char LAB_0047752e;
extern unsigned char LAB_0047756e;
extern unsigned char LAB_004775a0;
extern unsigned char LAB_004775d3;
extern unsigned char LAB_00477606;
extern unsigned char LAB_0047765b;
extern unsigned char LAB_004776a3;
extern unsigned char LAB_004776d3;
extern unsigned char LAB_004776f8;
extern unsigned char LAB_00477728;
extern unsigned char LAB_0047775b;
extern unsigned char LAB_004777bc;
extern unsigned char LAB_004777eb;
extern unsigned char LAB_0047781b;
extern unsigned char LAB_00477885;
extern unsigned char LAB_004778ab;
extern unsigned char LAB_004778e6;
extern unsigned char LAB_0047791b;
extern unsigned char LAB_00477948;
extern unsigned char LAB_0047797b;
extern unsigned char LAB_004779b6;
extern unsigned char LAB_004779eb;
extern unsigned char LAB_00477a1b;
extern unsigned char LAB_00477b26;
extern unsigned char LAB_00477b71;
extern unsigned char LAB_00477ba6;
extern unsigned char LAB_00477bd8;
extern unsigned char LAB_00477c0b;
extern unsigned char LAB_00477c3b;
extern unsigned char LAB_00477c6b;
extern unsigned char LAB_00477c9b;
extern unsigned char LAB_00477ccb;
extern unsigned char LAB_00477cfb;
extern unsigned char LAB_00477d6d;
extern unsigned char LAB_00477db1;
extern unsigned char LAB_00477de3;
extern unsigned char LAB_00477e0b;
extern unsigned char LAB_00477e3b;
extern unsigned char LAB_00477e68;
extern unsigned char LAB_00477ea6;
extern unsigned char LAB_00477ed8;
extern unsigned char LAB_00477f13;
extern unsigned char LAB_00477f3b;
extern unsigned char LAB_00477f6b;
extern unsigned char LAB_00477f9b;
extern unsigned char LAB_00477fd3;
extern unsigned char LAB_00477ffb;
extern unsigned char LAB_0047802b;
extern unsigned char LAB_0047805b;
extern unsigned char LAB_0047808b;
extern unsigned char LAB_004780fd;
extern unsigned char LAB_00478141;
extern unsigned char LAB_00478173;
extern unsigned char LAB_0047819b;
extern unsigned char LAB_004781de;
extern unsigned char LAB_0047820b;
extern unsigned char LAB_00478243;
extern unsigned char LAB_00478273;
extern unsigned char LAB_00478298;
extern unsigned char LAB_004782cb;
extern unsigned char LAB_004782f8;
extern unsigned char LAB_00478328;
extern unsigned char LAB_0047836b;
extern unsigned char LAB_004783db;
extern unsigned char LAB_0047840b;
extern unsigned char LAB_0047843b;
extern unsigned char LAB_00478481;
extern unsigned char LAB_004784c1;
extern unsigned char LAB_004784e8;
extern unsigned char LAB_0047853f;
extern unsigned char LAB_004785d2;
extern unsigned char LAB_00478603;
extern unsigned char LAB_00478641;
extern unsigned char LAB_004786df;
extern unsigned char LAB_0047870b;
extern unsigned char LAB_004787aa;
extern unsigned char LAB_00478833;
extern unsigned char LAB_0047885b;
extern unsigned char LAB_0047888b;
extern unsigned char LAB_00478989;
extern unsigned char LAB_004789b8;
extern unsigned char LAB_004789e8;
extern unsigned char LAB_00478a23;
extern unsigned char LAB_00478a6f;
extern unsigned char LAB_00478a98;
extern unsigned char LAB_00478ac8;
extern unsigned char LAB_00478afb;
extern unsigned char LAB_00478b2b;
extern unsigned char LAB_00478b5b;
extern unsigned char LAB_00478b8b;
extern unsigned char LAB_00478bc0;
extern unsigned char LAB_00478bfe;
extern unsigned char LAB_00478c4b;
extern unsigned char LAB_00478d32;
extern unsigned char LAB_00478d58;
extern unsigned char LAB_00478d88;
extern unsigned char LAB_00478db0;
extern unsigned char LAB_00478dd8;
extern unsigned char LAB_00478e61;
extern unsigned char LAB_00478e8b;
extern unsigned char LAB_00478eb8;
extern unsigned char LAB_00478f0f;
extern unsigned char LAB_00478f6a;
extern unsigned char LAB_00478fae;
extern unsigned char LAB_00479003;
extern unsigned char LAB_00479020;
extern unsigned char LAB_00479048;
extern unsigned char LAB_00479088;
extern unsigned char LAB_004790c3;
extern unsigned char LAB_0047910f;
extern unsigned char LAB_00479180;
extern unsigned char LAB_00479222;
extern unsigned char LAB_004792c2;
extern unsigned char LAB_004792eb;
extern unsigned char LAB_0047931b;
extern unsigned char LAB_0047937a;
extern unsigned char LAB_004793a8;
extern unsigned char LAB_004793d8;
extern unsigned char LAB_00479422;
extern unsigned char LAB_00479480;
extern unsigned char LAB_004794b0;
extern unsigned char LAB_004794e0;
extern unsigned char LAB_00479519;
extern unsigned char LAB_00479548;
extern unsigned char LAB_00479580;
extern unsigned char LAB_004795b6;
extern unsigned char LAB_004795eb;
extern unsigned char LAB_00479626;
extern unsigned char LAB_00479658;
extern unsigned char LAB_00479696;
extern unsigned char LAB_004796d6;
extern unsigned char LAB_00479700;
extern unsigned char LAB_00479728;
extern unsigned char LAB_00479750;
extern unsigned char LAB_0047978e;
extern unsigned char LAB_004797e1;
extern unsigned char LAB_00479831;
extern unsigned char LAB_0047985b;
extern unsigned char LAB_0047988b;
extern unsigned char LAB_004798b8;
extern unsigned char LAB_004798e8;
extern unsigned char LAB_0047991b;
extern unsigned char LAB_00479953;
extern unsigned char LAB_00479983;
extern unsigned char LAB_004799b3;
extern unsigned char LAB_004799e3;
extern unsigned char LAB_00479a08;
extern unsigned char LAB_00479a30;
extern unsigned char LAB_00479a50;
extern unsigned char LAB_00479a70;
extern unsigned char LAB_00479a90;
extern unsigned char LAB_00479aef;
extern unsigned char LAB_00479b1b;
extern unsigned char LAB_00479b58;
extern unsigned char LAB_00479baf;
extern unsigned char LAB_00479beb;
extern unsigned char LAB_00479c4a;
extern unsigned char LAB_00479c7b;
extern unsigned char LAB_00479ccf;
extern unsigned char LAB_00479cf8;
extern unsigned char LAB_00479d30;
extern unsigned char LAB_00479d58;
extern unsigned char LAB_00479d8b;
extern unsigned char LAB_00479db8;
extern unsigned char LAB_00479e09;
extern unsigned char LAB_00479e59;
extern unsigned char LAB_00479e88;
extern unsigned char LAB_00479ee4;
extern unsigned char LAB_00479f08;
extern unsigned char LAB_00479f3b;
extern unsigned char LAB_00479f68;
extern unsigned char LAB_00479f9b;
extern unsigned char LAB_00479fd3;
extern unsigned char LAB_0047a02a;
extern unsigned char LAB_0047a05b;
extern unsigned char LAB_0047a0a6;
extern unsigned char LAB_0047a0db;
extern unsigned char LAB_0047a108;
extern unsigned char LAB_0047a138;
extern unsigned char LAB_0047a168;
extern unsigned char LAB_0047a198;
extern unsigned char LAB_0047a1c8;
extern unsigned char LAB_0047a224;
extern unsigned char LAB_0047a274;
extern unsigned char LAB_0047a29b;
extern unsigned char LAB_0047a2c8;
extern unsigned char LAB_0047a2fb;
extern unsigned char LAB_0047a343;
extern unsigned char LAB_0047a386;
extern unsigned char LAB_0047a3b8;
extern unsigned char LAB_0047a3f3;
extern unsigned char LAB_0047a418;
extern unsigned char LAB_0047a448;
extern unsigned char LAB_0047a478;
extern unsigned char LAB_0047a4a8;
extern unsigned char LAB_0047a4db;
extern unsigned char LAB_0047a50b;
extern unsigned char LAB_0047a553;
extern unsigned char LAB_0047a57b;
extern unsigned char LAB_0047a5a0;
extern unsigned char LAB_0047a5db;
extern unsigned char LAB_0047a60b;
extern unsigned char LAB_0047a643;
extern unsigned char LAB_0047a673;
extern unsigned char LAB_0047a6a3;
extern unsigned char LAB_0047a6cb;
extern unsigned char LAB_0047a6fb;
extern unsigned char LAB_0047a72b;
extern unsigned char LAB_0047a779;
extern unsigned char LAB_0047a7e5;
extern unsigned char LAB_0047a800;
extern unsigned char LAB_0047a82b;
extern unsigned char LAB_0047a850;
extern unsigned char LAB_0047a88b;
extern unsigned char LAB_0047a8b8;
extern unsigned char LAB_0047a8e0;
extern unsigned char LAB_0047a929;
extern unsigned char LAB_0047a995;
extern unsigned char LAB_0047a9bb;
extern unsigned char LAB_0047a9f3;
extern unsigned char LAB_0047aa2e;
extern unsigned char LAB_0047aa5b;
extern unsigned char LAB_0047aa88;
extern unsigned char LAB_0047aabb;
extern unsigned char LAB_0047aaeb;
extern unsigned char LAB_0047ab2e;
extern unsigned char LAB_0047ab79;
extern unsigned char LAB_0047abab;
extern unsigned char LAB_0047abd0;
extern unsigned char LAB_0047abf0;
extern unsigned char LAB_0047ac10;
extern unsigned char LAB_0047ac43;
extern unsigned char LAB_0047ac68;
extern unsigned char LAB_0047ac90;
extern unsigned char LAB_0047acb0;
extern unsigned char LAB_0047acf9;
extern unsigned char LAB_0047ad9d;
extern unsigned char LAB_0047adcb;
extern unsigned char LAB_0047adf8;
extern unsigned char LAB_0047ae36;
extern unsigned char LAB_0047ae84;
extern unsigned char LAB_0047aeab;
extern unsigned char LAB_0047aed8;
extern unsigned char LAB_0047af08;
extern unsigned char LAB_0047af38;
extern unsigned char LAB_0047af70;
extern unsigned char LAB_0047af90;
extern unsigned char LAB_0047afb8;
extern unsigned char LAB_0047afd3;
extern unsigned char LAB_0047ee91;

/* PTR_AtlGetThreadACPThunk_ (1) */
extern unsigned char PTR_AtlGetThreadACPThunk_004afbfc;

/* PTR_ClientToScreen_ (1) */
extern unsigned char PTR_ClientToScreen_0047f1ec;

/* PTR_CloseHandle_ (1) */
extern unsigned char PTR_CloseHandle_0047f04c;

/* PTR_CoCreateInstance_ (1) */
extern unsigned char PTR_CoCreateInstance_0047f208;

/* PTR_CoInitialize_ (1) */
extern unsigned char PTR_CoInitialize_0047f20c;

/* PTR_CoUninitialize_ (1) */
extern unsigned char PTR_CoUninitialize_0047f204;

/* PTR_CreateEventW_ (1) */
extern unsigned char PTR_CreateEventW_0047f08c;

/* PTR_CreateFileA_ (1) */
extern unsigned char PTR_CreateFileA_0047f174;

/* PTR_CreateFileW_ (1) */
extern unsigned char PTR_CreateFileW_0047f070;

/* PTR_CreateThread_ (1) */
extern unsigned char PTR_CreateThread_0047f0c0;

/* PTR_CreateWindowExW_ (1) */
extern unsigned char PTR_CreateWindowExW_0047f1dc;

/* PTR_DAT_ (47) */
extern unsigned char PTR_DAT_00489650;
extern unsigned char PTR_DAT_0048be58;
extern unsigned char PTR_DAT_0048be5c;
extern unsigned char PTR_DAT_0048be60;
extern unsigned char PTR_DAT_0049d68c;
extern unsigned char PTR_DAT_0049d698;
extern unsigned char PTR_DAT_004ae004;
extern unsigned char PTR_DAT_004ae414;
extern unsigned char PTR_DAT_004ae614;
extern unsigned char PTR_DAT_004ae6b8;
extern unsigned char PTR_DAT_004ae7a8;
extern unsigned char PTR_DAT_004aef20;
extern unsigned char PTR_DAT_004aef78;
extern unsigned char PTR_DAT_004af100;
extern unsigned char PTR_DAT_004af368;
extern unsigned char PTR_DAT_004af840;
extern unsigned char PTR_DAT_004afca0;
extern unsigned char PTR_DAT_004afca4;
extern unsigned char PTR_DAT_004afce0;
extern unsigned char PTR_DAT_004afd18;
extern unsigned char PTR_DAT_004afd3c;
extern unsigned char PTR_DAT_004afe4c;
extern unsigned char PTR_DAT_004afe50;
extern unsigned char PTR_DAT_004afed0;
extern unsigned char PTR_DAT_004aff3c;
extern unsigned char PTR_DAT_004b00c8;
extern unsigned char PTR_DAT_004b0818;
extern unsigned char PTR_DAT_004b15c0;
extern unsigned char PTR_DAT_004b1790;
extern unsigned char PTR_DAT_004b17a0;
extern unsigned char PTR_DAT_004b17a8;
extern unsigned char PTR_DAT_004b1964;
extern unsigned char PTR_DAT_004b1968;
extern unsigned char PTR_DAT_004b1a28;
extern unsigned char PTR_DAT_004b1a2c;
extern unsigned char PTR_DAT_004b1a30;
extern unsigned char PTR_DAT_004b1a34;
extern unsigned char PTR_DAT_004b1a38;
extern unsigned char PTR_DAT_004b1a3c;
extern unsigned char PTR_DAT_004b1a40;
extern unsigned char PTR_DAT_004b1a44;
extern unsigned char PTR_DAT_004b1a48;
extern unsigned char PTR_DAT_004b1a4c;
extern unsigned char PTR_DAT_004b1d60;
extern unsigned char PTR_DAT_004b1fe0;
extern unsigned char PTR_DAT_004b2160;
extern unsigned char PTR_DAT_004b2174;

/* PTR_DefWindowProcW_ (1) */
extern unsigned char PTR_DefWindowProcW_0047f1e4;

/* PTR_DeleteCriticalSection_ (1) */
extern unsigned char PTR_DeleteCriticalSection_0047f1a4;

/* PTR_DeleteFileW_ (1) */
extern unsigned char PTR_DeleteFileW_0047f190;

/* PTR_DestroyWindow_ (1) */
extern unsigned char PTR_DestroyWindow_0047f1c8;

/* PTR_DestructExceptionObject_ (1) */
extern unsigned char PTR_DestructExceptionObject_00489630;

/* PTR_DispatchMessageW_ (1) */
extern unsigned char PTR_DispatchMessageW_0047f1c4;

/* PTR_EnterCriticalSection_ (1) */
extern unsigned char PTR_EnterCriticalSection_0047f074;

/* PTR_ExitProcess_ (1) */
extern unsigned char PTR_ExitProcess_0047f10c;

/* PTR_ExitThread_ (1) */
extern unsigned char PTR_ExitThread_0047f0bc;

/* PTR_FUN_ (6) */
extern unsigned char PTR_FUN_004895d0;
extern unsigned char PTR_FUN_0049e0e8;
extern unsigned char PTR_FUN_004af018;
extern unsigned char PTR_FUN_004af2fc;
extern unsigned char PTR_FUN_004af7ac;
extern unsigned char PTR_FUN_004b0070;

/* PTR_FindClose_ (1) */
extern unsigned char PTR_FindClose_0047f044;

/* PTR_FindFirstFileW_ (1) */
extern unsigned char PTR_FindFirstFileW_0047f048;

/* PTR_FindNextFileW_ (1) */
extern unsigned char PTR_FindNextFileW_0047f1ac;

/* PTR_FlushFileBuffers_ (1) */
extern unsigned char PTR_FlushFileBuffers_0047f06c;

/* PTR_FormatMessageW_ (1) */
extern unsigned char PTR_FormatMessageW_0047f084;

/* PTR_FreeEnvironmentStringsA_ (1) */
extern unsigned char PTR_FreeEnvironmentStringsA_0047f128;

/* PTR_FreeEnvironmentStringsW_ (1) */
extern unsigned char PTR_FreeEnvironmentStringsW_0047f130;

/* PTR_GetACP_ (1) */
extern unsigned char PTR_GetACP_0047f17c;

/* PTR_GetCPInfo_ (1) */
extern unsigned char PTR_GetCPInfo_0047f110;

/* PTR_GetClientRect_ (1) */
extern unsigned char PTR_GetClientRect_0047f1e8;

/* PTR_GetCommandLineA_ (1) */
extern unsigned char PTR_GetCommandLineA_0047f0ac;

/* PTR_GetCommandLineW_ (1) */
extern unsigned char PTR_GetCommandLineW_0047f198;

/* PTR_GetComputerNameW_ (1) */
extern unsigned char PTR_GetComputerNameW_0047f184;

/* PTR_GetConsoleCP_ (1) */
extern unsigned char PTR_GetConsoleCP_0047f15c;

/* PTR_GetConsoleMode_ (1) */
extern unsigned char PTR_GetConsoleMode_0047f160;

/* PTR_GetConsoleOutputCP_ (1) */
extern unsigned char PTR_GetConsoleOutputCP_0047f16c;

/* PTR_GetCurrentProcessId_ (1) */
extern unsigned char PTR_GetCurrentProcessId_0047f148;

/* PTR_GetCurrentProcess_ (1) */
extern unsigned char PTR_GetCurrentProcess_0047f0dc;

/* PTR_GetCurrentThreadId_ (1) */
extern unsigned char PTR_GetCurrentThreadId_0047f07c;

/* PTR_GetEnvironmentStringsW_ (1) */
extern unsigned char PTR_GetEnvironmentStringsW_0047f134;

/* PTR_GetEnvironmentStrings_ (1) */
extern unsigned char PTR_GetEnvironmentStrings_0047f12c;

/* PTR_GetExitCodeThread_ (1) */
extern unsigned char PTR_GetExitCodeThread_0047f094;

/* PTR_GetFileAttributesW_ (1) */
extern unsigned char PTR_GetFileAttributesW_0047f034;

/* PTR_GetFileSize_ (1) */
extern unsigned char PTR_GetFileSize_0047f068;

/* PTR_GetFileType_ (1) */
extern unsigned char PTR_GetFileType_0047f13c;

/* PTR_GetLastError_ (1) */
extern unsigned char PTR_GetLastError_0047f1b4;

/* PTR_GetLocalTime_ (1) */
extern unsigned char PTR_GetLocalTime_0047f03c;

/* PTR_GetLocaleInfoA_ (1) */
extern unsigned char PTR_GetLocaleInfoA_0047f178;

/* PTR_GetModuleFileNameA_ (1) */
extern unsigned char PTR_GetModuleFileNameA_0047f124;

/* PTR_GetModuleFileNameW_ (1) */
extern unsigned char PTR_GetModuleFileNameW_0047f194;

/* PTR_GetModuleHandleA_ (1) */
extern unsigned char PTR_GetModuleHandleA_0047f0ec;

/* PTR_GetOEMCP_ (1) */
extern unsigned char PTR_GetOEMCP_0047f114;

/* PTR_GetProcAddress_ (1) */
extern unsigned char PTR_GetProcAddress_0047f0e8;

/* PTR_GetProcessHeap_ (1) */
extern unsigned char PTR_GetProcessHeap_0047f0b0;

/* PTR_GetStartupInfoA_ (1) */
extern unsigned char PTR_GetStartupInfoA_0047f0b4;

/* PTR_GetStdHandle_ (1) */
extern unsigned char PTR_GetStdHandle_0047f120;

/* PTR_GetStockObject_ (1) */
extern unsigned char PTR_GetStockObject_0047f028;

/* PTR_GetStringTypeA_ (1) */
extern unsigned char PTR_GetStringTypeA_0047f154;

/* PTR_GetStringTypeW_ (1) */
extern unsigned char PTR_GetStringTypeW_0047f158;

/* PTR_GetSystemMetrics_ (1) */
extern unsigned char PTR_GetSystemMetrics_0047f1f0;

/* PTR_GetSystemTimeAsFileTime_ (1) */
extern unsigned char PTR_GetSystemTimeAsFileTime_0047f14c;

/* PTR_GetTempPathW_ (1) */
extern unsigned char PTR_GetTempPathW_0047f038;

/* PTR_GetThreadLocale_ (1) */
extern unsigned char PTR_GetThreadLocale_0047f0d8;

/* PTR_GetTickCount_ (1) */
extern unsigned char PTR_GetTickCount_0047f144;

/* PTR_GetVersionExA_ (1) */
extern unsigned char PTR_GetVersionExA_0047f030;

/* PTR_HeapAlloc_ (1) */
extern unsigned char PTR_HeapAlloc_0047f0a0;

/* PTR_HeapCreate_ (1) */
extern unsigned char PTR_HeapCreate_0047f0cc;

/* PTR_HeapDestroy_ (1) */
extern unsigned char PTR_HeapDestroy_0047f0c8;

/* PTR_HeapFree_ (1) */
extern unsigned char PTR_HeapFree_0047f09c;

/* PTR_HeapReAlloc_ (1) */
extern unsigned char PTR_HeapReAlloc_0047f0a4;

/* PTR_HeapSize_ (1) */
extern unsigned char PTR_HeapSize_0047f0b8;

/* PTR_InitializeCriticalSection_ (1) */
extern unsigned char PTR_InitializeCriticalSection_0047f1a8;

/* PTR_InterlockedDecrement_ (1) */
extern unsigned char PTR_InterlockedDecrement_0047f108;

/* PTR_InterlockedExchange_ (1) */
extern unsigned char PTR_InterlockedExchange_0047f180;

/* PTR_InterlockedIncrement_ (1) */
extern unsigned char PTR_InterlockedIncrement_0047f100;

/* PTR_IsDebuggerPresent_ (1) */
extern unsigned char PTR_IsDebuggerPresent_0047f0e4;

/* PTR_LAB_ (13) */
extern unsigned char PTR_LAB_0041948c;
extern unsigned char PTR_LAB_004b0074;
extern unsigned char PTR_LAB_004b0118;
extern unsigned char PTR_LAB_004b1870;
extern unsigned char PTR_LAB_004b1874;
extern unsigned char PTR_LAB_004b1878;
extern unsigned char PTR_LAB_004b187c;
extern unsigned char PTR_LAB_004b1880;
extern unsigned char PTR_LAB_004b1884;
extern unsigned char PTR_LAB_004b1888;
extern unsigned char PTR_LAB_004b188c;
extern unsigned char PTR_LAB_004b1890;
extern unsigned char PTR_LAB_004b1894;

/* PTR_LCMapStringA_ (1) */
extern unsigned char PTR_LCMapStringA_0047f118;

/* PTR_LCMapStringW_ (1) */
extern unsigned char PTR_LCMapStringW_0047f11c;

/* PTR_LeaveCriticalSection_ (1) */
extern unsigned char PTR_LeaveCriticalSection_0047f078;

/* PTR_LoadLibraryA_ (1) */
extern unsigned char PTR_LoadLibraryA_0047f150;

/* PTR_LocalFree_ (1) */
extern unsigned char PTR_LocalFree_0047f080;

/* PTR_LockFile_ (1) */
extern unsigned char PTR_LockFile_0047f058;

/* PTR_MessageBoxW_ (1) */
extern unsigned char PTR_MessageBoxW_0047f1cc;

/* PTR_MultiByteToWideChar_ (1) */
extern unsigned char PTR_MultiByteToWideChar_0047f1a0;

/* PTR_PTR_ (1) */
extern unsigned char PTR_PTR_004afbbc;

/* PTR_PeekMessageW_ (1) */
extern unsigned char PTR_PeekMessageW_0047f1bc;

/* PTR_PostQuitMessage_ (1) */
extern unsigned char PTR_PostQuitMessage_0047f1d0;

/* PTR_QueryPerformanceCounter_ (1) */
extern unsigned char PTR_QueryPerformanceCounter_0047f140;

/* PTR_RaiseException_ (1) */
extern unsigned char PTR_RaiseException_0047f098;

/* PTR_ReadFile_ (1) */
extern unsigned char PTR_ReadFile_0047f050;

/* PTR_RegCloseKey_ (1) */
extern unsigned char PTR_RegCloseKey_0047f010;

/* PTR_RegCreateKeyExW_ (1) */
extern unsigned char PTR_RegCreateKeyExW_0047f00c;

/* PTR_RegOpenKeyExW_ (1) */
extern unsigned char PTR_RegOpenKeyExW_0047f008;

/* PTR_RegQueryValueExW_ (1) */
extern unsigned char PTR_RegQueryValueExW_0047f004;

/* PTR_RegSetValueExW_ (1) */
extern unsigned char PTR_RegSetValueExW_0047f000;

/* PTR_RegisterClassExW_ (1) */
extern unsigned char PTR_RegisterClassExW_0047f1d8;

/* PTR_SetCursor_ (1) */
extern unsigned char PTR_SetCursor_0047f1d4;

/* PTR_SetEndOfFile_ (1) */
extern unsigned char PTR_SetEndOfFile_0047f064;

/* PTR_SetEvent_ (1) */
extern unsigned char PTR_SetEvent_0047f090;

/* PTR_SetFilePointer_ (1) */
extern unsigned char PTR_SetFilePointer_0047f060;

/* PTR_SetFocus_ (1) */
extern unsigned char PTR_SetFocus_0047f1e0;

/* PTR_SetHandleCount_ (1) */
extern unsigned char PTR_SetHandleCount_0047f138;

/* PTR_SetLastError_ (1) */
extern unsigned char PTR_SetLastError_0047f104;

/* PTR_SetUnhandledExceptionFilter_ (1) */
extern unsigned char PTR_SetUnhandledExceptionFilter_0047f0c4;

/* PTR_SetWindowPos_ (1) */
extern unsigned char PTR_SetWindowPos_0047f1f4;

/* PTR_Sleep_ (1) */
extern unsigned char PTR_Sleep_0047f040;

/* PTR_TerminateProcess_ (1) */
extern unsigned char PTR_TerminateProcess_0047f1b0;

/* PTR_TlsAlloc_ (1) */
extern unsigned char PTR_TlsAlloc_0047f0f4;

/* PTR_TlsFree_ (1) */
extern unsigned char PTR_TlsFree_0047f0fc;

/* PTR_TlsGetValue_ (1) */
extern unsigned char PTR_TlsGetValue_0047f0f0;

/* PTR_TlsSetValue_ (1) */
extern unsigned char PTR_TlsSetValue_0047f0f8;

/* PTR_TranslateMessage_ (1) */
extern unsigned char PTR_TranslateMessage_0047f1c0;

/* PTR_UnhandledExceptionFilter_ (1) */
extern unsigned char PTR_UnhandledExceptionFilter_0047f0e0;

/* PTR_UnlockFile_ (1) */
extern unsigned char PTR_UnlockFile_0047f05c;

/* PTR_VirtualAlloc_ (1) */
extern unsigned char PTR_VirtualAlloc_0047f0d4;

/* PTR_VirtualFree_ (1) */
extern unsigned char PTR_VirtualFree_0047f0d0;

/* PTR_WaitForSingleObject_ (1) */
extern unsigned char PTR_WaitForSingleObject_0047f088;

/* PTR_WideCharToMultiByte_ (1) */
extern unsigned char PTR_WideCharToMultiByte_0047f18c;

/* PTR_WriteConsoleA_ (1) */
extern unsigned char PTR_WriteConsoleA_0047f168;

/* PTR_WriteConsoleW_ (1) */
extern unsigned char PTR_WriteConsoleW_0047f170;

/* PTR_WriteFile_ (1) */
extern unsigned char PTR_WriteFile_0047f054;

/* PTR_caseD_0_ (2) */
extern unsigned char PTR_caseD_0_00448150;
extern unsigned char PTR_caseD_0_004491b0;

/* PTR_exit_ (1) */
extern unsigned char PTR_exit_004b1194;

/* PTR_fpmath_ (1) */
extern unsigned char PTR_fpmath_004895c8;

/* PTR_lstrlenA_ (1) */
extern unsigned char PTR_lstrlenA_0047f19c;

/* PTR_lstrlenW_ (1) */
extern unsigned char PTR_lstrlenW_0047f188;

/* PTR_s_1_1_3_00487594_ (1) */
extern unsigned char PTR_s_1_1_3_00487594_004b2134;

/* PTR_s_bad_allocation_ (1) */
extern unsigned char PTR_s_bad_allocation_004b0e4c;

/* PTR_s_buffer_error_ (1) */
extern unsigned char PTR_s_buffer_error_004b2154;

/* PTR_s_insufficient_memory_ (1) */
extern unsigned char PTR_s_insufficient_memory_004b2150;

/* PTR_s_stream_error_ (1) */
extern unsigned char PTR_s_stream_error_004b2148;

/* PTR_timeGetTime_ (1) */
extern unsigned char PTR_timeGetTime_0047f1fc;

/* PTR_u_Config_ (1) */
extern unsigned char PTR_u_Config_004ae5e8;

/* PTR_u_Software_SleepTeam_Bulanci_0047f66c_ (1) */
extern unsigned char PTR_u_Software_SleepTeam_Bulanci_0047f66c_004ae000;

/* PTR_u_Windowed_ (1) */
extern unsigned char PTR_u_Windowed_004afc9c;

/* PTR_u_null_0048ae14_ (1) */
extern unsigned char PTR_u_null_0048ae14_004b1fe4;

/* s_1_1_3_ (1) */
extern unsigned char s_1_1_3_00487594;

/* s_1_IND_ (1) */
extern unsigned char s_1_IND_0048af3c;

/* s_1_INF_ (1) */
extern unsigned char s_1_INF_0048af34;

/* s_1_QNAN_ (1) */
extern unsigned char s_1_QNAN_0048af2c;

/* s_1_SNAN_ (1) */
extern unsigned char s_1_SNAN_0048af44;

/* s_CONOUT_ (1) */
extern unsigned char s_CONOUT_0048af4c;

/* s_CorExitProcess_ (1) */
extern unsigned char s_CorExitProcess_00489678;

/* s_DecodePointer_ (1) */
extern unsigned char s_DecodePointer_004895f4;

/* s_EncodePointer_ (1) */
extern unsigned char s_EncodePointer_004895d4;

/* s_FlsAlloc_ (1) */
extern unsigned char s_FlsAlloc_00489624;

/* s_FlsFree_ (1) */
extern unsigned char s_FlsFree_00489604;

/* s_FlsGetValue_ (1) */
extern unsigned char s_FlsGetValue_00489618;

/* s_FlsSetValue_ (1) */
extern unsigned char s_FlsSetValue_0048960c;

/* s_GetActiveWindow_ (1) */
extern unsigned char s_GetActiveWindow_0048adec;

/* s_GetLastActivePopup_ (1) */
extern unsigned char s_GetLastActivePopup_0048add8;

/* s_GetProcessWindowStation_ (1) */
extern unsigned char s_GetProcessWindowStation_0048ada4;

/* s_GetUserObjectInformationA_ (1) */
extern unsigned char s_GetUserObjectInformationA_0048adbc;

/* s_InitializeCriticalSectionAndSpin_ (1) */
extern unsigned char s_InitializeCriticalSectionAndSpin_0048a438;

/* s_KERNEL32_ (1) */
extern unsigned char s_KERNEL32_00489d14;

/* s_KERNEL32_DLL_ (1) */
extern unsigned char s_KERNEL32_DLL_004895e4;

/* s_MessageBoxA_ (1) */
extern unsigned char s_MessageBoxA_0048adfc;

/* s_Microsoft_Visual_C_Runtime_Lib_ (1) */
extern unsigned char s_Microsoft_Visual_C_Runtime_Lib_00489c78;

/* s_Runtime_Error_Program_ (1) */
extern unsigned char s_Runtime_Error_Program_00489cc0;

/* s_USER32_DLL_ (1) */
extern unsigned char s_USER32_DLL_0048ae08;

/* s_Unknown_exception_ (1) */
extern unsigned char s_Unknown_exception_00489664;

/* s_bad_exception_ (1) */
extern unsigned char s_bad_exception_00489640;

/* s_e_000_ (1) */
extern unsigned char s_e_000_00489cdc;

/* s_empty_distance_tree_with_lengths_ (1) */
extern unsigned char s_empty_distance_tree_with_lengths_0049ef78;

/* s_incomplete_distance_tree_ (1) */
extern unsigned char s_incomplete_distance_tree_0049ef9c;

/* s_incomplete_dynamic_bit_lengths_t_ (1) */
extern unsigned char s_incomplete_dynamic_bit_lengths_t_0049eee8;

/* s_incomplete_literal_length_tree_ (1) */
extern unsigned char s_incomplete_literal_length_tree_0049ef34;

/* s_incorrect_data_check_ (1) */
extern unsigned char s_incorrect_data_check_0049e080;

/* s_incorrect_header_check_ (1) */
extern unsigned char s_incorrect_header_check_0049e098;

/* s_invalid_bit_length_repeat_ (1) */
extern unsigned char s_invalid_bit_length_repeat_0049e1a4;

/* s_invalid_block_type_ (1) */
extern unsigned char s_invalid_block_type_0049e204;

/* s_invalid_distance_code_ (1) */
extern unsigned char s_invalid_distance_code_0049ecdc;

/* s_invalid_literal_length_code_ (1) */
extern unsigned char s_invalid_literal_length_code_0049ecc0;

/* s_invalid_stored_block_lengths_ (1) */
extern unsigned char s_invalid_stored_block_lengths_0049e1e4;

/* s_invalid_window_size_ (1) */
extern unsigned char s_invalid_window_size_0049e0b0;

/* s_kernel32_dll_ (1) */
extern unsigned char s_kernel32_dll_0048a460;

/* s_mscoree_dll_ (1) */
extern unsigned char s_mscoree_dll_00489688;

/* s_oversubscribed_distance_tree_ (1) */
extern unsigned char s_oversubscribed_distance_tree_0049efb8;

/* s_oversubscribed_dynamic_bit_lengt_ (1) */
extern unsigned char s_oversubscribed_dynamic_bit_lengt_0049ef0c;

/* s_oversubscribed_literal_length_tr_ (1) */
extern unsigned char s_oversubscribed_literal_length_tr_0049ef54;

/* s_program_name_unknown_ (1) */
extern unsigned char s_program_name_unknown_00489ca8;

/* s_too_many_length_or_distance_symb_ (1) */
extern unsigned char s_too_many_length_or_distance_symb_0049e1c0;

/* s_unknown_compression_method_ (1) */
extern unsigned char s_unknown_compression_method_0049e0c4;

#ifdef __cplusplus
}
#endif

#endif
