[package]
name = "bulanci_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bulanci_core = { path = "../core" }
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = { version = "0.3", features = ["sink"] }
serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.0", features = ["alloc"] }
anyhow = "1.0"
