; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	C:\Users\mstagl-dev\Documents\GitHub\bulanci\src\bulanci\CTcpIpConfig.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	??0CWindow@@QAE@IIIIE@Z				; CWindow::CWindow
EXTRN	?CWindow_BuildAt@CWindow@@QAEPAIIIIIE@Z:PROC	; CWindow::CWindow_BuildAt
; Function compile flags: /Ogtpy
;	COMDAT ??0CWindow@@QAE@IIIIE@Z
_TEXT	SEGMENT
_param_1$ = 8						; size = 4
_param_2$ = 12						; size = 4
_param_3$ = 16						; size = 4
_param_4$ = 20						; size = 4
_param_5$ = 24						; size = 1
??0CWindow@@QAE@IIIIE@Z PROC				; CWindow::CWindow, COMDAT
; _this$ = ecx
; File c:\users\mstagl-dev\documents\github\bulanci\include\bulanci\cwindow.h
; Line 10
	mov	eax, DWORD PTR _param_5$[esp-4]
	mov	edx, DWORD PTR _param_3$[esp-4]
	push	esi
	push	eax
	mov	eax, DWORD PTR _param_2$[esp+4]
	mov	esi, ecx
	mov	ecx, DWORD PTR _param_4$[esp+4]
	push	ecx
	mov	ecx, DWORD PTR _param_1$[esp+8]
	push	edx
	push	eax
	push	ecx
	mov	ecx, esi
	call	?CWindow_BuildAt@CWindow@@QAEPAIIIIIE@Z	; CWindow::CWindow_BuildAt
; Line 11
	mov	eax, esi
	pop	esi
	ret	20					; 00000014H
??0CWindow@@QAE@IIIIE@Z ENDP				; CWindow::CWindow
_TEXT	ENDS
PUBLIC	??0CBulanci@@QAE@PAF@Z				; CBulanci::CBulanci
EXTRN	?FUN_0042d510@CBulanci@@QAEPAHPAF@Z:PROC	; CBulanci::FUN_0042d510
; Function compile flags: /Ogtpy
;	COMDAT ??0CBulanci@@QAE@PAF@Z
_TEXT	SEGMENT
_param_1$ = 8						; size = 4
??0CBulanci@@QAE@PAF@Z PROC				; CBulanci::CBulanci, COMDAT
; _this$ = ecx
; File c:\users\mstagl-dev\documents\github\bulanci\include\bulanci\cbulanci.h
; Line 18
	mov	eax, DWORD PTR _param_1$[esp-4]
	push	esi
	mov	esi, ecx
	push	eax
	mov	DWORD PTR [esi], 0
	call	?FUN_0042d510@CBulanci@@QAEPAHPAF@Z	; CBulanci::FUN_0042d510
; Line 19
	mov	eax, esi
	pop	esi
	ret	4
??0CBulanci@@QAE@PAF@Z ENDP				; CBulanci::CBulanci
_TEXT	ENDS
PUBLIC	??_7CTcpIpConfig@@6B@				; CTcpIpConfig::`vftable'
PUBLIC	??0CTcpIpConfig@@QAE@XZ				; CTcpIpConfig::CTcpIpConfig
PUBLIC	??_R4CTcpIpConfig@@6B@				; CTcpIpConfig::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCTcpIpConfig@@@8			; CTcpIpConfig `RTTI Type Descriptor'
PUBLIC	??_R3CTcpIpConfig@@8				; CTcpIpConfig::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CTcpIpConfig@@8				; CTcpIpConfig::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CTcpIpConfig@@8			; CTcpIpConfig::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R13?0A@EA@CWindow@@8				; CWindow::`RTTI Base Class Descriptor at (4,-1,0,64)'
PUBLIC	??_R0?AVCWindow@@@8				; CWindow `RTTI Type Descriptor'
PUBLIC	??_R3CWindow@@8					; CWindow::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CWindow@@8					; CWindow::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CWindow@@8			; CWindow::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	?GetClassMeta@CTcpIpConfig@@UAEPAEXZ		; CTcpIpConfig::GetClassMeta
EXTRN	?CButton_BuildAt@CButton@@QAEPAIHGVCBulanci@@IIIPAI@Z:PROC ; CButton::CButton_BuildAt
EXTRN	?CEdit_BuildAt@CEdit@@QAEPAIIIIIIIII@Z:PROC	; CEdit::CEdit_BuildAt
EXTRN	?FUN_0042d0b0@_Globals@@QAEEPAHH@Z:PROC		; _Globals::FUN_0042d0b0
EXTRN	??1CBulanci@@QAE@XZ:PROC			; CBulanci::~CBulanci
EXTRN	?CStaticText_BuildAt@CStaticText@@QAEPAIIIHIVCBulanci@@III@Z:PROC ; CStaticText::CStaticText_BuildAt
EXTRN	_PTR_PTR_004afbbc:BYTE
EXTRN	?FUN_00447c42@_Globals@@SAPAXI@Z:PROC		; _Globals::FUN_00447c42
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
;	COMDAT ??_R1A@?0A@EA@CWindow@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CWindow@@8 DD FLAT:??_R0?AVCWindow@@@8	; CWindow::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWindow@@8
rdata$r	ENDS
;	COMDAT ??_R2CWindow@@8
rdata$r	SEGMENT
??_R2CWindow@@8 DD FLAT:??_R1A@?0A@EA@CWindow@@8	; CWindow::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CWindow@@8
rdata$r	SEGMENT
??_R3CWindow@@8 DD 00H					; CWindow::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CWindow@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCWindow@@@8
_DATA	SEGMENT
??_R0?AVCWindow@@@8 DD FLAT:??_7type_info@@6B@		; CWindow `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCWindow@@', 00H
_DATA	ENDS
;	COMDAT ??_R13?0A@EA@CWindow@@8
rdata$r	SEGMENT
??_R13?0A@EA@CWindow@@8 DD FLAT:??_R0?AVCWindow@@@8	; CWindow::`RTTI Base Class Descriptor at (4,-1,0,64)'
	DD	00H
	DD	04H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWindow@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CTcpIpConfig@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CTcpIpConfig@@8 DD FLAT:??_R0?AVCTcpIpConfig@@@8 ; CTcpIpConfig::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CTcpIpConfig@@8
rdata$r	ENDS
;	COMDAT ??_R2CTcpIpConfig@@8
rdata$r	SEGMENT
??_R2CTcpIpConfig@@8 DD FLAT:??_R1A@?0A@EA@CTcpIpConfig@@8 ; CTcpIpConfig::`RTTI Base Class Array'
	DD	FLAT:??_R13?0A@EA@CWindow@@8
rdata$r	ENDS
;	COMDAT ??_R3CTcpIpConfig@@8
rdata$r	SEGMENT
??_R3CTcpIpConfig@@8 DD 00H				; CTcpIpConfig::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CTcpIpConfig@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCTcpIpConfig@@@8
_DATA	SEGMENT
??_R0?AVCTcpIpConfig@@@8 DD FLAT:??_7type_info@@6B@	; CTcpIpConfig `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCTcpIpConfig@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CTcpIpConfig@@6B@
rdata$r	SEGMENT
??_R4CTcpIpConfig@@6B@ DD 00H				; CTcpIpConfig::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCTcpIpConfig@@@8
	DD	FLAT:??_R3CTcpIpConfig@@8
rdata$r	ENDS
;	COMDAT ??_7CTcpIpConfig@@6B@
CONST	SEGMENT
??_7CTcpIpConfig@@6B@ DD FLAT:??_R4CTcpIpConfig@@6B@	; CTcpIpConfig::`vftable'
	DD	FLAT:?GetClassMeta@CTcpIpConfig@@UAEPAEXZ
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0CTcpIpConfig@@QAE@XZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$0
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$1
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$2
__ehfuncinfo$??0CTcpIpConfig@@QAE@XZ DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$??0CTcpIpConfig@@QAE@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Ogtpy
xdata$x	ENDS
;	COMDAT ??0CTcpIpConfig@@QAE@XZ
_TEXT	SEGMENT
_okBtnStr$8932 = -20					; size = 4
_staticTextStr$8918 = -20				; size = 4
_cancelBtnStr$8941 = -16				; size = 4
__$EHRec$ = -12						; size = 12
??0CTcpIpConfig@@QAE@XZ PROC				; CTcpIpConfig::CTcpIpConfig, COMDAT
; _this$ = ecx
; File c:\users\mstagl-dev\documents\github\bulanci\src\bulanci\ctcpipconfig.cpp
; Line 13
	push	-1
	push	__ehhandler$??0CTcpIpConfig@@QAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 8
	push	ebx
	push	esi
	push	edi
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, esp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[esp+36]
	mov	DWORD PTR fs:0, eax
	mov	esi, ecx
	push	1
	push	160					; 000000a0H
	push	312					; 00000138H
	xor	ebx, ebx
	push	ebx
	lea	ecx, DWORD PTR [esi+4]
	push	ebx
	call	?CWindow_BuildAt@CWindow@@QAEPAIIIIIE@Z	; CWindow::CWindow_BuildAt
; Line 16
	push	152					; 00000098H
	mov	DWORD PTR [esi], OFFSET ??_7CTcpIpConfig@@6B@
	call	?FUN_00447c42@_Globals@@SAPAXI@Z	; _Globals::FUN_00447c42
	mov	edi, eax
	add	esp, 4
; Line 17
	cmp	edi, ebx
	je	SHORT $LN4@CTcpIpConf
; Line 18
	mov	eax, DWORD PTR _PTR_PTR_004afbbc
	mov	eax, DWORD PTR [eax+124]
	push	eax
	lea	ecx, DWORD PTR _staticTextStr$8918[esp+40]
	mov	DWORD PTR _staticTextStr$8918[esp+40], ebx
	call	?FUN_0042d510@CBulanci@@QAEPAHPAF@Z	; CBulanci::FUN_0042d510
; Line 23
	mov	ecx, DWORD PTR _staticTextStr$8918[esp+36]
	push	65710					; 000100aeH
	push	5
	push	1
	push	ecx
	push	60					; 0000003cH
	push	292					; 00000124H
	push	20					; 00000014H
	push	20					; 00000014H
	mov	ecx, edi
	mov	DWORD PTR __$EHRec$[esp+76], ebx
	call	?CStaticText_BuildAt@CStaticText@@QAEPAIIIHIVCBulanci@@III@Z ; CStaticText::CStaticText_BuildAt
; Line 24
	lea	ecx, DWORD PTR _staticTextStr$8918[esp+36]
	mov	DWORD PTR __$EHRec$[esp+44], -1
	call	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
$LN4@CTcpIpConf:
; Line 25
	push	ebx
	push	edi
	mov	ecx, esi
	call	?FUN_0042d0b0@_Globals@@QAEEPAHH@Z	; _Globals::FUN_0042d0b0
; Line 27
	push	184					; 000000b8H
	call	?FUN_00447c42@_Globals@@SAPAXI@Z	; _Globals::FUN_00447c42
	mov	edi, eax
	add	esp, 4
; Line 28
	cmp	edi, ebx
	je	SHORT $LN3@CTcpIpConf
; Line 32
	push	65711					; 000100afH
	push	ebx
	push	2
	push	18					; 00000012H
	push	60					; 0000003cH
	push	292					; 00000124H
	push	70					; 00000046H
	push	20					; 00000014H
	mov	ecx, edi
	call	?CEdit_BuildAt@CEdit@@QAEPAIIIIIIIII@Z	; CEdit::CEdit_BuildAt
$LN3@CTcpIpConf:
; Line 34
	push	ebx
	push	edi
	mov	ecx, esi
	call	?FUN_0042d0b0@_Globals@@QAEEPAHH@Z	; _Globals::FUN_0042d0b0
; Line 36
	push	152					; 00000098H
	call	?FUN_00447c42@_Globals@@SAPAXI@Z	; _Globals::FUN_00447c42
	mov	edi, eax
	add	esp, 4
; Line 37
	cmp	edi, ebx
	je	SHORT $LN2@CTcpIpConf
; Line 38
	mov	edx, DWORD PTR _PTR_PTR_004afbbc
	mov	eax, DWORD PTR [edx+116]
	push	eax
	lea	ecx, DWORD PTR _okBtnStr$8932[esp+40]
	mov	DWORD PTR _okBtnStr$8932[esp+40], ebx
	call	?FUN_0042d510@CBulanci@@QAEPAHPAF@Z	; CBulanci::FUN_0042d510
; Line 43
	mov	eax, DWORD PTR _okBtnStr$8932[esp+36]
	push	ebx
	push	20					; 00000014H
	push	1
	push	32770					; 00008002H
	push	eax
	push	115					; 00000073H
	push	73					; 00000049H
	mov	ecx, edi
	mov	DWORD PTR __$EHRec$[esp+72], 1
	call	?CButton_BuildAt@CButton@@QAEPAIHGVCBulanci@@IIIPAI@Z ; CButton::CButton_BuildAt
; Line 44
	lea	ecx, DWORD PTR _okBtnStr$8932[esp+36]
	mov	DWORD PTR __$EHRec$[esp+44], -1
	call	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
$LN2@CTcpIpConf:
; Line 45
	push	ebx
	push	edi
	mov	ecx, esi
	call	?FUN_0042d0b0@_Globals@@QAEEPAHH@Z	; _Globals::FUN_0042d0b0
; Line 47
	push	152					; 00000098H
	call	?FUN_00447c42@_Globals@@SAPAXI@Z	; _Globals::FUN_00447c42
	mov	edi, eax
	add	esp, 4
; Line 48
	cmp	edi, ebx
	je	SHORT $LN1@CTcpIpConf
; Line 49
	mov	ecx, DWORD PTR _PTR_PTR_004afbbc
	mov	eax, DWORD PTR [ecx+120]
	push	eax
	lea	ecx, DWORD PTR _cancelBtnStr$8941[esp+40]
	mov	DWORD PTR _cancelBtnStr$8941[esp+40], ebx
	call	?FUN_0042d510@CBulanci@@QAEPAHPAF@Z	; CBulanci::FUN_0042d510
; Line 54
	mov	edx, DWORD PTR _cancelBtnStr$8941[esp+36]
	push	ebx
	push	20					; 00000014H
	push	ebx
	push	32771					; 00008003H
	push	edx
	push	115					; 00000073H
	push	163					; 000000a3H
	mov	ecx, edi
	mov	DWORD PTR __$EHRec$[esp+72], 2
	call	?CButton_BuildAt@CButton@@QAEPAIHGVCBulanci@@IIIPAI@Z ; CButton::CButton_BuildAt
; Line 55
	lea	ecx, DWORD PTR _cancelBtnStr$8941[esp+36]
	mov	DWORD PTR __$EHRec$[esp+44], -1
	call	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
$LN1@CTcpIpConf:
; Line 56
	push	ebx
	push	edi
	mov	ecx, esi
	call	?FUN_0042d0b0@_Globals@@QAEEPAHH@Z	; _Globals::FUN_0042d0b0
; Line 59
	mov	eax, DWORD PTR [esi+40]
	sub	eax, DWORD PTR [esi+32]
; Line 63
	mov	ecx, DWORD PTR [esi+36]
	or	WORD PTR [esi+70], 8
	sub	DWORD PTR [esi+44], ecx
; Line 66
	add	eax, 300				; 0000012cH
	mov	DWORD PTR [esi+40], eax
	mov	DWORD PTR [esi+32], 300			; 0000012cH
	mov	DWORD PTR [esi+36], ebx
; Line 67
	mov	eax, esi
	mov	ecx, DWORD PTR __$EHRec$[esp+36]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 20					; 00000014H
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$0:
	lea	ecx, DWORD PTR _staticTextStr$8918[ebp]
	jmp	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$1:
	lea	ecx, DWORD PTR _okBtnStr$8932[ebp]
	jmp	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
__unwindfunclet$??0CTcpIpConfig@@QAE@XZ$2:
	lea	ecx, DWORD PTR _cancelBtnStr$8941[ebp]
	jmp	??1CBulanci@@QAE@XZ			; CBulanci::~CBulanci
__ehhandler$??0CTcpIpConfig@@QAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx-20]
	mov	ecx, DWORD PTR [edx-24]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0CTcpIpConfig@@QAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??0CTcpIpConfig@@QAE@XZ ENDP				; CTcpIpConfig::CTcpIpConfig
EXTRN	_DAT_004b34e8:BYTE
; Function compile flags: /Ogtpy
;	COMDAT ?GetClassMeta@CTcpIpConfig@@UAEPAEXZ
_TEXT	SEGMENT
?GetClassMeta@CTcpIpConfig@@UAEPAEXZ PROC		; CTcpIpConfig::GetClassMeta, COMDAT
; _this$ = ecx
; Line 73
	mov	eax, OFFSET _DAT_004b34e8
; Line 74
	ret	0
?GetClassMeta@CTcpIpConfig@@UAEPAEXZ ENDP		; CTcpIpConfig::GetClassMeta
_TEXT	ENDS
END
