import { defineConfig, type Plugin } from "vite-plus";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import path from "node:path";
import fs from "node:fs";
import { promises as fsp } from "node:fs";
import { createReadStream } from "node:fs";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import { WebSocketServer } from "ws";
import { toSocket } from "vscode-ws-jsonrpc";
import { createWebSocketConnection, createServerProcess, forward } from "vscode-ws-jsonrpc/server";

// Repo layout (the gallery sits four levels deep):
//   <repo>/ghidra_analysis/asset_catalog/gallery/vite.config.ts
//                                       ^- __dirname
const repoRoot       = path.resolve(__dirname, "../../..");
const catalogDir     = path.resolve(repoRoot, "ghidra_analysis/asset_catalog");
const overlayDir     = path.resolve(repoRoot, "unpacked/overlay");
const indexCachePath = path.resolve(catalogDir, ".overlay-index.cache.json");
// Layered pak root (master + mod paks + load-order profile). The broker
// write-throughs live pushes into the active mod pak here so they persist
// across restarts and the native client picks them up via its disk watcher.
const paksDir        = path.resolve(repoRoot, "open_bulanci/paks");
// The codegen handle table lives with the built assets, not in the
// catalog dir — the live-engine bridge reads it to map assets to push
// target hashes.  Exposed under the catalog prefix for convenience.
const assetsManifest = path.resolve(repoRoot, "open_bulanci/assets/manifest.json");

const MIMES: Record<string, string> = {
  ".json": "application/json",
  ".toml": "text/plain; charset=utf-8",
  ".txt":  "text/plain; charset=utf-8",
  ".lua":  "text/plain; charset=utf-8",
  ".asm":  "text/plain; charset=utf-8",
  ".png":  "image/png",
  ".gif":  "image/gif",
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".wav":  "audio/wav",
  ".mp3":  "audio/mpeg",
  // The embedded live-engine preview (`/play/*`, served by bulanciWebGame).
  ".wasm": "application/wasm",
  ".js":   "text/javascript; charset=utf-8",
  ".mjs":  "text/javascript; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".css":  "text/css; charset=utf-8",
};

// The wasm web build (`open_bulanci/web/`: index.html + bulanci_client.js/.wasm).
// Served at `/play/` so the editor can embed the REAL engine as a live preview,
// same-origin with the broker below. The artifacts are built + deployed by the
// auto-build orchestrator in `bulanciWebEngine` (or scripts/build-web.ps1).
const obRoot      = path.resolve(repoRoot, "open_bulanci");
const webGameDir  = path.resolve(obRoot, "web");
const webWasmFile = path.resolve(webGameDir, "bulanci_client.wasm");

/** Vite plugin that serves the catalog + unpacked overlay straight
 *  from the local filesystem under `/data/catalog/*` and
 *  `/data/overlay/*`.  Lets `bun run dev` work without a Python
 *  backend — the same layout the production static build expects. */
function bulanciDataSource(): Plugin {
  return {
    name: "bulanci-data-source",
    configureServer(server) {
      server.middlewares.use(async (req, res, next) => {
        const url    = req.url ?? "";
        const method = req.method ?? "GET";
        try {
          // Capability probe — the React app pings this once at boot to
          // decide whether to expose editor controls.  Only the Vite
          // dev plugin replies 200; the static `serve.py` shim 404s.
          if (url === "/data/api/writable") {
            res.statusCode = 200;
            res.setHeader("Content-Type", "application/json");
            res.end(`{"writable":true}`);
            return;
          }

          if (url.startsWith("/data/catalog/overlay-index.json")) {
            return await sendOverlayIndex(res);
          }

          // Codegen handle table — sourced from open_bulanci/assets,
          // not catalogDir, so it gets its own route.  Optional: 404
          // when the assets haven't been built yet.
          if (url.startsWith("/data/catalog/manifest.json")) {
            try {
              const txt = await fsp.readFile(assetsManifest, "utf-8");
              res.statusCode = 200;
              res.setHeader("Content-Type",  "application/json");
              res.setHeader("Cache-Control", "no-store");
              res.end(txt);
            } catch {
              res.statusCode = 404;
              res.end("manifest.json not found");
            }
            return;
          }

          // Asset-editor write back: only `registry.json` for now,
          // since folder / slug / notes edits go through there.  Other
          // catalog files are regenerated by python scripts.
          if (
            method === "PUT" &&
            url === "/data/catalog/registry.json"
          ) {
            return await receiveRegistry(req, res);
          }

          // Scene discovery — flat list of every scene declared across the
          // load-order profile's paks (the scene editor's browser).
          if (url.split("?")[0] === "/data/scenes") {
            return await sendScenes(res);
          }

          // Pak script index — every `.luau` in a pak (the Scripts panel's
          // file browser, so it can open lib/startgame1.luau, poem.luau, …).
          if (url.split("?")[0].startsWith("/data/pak-scripts/")) {
            const pak = decodeURIComponent(url.slice("/data/pak-scripts/".length).split("?")[0]);
            return sendPakScripts(res, pak);
          }

          // Pak file IO for the scene editor — read/write a scene doc or
          // attached script by `<pakId>/<relpath>`. GET reads text, PUT
          // persists it (the native client's disk watcher then hot-reloads;
          // the same path in a higher mod pak overlays the base scene).
          if (url.startsWith("/data/pak/")) {
            const rel = decodeURIComponent(url.slice("/data/pak/".length).split("?")[0]);
            if (method === "PUT") return await writePakFile(req, res, rel);
            return await readPakFile(res, rel);
          }

          if (url.startsWith("/data/catalog/")) {
            const rel = decodeURIComponent(url.slice("/data/catalog/".length).split("?")[0]);
            return await sendFile(res, path.join(catalogDir, rel));
          }
          if (url.startsWith("/data/overlay/")) {
            const rel = decodeURIComponent(url.slice("/data/overlay/".length).split("?")[0]);
            return await sendFile(res, path.join(overlayDir, rel));
          }
        } catch (err) {
          console.error("[bulanci-data-source]", url, err);
          res.statusCode = 500;
          res.end("data source error");
          return;
        }
        next();
      });
    },
  };
}

/** Buffer the PUT body, validate it as JSON, and write it to
 *  `registry.json` atomically (write to `*.tmp` then rename, so a
 *  crash mid-write doesn't leave a half-rewritten registry behind). */
async function receiveRegistry(
  req:  import("node:http").IncomingMessage,
  res:  import("node:http").ServerResponse,
): Promise<void> {
  const chunks: Buffer[] = [];
  let   total = 0;
  // Refuse anything over a generous 4 MB so a runaway editor can't
  // exhaust memory.  registry.json is currently ~10 kB.
  const MAX_BYTES = 4 * 1024 * 1024;
  for await (const chunk of req) {
    chunks.push(chunk as Buffer);
    total += (chunk as Buffer).length;
    if (total > MAX_BYTES) {
      res.statusCode = 413;
      res.end("registry.json too large");
      return;
    }
  }
  const body = Buffer.concat(chunks).toString("utf-8");
  // Structural sanity check — confirm the payload parses as JSON
  // *and* has the registry's top-level shape before we overwrite the
  // file.  Catches the editor writing TOML / garbage by mistake.
  try {
    const obj = JSON.parse(body);
    if (typeof obj !== "object" || obj === null
        || !("assets" in obj || "scripts" in obj || "folders" in obj)) {
      throw new Error("missing top-level assets/scripts/folders");
    }
  } catch (err) {
    res.statusCode = 400;
    res.end(`payload is not a valid registry.json: ${err}`);
    return;
  }
  const target = path.join(catalogDir, "registry.json");
  const tmp    = `${target}.${process.pid}.tmp`;
  await fsp.writeFile(tmp, body, "utf-8");
  await fsp.rename(tmp, target);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(`{"ok":true,"bytes":${body.length}}`);
  console.log(`[bulanci-data-source] registry.json updated (${body.length} bytes)`);
}

async function sendFile(res: import("node:http").ServerResponse, filePath: string): Promise<void> {
  // Guard against `..` traversal (the path must still resolve under
  // catalogDir or overlayDir).
  const resolved = path.resolve(filePath);
  if (!resolved.startsWith(catalogDir) && !resolved.startsWith(overlayDir)) {
    res.statusCode = 403; res.end("forbidden"); return;
  }
  try {
    const stat = await fsp.stat(resolved);
    if (!stat.isFile()) { res.statusCode = 404; res.end("not a file"); return; }
    res.statusCode = 200;
    res.setHeader("Content-Type",   MIMES[path.extname(resolved).toLowerCase()] || "application/octet-stream");
    res.setHeader("Content-Length", stat.size);
    res.setHeader("Cache-Control",  "no-store");
    createReadStream(resolved).pipe(res);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") {
      res.statusCode = 404; res.end("not found");
    } else throw err;
  }
}

let _indexCache: { mtime: number; payload: string } | null = null;

async function sendOverlayIndex(res: import("node:http").ServerResponse): Promise<void> {
  // Skip the readdir hit on hot-reload by caching against the overlay
  // dir's mtime.  Once the underlying directory changes (e.g. a fresh
  // unpack) we regenerate.
  const stat = await fsp.stat(overlayDir);
  const mtime = stat.mtimeMs;
  if (_indexCache && _indexCache.mtime === mtime) {
    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");
    res.end(_indexCache.payload);
    return;
  }
  const entries = await fsp.readdir(overlayDir, { withFileTypes: true });
  const files   = entries.filter(e => e.isFile()).map(e => e.name).sort();
  const payload = JSON.stringify(files);
  _indexCache = { mtime, payload };
  try {
    fs.writeFileSync(indexCachePath, payload);
  } catch { /* best effort */ }
  res.statusCode = 200;
  res.setHeader("Content-Type",  "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(payload);
}

// ---------------------------------------------------------------------
// scene discovery + pak file IO (scene editor)
// ---------------------------------------------------------------------

interface SceneRefWire {
  pak: string;
  name: string;
  kind: "declarative" | "module";
  doc?: string;
  scripts: string[];
  file?: string;
  writable: boolean;
}

/** Read the load-order profile and each folder pak's `pak.json`, flattening
 *  the `scenes` tables into a single list tagged by owning pak. */
function enumerateScenes(): SceneRefWire[] {
  let profile: { paks?: { id?: string; kind?: string; path?: string }[] } = {};
  try {
    profile = JSON.parse(fs.readFileSync(path.join(paksDir, "profile.json"), "utf-8"));
  } catch {
    return [];
  }
  const out: SceneRefWire[] = [];
  for (const entry of profile.paks ?? []) {
    if (!entry?.id || entry.kind === "master") continue; // master ships embedded
    const folder = entry.path ?? entry.id;
    const dir = path.join(paksDir, folder);
    let manifest: { scenes?: Record<string, { file?: string; doc?: string; scripts?: string[] }> } = {};
    try {
      manifest = JSON.parse(fs.readFileSync(path.join(dir, "pak.json"), "utf-8"));
    } catch {
      continue;
    }
    // A folder mod pak is always writable through the broker.
    const writable = entry.kind === "mod";
    for (const [name, scene] of Object.entries(manifest.scenes ?? {})) {
      out.push({
        pak: entry.id,
        name,
        kind: scene.doc ? "declarative" : "module",
        doc: scene.doc,
        scripts: scene.scripts ?? [],
        file: scene.file,
        writable,
      });
    }
  }
  return out;
}

function sendScenes(res: import("node:http").ServerResponse): void {
  const payload = JSON.stringify({ scenes: enumerateScenes() });
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(payload);
}

/** Map a pak id to its on-disk folder via the profile (defaults to the id). */
function pakFolder(pak: string): string {
  try {
    const profile = JSON.parse(fs.readFileSync(path.join(paksDir, "profile.json"), "utf-8")) as {
      paks?: { id?: string; path?: string }[];
    };
    const entry = (profile.paks ?? []).find(p => p.id === pak);
    if (entry?.path) return entry.path;
  } catch { /* default to id */ }
  return pak;
}

/** Recursively list every `.luau` under a pak folder, as pak-relative
 *  POSIX paths (the Scripts panel's file browser). */
function sendPakScripts(res: import("node:http").ServerResponse, pak: string): void {
  if (!/^[A-Za-z0-9_-]+$/.test(pak)) {
    res.statusCode = 400; res.end("bad pak id"); return;
  }
  const root = path.resolve(paksDir, pakFolder(pak));
  const out: string[] = [];
  const walk = (dir: string): void => {
    let ents: fs.Dirent[] = [];
    try { ents = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const ent of ents) {
      const abs = path.join(dir, ent.name);
      if (ent.isDirectory()) { walk(abs); continue; }
      if (ent.name.endsWith(".luau")) {
        out.push(path.relative(root, abs).replace(/\\/g, "/"));
      }
    }
  };
  if (root === paksDir || root.startsWith(paksDir + path.sep)) walk(root);
  out.sort();
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.setHeader("Cache-Control", "no-store");
  res.end(JSON.stringify({ scripts: out }));
}

/** Resolve `<pakId>/<relpath>` to an absolute path under `paksDir`,
 *  refusing `..` escapes and unknown paks. Returns null on any violation. */
function resolvePakFile(rel: string): { abs: string; pak: string; relPath: string } | null {
  const slash = rel.indexOf("/");
  if (slash <= 0) return null;
  const pak = rel.slice(0, slash);
  const relPath = rel.slice(slash + 1);
  if (!relPath || !/^[A-Za-z0-9_-]+$/.test(pak)) return null;
  // Map pak id -> folder via the profile (defaults to the id).
  let folder = pak;
  try {
    const profile = JSON.parse(fs.readFileSync(path.join(paksDir, "profile.json"), "utf-8")) as {
      paks?: { id?: string; path?: string }[];
    };
    const entry = (profile.paks ?? []).find(p => p.id === pak);
    if (entry?.path) folder = entry.path;
  } catch { /* default to id */ }
  const pakDir = path.resolve(paksDir, folder);
  const abs = path.resolve(pakDir, relPath);
  if (abs !== pakDir && !abs.startsWith(pakDir + path.sep)) return null;
  return { abs, pak, relPath };
}

async function readPakFile(res: import("node:http").ServerResponse, rel: string): Promise<void> {
  const r = resolvePakFile(rel);
  if (!r) { res.statusCode = 400; res.end("bad pak path"); return; }
  try {
    const stat = await fsp.stat(r.abs);
    if (!stat.isFile()) { res.statusCode = 404; res.end("not a file"); return; }
    res.statusCode = 200;
    res.setHeader("Content-Type", MIMES[path.extname(r.abs).toLowerCase()] || "text/plain; charset=utf-8");
    res.setHeader("Content-Length", stat.size);
    res.setHeader("Cache-Control", "no-store");
    createReadStream(r.abs).pipe(res);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") { res.statusCode = 404; res.end("not found"); }
    else throw err;
  }
}

async function writePakFile(
  req: import("node:http").IncomingMessage,
  res: import("node:http").ServerResponse,
  rel: string,
): Promise<void> {
  const r = resolvePakFile(rel);
  if (!r) { res.statusCode = 400; res.end("bad pak path"); return; }
  const chunks: Buffer[] = [];
  let total = 0;
  const MAX = 8 * 1024 * 1024;
  for await (const chunk of req) {
    chunks.push(chunk as Buffer);
    total += (chunk as Buffer).length;
    if (total > MAX) { res.statusCode = 413; res.end("file too large"); return; }
  }
  const body = Buffer.concat(chunks).toString("utf-8");
  // A `.scene.json` doc must parse as JSON before we overwrite it; scripts
  // are written as-is (the editor's Luau LSP validates those).
  if (r.relPath.endsWith(".json")) {
    try { JSON.parse(body); }
    catch (err) { res.statusCode = 400; res.end(`invalid JSON: ${err}`); return; }
  }
  await fsp.mkdir(path.dirname(r.abs), { recursive: true });
  const tmp = `${r.abs}.${process.pid}.tmp`;
  await fsp.writeFile(tmp, body, "utf-8");
  await fsp.rename(tmp, r.abs);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ ok: true, pak: r.pak, path: r.relPath, bytes: body.length }));
  console.log(`[bulanci-data-source] pak file written ${r.pak}/${r.relPath} (${body.length} bytes)`);
}

// ---------------------------------------------------------------------
// pak persistence (write-through into the active mod pak folder)
// ---------------------------------------------------------------------

interface PakEntry { id: string; kind: string; path?: string; file?: string; enabled: boolean }

/** Read the load-order profile + per-pak manifests, write live pushes
 *  through to the active mod pak folder, and seed the broker snapshot
 *  from already-persisted overrides. The native client watches the same
 *  folders, so one push persists *and* hot-reloads both targets. */
class PakStore {
  activeId: string;
  private queue: Promise<void> = Promise.resolve();

  constructor() {
    const paks = this.listPaks();
    const mods = paks.filter(p => p.kind === "mod" && p.enabled);
    // Default write-target: the highest-priority mod (last in load order),
    // falling back to the conventional dev pak.
    this.activeId = mods.length ? mods[mods.length - 1].id : "dev_overrides";
  }

  listPaks(): PakEntry[] {
    try {
      const raw = fs.readFileSync(path.join(paksDir, "profile.json"), "utf-8");
      const prof = JSON.parse(raw) as { paks?: Partial<PakEntry>[] };
      return (prof.paks ?? []).map(p => ({
        id: p.id ?? "",
        kind: p.kind ?? "mod",
        path: p.path,
        file: p.file,
        enabled: p.enabled ?? true,
      }));
    } catch {
      return [];
    }
  }

  setActive(id: string): boolean {
    const ok = this.listPaks().some(p => p.id === id && p.kind === "mod");
    if (ok) this.activeId = id;
    return ok;
  }

  private dirFor(id: string): string | null {
    const e = this.listPaks().find(p => p.id === id && p.kind === "mod" && p.enabled && !p.file);
    if (!e) return null;
    return path.join(paksDir, e.path ?? e.id);
  }

  /** Walk every enabled folder mod pak (low -> high) and load its content
   *  files into `overlays`, recording which hashes are disk-backed. */
  seed(overlays: Map<string, Buffer>, persisted: Set<string>): void {
    for (const p of this.listPaks()) {
      if (p.kind !== "mod" || !p.enabled || p.file) continue;
      const dir = path.join(paksDir, p.path ?? p.id);
      let manifest: any = {};
      try { manifest = JSON.parse(fs.readFileSync(path.join(dir, "pak.json"), "utf-8")); } catch { /* none */ }
      const fileToHash = new Map<string, string>();
      for (const [hashHex, a] of Object.entries((manifest.assets ?? {}) as Record<string, { file?: string }>)) {
        if (a.file) fileToHash.set(a.file.replace(/\\/g, "/"), hashHex);
      }
      const walk = (d: string): void => {
        let ents: fs.Dirent[] = [];
        try { ents = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
        for (const ent of ents) {
          const abs = path.join(d, ent.name);
          if (ent.isDirectory()) { walk(abs); continue; }
          const rel = path.relative(dir, abs).replace(/\\/g, "/");
          if (rel === "pak.json" || rel.endsWith(".schema.json")) continue;
          const stem = ent.name.replace(/\.[^.]*$/, "");
          let hash = fileToHash.get(rel);
          if (!hash && /^[0-9a-f]{16}$/i.test(stem)) hash = stem.toLowerCase();
          if (!hash) continue; // path-keyed (scenes/levels) — engine reads those itself
          try {
            overlays.set(hash, fs.readFileSync(abs));
            persisted.add(hash);
          } catch { /* skip */ }
        }
      };
      walk(dir);
    }
  }

  private serialize<T>(fn: () => Promise<T>): Promise<T> {
    const run = this.queue.then(fn, fn);
    this.queue = run.then(() => undefined, () => undefined);
    return run;
  }

  /** Persist a pushed override: write `<hash><ext>` into the active pak
   *  and record/update its `pak.json` entry. Returns false if there is no
   *  writable active pak folder. */
  async write(hashHex: string, buf: Buffer, meta: { ext?: string; slug?: string; folder?: string; className?: string }): Promise<boolean> {
    const dir = this.dirFor(this.activeId);
    if (!dir) return false;
    let ext = (meta.ext ?? "").trim().toLowerCase();
    if (ext && !ext.startsWith(".")) ext = "." + ext;
    if (!ext) ext = ".bin";
    const file = `${hashHex}${ext}`;
    return this.serialize(async () => {
      await fsp.mkdir(dir, { recursive: true });
      // Drop any stale same-hash file with a different extension.
      try {
        for (const n of await fsp.readdir(dir)) {
          if (n.startsWith(hashHex + ".") && n !== file) await fsp.rm(path.join(dir, n));
        }
      } catch { /* ignore */ }
      const tmp = path.join(dir, `${file}.${process.pid}.tmp`);
      await fsp.writeFile(tmp, buf);
      await fsp.rename(tmp, path.join(dir, file));
      await this.patchManifest(dir, (m) => {
        m.assets ??= {};
        m.assets[hashHex] = {
          ...(meta.folder ? { folder: meta.folder } : {}),
          ...(meta.slug ? { slug: meta.slug } : {}),
          ...(meta.className ? { class: meta.className } : {}),
          file,
          overrides: true,
        };
      });
      console.log(`[mod-broker] persisted ${hashHex} -> ${this.activeId}/${file} (${buf.length} bytes)`);
      return true;
    });
  }

  async remove(hashHex: string): Promise<void> {
    const dir = this.dirFor(this.activeId);
    if (!dir) return;
    await this.serialize(async () => {
      try {
        for (const n of await fsp.readdir(dir)) {
          if (n.startsWith(hashHex + ".") || n === hashHex) await fsp.rm(path.join(dir, n));
        }
      } catch { /* ignore */ }
      await this.patchManifest(dir, (m) => { if (m.assets) delete m.assets[hashHex]; });
    });
  }

  private async patchManifest(dir: string, mutate: (m: any) => void): Promise<void> {
    const p = path.join(dir, "pak.json");
    let m: any = {};
    try { m = JSON.parse(await fsp.readFile(p, "utf-8")); } catch { m = {}; }
    if (!m.schema) m.schema = 1;
    if (!m.id) m.id = path.basename(dir);
    if (!m.kind) m.kind = "mod";
    mutate(m);
    const tmp = `${p}.${process.pid}.tmp`;
    await fsp.writeFile(tmp, JSON.stringify(m, null, 2) + "\n", "utf-8");
    await fsp.rename(tmp, p);
  }
}

// ---------------------------------------------------------------------
// Embedded live-engine (wasm) — auto-build + serve under `/play/`
// ---------------------------------------------------------------------

/** Roots whose changes invalidate the wasm engine and trigger a rebuild.
 *  Only Rust + build inputs matter — pak/Luau/asset edits hot-reload over the
 *  broker WS without recompiling, so they are deliberately excluded. */
const WEB_ENGINE_WATCH_DIRS = [
  path.resolve(obRoot, "client/src"),
  path.resolve(obRoot, "core/src"),
];
const WEB_ENGINE_WATCH_FILES = [
  path.resolve(obRoot, "client/Cargo.toml"),
  path.resolve(obRoot, "core/Cargo.toml"),
  path.resolve(obRoot, "Cargo.toml"),
  path.resolve(obRoot, "Cargo.lock"),
  path.resolve(obRoot, ".cargo/config.toml"),
  path.resolve(obRoot, "core/build.rs"),
  path.resolve(obRoot, "client/build.rs"),
];

/** A path that, when changed, should rebuild the wasm engine. */
function isEngineSource(p: string): boolean {
  const norm = path.resolve(p);
  if (WEB_ENGINE_WATCH_FILES.includes(norm)) return true;
  if (!WEB_ENGINE_WATCH_DIRS.some((d) => norm === d || norm.startsWith(d + path.sep))) return false;
  return norm.endsWith(".rs");
}

/** Newest mtime (ms) across the watched source, or 0 if none exist. Used to
 *  decide on startup whether the deployed artifact is stale. */
function engineSourceNewestMtime(): number {
  let newest = 0;
  const stat = (p: string) => { try { const s = fs.statSync(p); if (s.mtimeMs > newest) newest = s.mtimeMs; } catch { /* missing */ } };
  for (const f of WEB_ENGINE_WATCH_FILES) stat(f);
  const walk = (dir: string) => {
    let ents: fs.Dirent[] = [];
    try { ents = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
    for (const e of ents) {
      const abs = path.join(dir, e.name);
      if (e.isDirectory()) { walk(abs); continue; }
      if (e.name.endsWith(".rs")) stat(abs);
    }
  };
  for (const d of WEB_ENGINE_WATCH_DIRS) walk(d);
  return newest;
}

interface EngineBuildState {
  /** A deployed wasm artifact exists (regardless of freshness). */
  built: boolean;
  /** Lifecycle: never built / compiling / deployed / failed / autobuild off. */
  status: "idle" | "building" | "ready" | "error" | "disabled";
  /** Bumped on every successful (re)build — the panel reloads the iframe when
   *  it increases, so a Rust edit shows up without a manual refresh. */
  generation: number;
  /** Wall-clock duration of the last build (ms). */
  durationMs: number;
  /** Tail of the last build's combined stdout/stderr (for the panel + errors). */
  log: string[];
  /** Auto-build (build on demand + rebuild on Rust change) is enabled. */
  enabled: boolean;
  profile: "debug" | "release";
}

/** Serves the wasm web build under `/play/` AND owns its build lifecycle so the
 *  dev loop is just "run the editor": on startup it builds the engine if the
 *  deployed artifact is missing or older than the Rust source, and it watches
 *  `client/src` + `core/src` (+ manifests) to rebuild + redeploy on any Rust
 *  change. Builds run detached (never blocking the dev server); the panel polls
 *  `GET /play/__status` for progress and reloads the iframe when `generation`
 *  bumps. `POST /play/__build` forces a rebuild.
 *
 *  Disable the auto-build with `BULANCI_WEB_AUTOBUILD=0` (e.g. no emsdk); the
 *  panel then just serves whatever is already deployed. `BULANCI_WEB_PROFILE`
 *  (`release` default, or `debug` for faster relinks) picks the cargo profile. */
function bulanciWebEngine(): Plugin {
  const enabled = process.env.BULANCI_WEB_AUTOBUILD !== "0";
  const profile = process.env.BULANCI_WEB_PROFILE === "debug" ? "debug" : "release";
  const LOG_TAIL = 240;

  const state: EngineBuildState = {
    built: false,
    status: enabled ? "idle" : "disabled",
    generation: 0,
    durationMs: 0,
    log: [],
    enabled,
    profile,
  };
  try { state.built = fs.statSync(webWasmFile).isFile(); } catch { /* not built */ }
  // Seed generation so an already-deployed artifact loads immediately.
  if (state.built) { state.status = enabled ? "ready" : "disabled"; state.generation = 1; }

  let building = false;
  let pending = false;
  let proc: ChildProcess | null = null;

  const pushLog = (line: string) => {
    for (const l of line.split(/\r?\n/)) {
      if (l.length) {
        state.log.push(l);
        console.log(`[web-engine] ${l}`);
      }
    }
    if (state.log.length > LOG_TAIL) state.log.splice(0, state.log.length - LOG_TAIL);
  };

  const startBuild = (reason: string) => {
    if (!enabled) return;
    if (building) { pending = true; return; }
    building = true;
    pending = false;
    state.status = "building";
    state.log = [];
    const startedAt = Date.now();
    pushLog(`building wasm engine (${profile}) — ${reason}`);

    const scriptPath = path.resolve(obRoot, "scripts/build-web.ps1");
    // Windows-first (the engine's C toolchain is set up by dev-shell.ps1 via
    // vcvars/emsdk). pwsh on other platforms is best-effort.
    const isWin = process.platform === "win32";
    const cmd  = isWin ? "powershell" : "pwsh";
    const args = ["-NoProfile", "-ExecutionPolicy", "Bypass", "-File", scriptPath, "-Profile", profile];

    try {
      proc = spawn(cmd, args, { cwd: obRoot, windowsHide: true });
    } catch (err) {
      building = false;
      state.status = "error";
      pushLog(`failed to spawn build: ${err}`);
      return;
    }
    proc.stdout?.on("data", (d: Buffer) => pushLog(d.toString()));
    proc.stderr?.on("data", (d: Buffer) => pushLog(d.toString()));
    proc.on("error", (err) => { pushLog(`build process error: ${err.message}`); });
    proc.on("close", (code) => {
      proc = null;
      building = false;
      state.durationMs = Date.now() - startedAt;
      try { state.built = fs.statSync(webWasmFile).isFile(); } catch { state.built = false; }
      if (code === 0 && state.built) {
        state.status = "ready";
        state.generation += 1;
        pushLog(`done in ${(state.durationMs / 1000).toFixed(1)}s → generation ${state.generation}`);
      } else {
        state.status = "error";
        pushLog(`build failed (exit ${code})`);
      }
      if (pending) startBuild("coalesced change");
    });
  };

  return {
    name: "bulanci-web-engine",
    configureServer(server) {
      // Build on startup if the deployed artifact is missing or stale.
      if (enabled) {
        const artifactMtime = state.built ? (() => { try { return fs.statSync(webWasmFile).mtimeMs; } catch { return 0; } })() : 0;
        const stale = !state.built || engineSourceNewestMtime() > artifactMtime;
        if (stale) startBuild(state.built ? "source changed since last deploy" : "no deployed artifact");
        else pushLog("deployed wasm engine is up to date");

        // Watch the Rust source for changes → debounced rebuild. The dirs live
        // outside the Vite root, so add them to the watcher explicitly; they're
        // never imported, so this only drives our cargo build (no Vite HMR).
        try { server.watcher.add([...WEB_ENGINE_WATCH_DIRS, ...WEB_ENGINE_WATCH_FILES]); } catch { /* best effort */ }
        let debounce: ReturnType<typeof setTimeout> | null = null;
        const onChange = (p: string) => {
          if (!isEngineSource(p)) return;
          if (debounce) clearTimeout(debounce);
          debounce = setTimeout(() => { debounce = null; startBuild(`changed ${path.basename(p)}`); }, 400);
        };
        server.watcher.on("change", onChange);
        server.watcher.on("add", onChange);
        server.watcher.on("unlink", onChange);
      }

      server.middlewares.use(async (req, res, next) => {
        const url = req.url ?? "";
        if (url !== "/play" && !url.startsWith("/play/") && !url.startsWith("/play?")) {
          return next();
        }
        const method = req.method ?? "GET";
        let rel = url.slice("/play".length).split("?")[0];
        rel = decodeURIComponent(rel).replace(/^\/+/, "");
        if (rel === "") rel = "index.html";

        // Build status (polled by the Live panel) + force-rebuild control.
        if (rel === "__status") {
          res.statusCode = 200;
          res.setHeader("Content-Type", "application/json");
          res.setHeader("Cache-Control", "no-store");
          res.end(JSON.stringify(state));
          return;
        }
        if (rel === "__build") {
          if (method !== "POST") { res.statusCode = 405; res.end("use POST"); return; }
          startBuild("manual rebuild");
          res.statusCode = enabled ? 202 : 409;
          res.setHeader("Content-Type", "application/json");
          res.end(JSON.stringify({ ok: enabled, status: state.status, enabled }));
          return;
        }

        const abs = path.resolve(webGameDir, rel);
        if (abs !== webGameDir && !abs.startsWith(webGameDir + path.sep)) {
          res.statusCode = 403; res.end("forbidden"); return;
        }
        try {
          const stat = await fsp.stat(abs);
          if (!stat.isFile()) { res.statusCode = 404; res.end("not a file"); return; }
          res.statusCode = 200;
          res.setHeader("Content-Type",   MIMES[path.extname(abs).toLowerCase()] || "application/octet-stream");
          res.setHeader("Content-Length", stat.size);
          res.setHeader("Cache-Control",  "no-store");
          createReadStream(abs).pipe(res);
        } catch (err) {
          if ((err as NodeJS.ErrnoException).code === "ENOENT") { res.statusCode = 404; res.end("not built yet"); }
          else { console.error("[bulanci-web-engine]", url, err); res.statusCode = 500; res.end("web-engine error"); }
        }
      });
    },
  };
}

/** Dev-only live-mod broker. Bridges the asset studio's HTTP overlay
 *  pushes to the running web game (served separately on :8765) over a
 *  WebSocket, so two browser tabs can mod the game live.
 *
 *  The editor PUTs bytes to `/__engine/overlay/hash/<hex>` — the exact
 *  dialect the native bridge (`client/src/asset/bridge.rs`) speaks, so
 *  `EngineBridge` just points its base URL here. We keep the current
 *  overlay set in memory and fan every change out to game tabs connected
 *  on `/__engine/subscribe`, replaying a full snapshot the instant a tab
 *  connects so a game opened *after* edits still catches up.
 *
 *  Pushes also **write through** to the active mod pak folder (see
 *  `PakStore`), so an edit survives a restart and the native client's
 *  disk watcher mounts the same bytes — one push, both targets, persisted.
 *
 *  Binary frame (matches the parser in web/index.html):
 *    install: [op=1:u8][hash:16 ascii][len:u32le][payload]
 *    clear:   [op=2:u8][hash:16 ascii]
 */
function bulanciModBroker(): Plugin {
  const overlays = new Map<string, Buffer>();
  const persisted = new Set<string>();
  const store = new PakStore();
  store.seed(overlays, persisted);
  if (overlays.size) console.log(`[mod-broker] seeded ${overlays.size} persisted override(s) from paks/`);
  const wss = new WebSocketServer({ noServer: true });

  const encodeInstall = (hashHex: string, payload: Buffer): Buffer => {
    const head = Buffer.alloc(21);
    head.writeUInt8(1, 0);
    head.write(hashHex, 1, "ascii");
    head.writeUInt32LE(payload.length, 17);
    return Buffer.concat([head, payload]);
  };
  const encodeClear = (hashHex: string): Buffer => {
    const head = Buffer.alloc(17);
    head.writeUInt8(2, 0);
    head.write(hashHex, 1, "ascii");
    return head;
  };
  // Scene-HMR patch frame: [op=3:u8][len:u32le][utf8 ScenePatch json].
  // Transient (never persisted, never replayed on connect) — a tab that
  // joins mid-session catches up via the next full doc overlay push.
  const encodeScenePatch = (jsonText: string): Buffer => {
    const payload = Buffer.from(jsonText, "utf-8");
    const head = Buffer.alloc(5);
    head.writeUInt8(3, 0);
    head.writeUInt32LE(payload.length, 1);
    return Buffer.concat([head, payload]);
  };
  const broadcast = (frame: Buffer): void => {
    for (const client of wss.clients) {
      if (client.readyState === 1 /* OPEN */) client.send(frame);
    }
  };
  // Accept 1..16 hex digits and zero-pad to the engine's 16-char form.
  const normHash = (raw: string): string | null => {
    const h = raw.trim().toLowerCase();
    return /^[0-9a-f]{1,16}$/.test(h) ? h.padStart(16, "0") : null;
  };

  wss.on("connection", (ws) => {
    // Replay the full current overlay set (persisted + transient, incl. the
    // latest full scene-doc) so a game that connects/reconnects *after* edits
    // catches up to the editor's live state instead of its stale disk paks.
    for (const [hashHex, buf] of overlays) ws.send(encodeInstall(hashHex, buf));
    console.log(`[mod-broker] client connected -> replayed ${overlays.size} overlay(s), ${wss.clients.size} client(s) now`);
  });

  return {
    name: "bulanci-mod-broker",
    configureServer(server) {
      // Claim only our path on upgrade; everything else (Vite HMR) is left
      // for Vite's own listener.
      server.httpServer?.on("upgrade", (req, socket, head) => {
        let pathname = "";
        try { pathname = new URL(req.url ?? "", "http://localhost").pathname; } catch { /* ignore */ }
        if (pathname !== "/__engine/subscribe") return;
        wss.handleUpgrade(req, socket, head, (ws) => wss.emit("connection", ws, req));
      });

      server.middlewares.use(async (req, res, next) => {
        const url = req.url ?? "";
        if (!url.startsWith("/__engine/")) return next();
        const method = req.method ?? "GET";
        const path = url.split("?")[0];

        res.setHeader("Access-Control-Allow-Origin", "*");
        res.setHeader("Access-Control-Allow-Methods", "GET, PUT, POST, DELETE, OPTIONS");
        res.setHeader("Access-Control-Allow-Headers", "Content-Type");
        if (method === "OPTIONS") { res.statusCode = 204; res.end(); return; }

        const json = (code: number, obj: unknown): void => {
          res.statusCode = code;
          res.setHeader("Content-Type", "application/json");
          res.setHeader("Cache-Control", "no-store");
          res.end(JSON.stringify(obj));
        };

        if (method === "GET" && path === "/__engine/health") {
          return json(200, {
            ok: true, packed: 0, overlays: overlays.size, clients: wss.clients.size,
            target: store.activeId, persisted: persisted.size,
          });
        }
        if (method === "GET" && path === "/__engine/overlays") {
          return json(200, {
            overlays: [...overlays.keys()],
            persisted: [...persisted],
            target: store.activeId,
            paks: store.listPaks().filter(p => p.kind === "mod").map(p => ({ id: p.id, kind: p.kind })),
          });
        }
        // List paks + the active write-target.
        if (method === "GET" && path === "/__engine/paks") {
          return json(200, { target: store.activeId, paks: store.listPaks() });
        }
        // Choose the active write-target pak (must be a folder mod pak).
        if (method === "PUT" && path === "/__engine/target") {
          const chunks: Buffer[] = [];
          for await (const chunk of req) chunks.push(chunk as Buffer);
          let id = "";
          try { id = (JSON.parse(Buffer.concat(chunks).toString("utf-8")) as { id?: string }).id ?? ""; } catch { /* ignore */ }
          if (!store.setActive(id)) return json(400, { error: `unknown mod pak '${id}'` });
          console.log(`[mod-broker] active write-target -> ${id}`);
          return json(200, { ok: true, target: store.activeId });
        }
        // Scene HMR: fan a declarative-doc patch out to every connected game
        // tab as an `op=3` frame. Transient — never persisted (Live = patch
        // only; explicit Save writes the pak via the overlay path).
        if (method === "POST" && path === "/__engine/scene/patch") {
          const chunks: Buffer[] = [];
          let total = 0;
          const MAX = 8 * 1024 * 1024;
          for await (const chunk of req) {
            chunks.push(chunk as Buffer);
            total += (chunk as Buffer).length;
            if (total > MAX) return json(413, { error: "scene patch too large" });
          }
          const body = Buffer.concat(chunks).toString("utf-8");
          try { JSON.parse(body); }
          catch (err) { return json(400, { error: `invalid scene patch JSON: ${err}` }); }
          broadcast(encodeScenePatch(body));
          console.log(`[mod-broker] scene patch (${body.length} bytes) -> ${wss.clients.size} client(s)`);
          return json(200, { ok: true, bytes: body.length, clients: wss.clients.size });
        }

        const prefix = "/__engine/overlay/hash/";
        if (path.startsWith(prefix)) {
          const hashHex = normHash(decodeURIComponent(path.slice(prefix.length)));
          if (!hashHex) return json(400, { error: "hash must be 1-16 hex digits" });

          if (method === "PUT" || method === "POST") {
            const chunks: Buffer[] = [];
            let total = 0;
            const MAX = 32 * 1024 * 1024;
            for await (const chunk of req) {
              chunks.push(chunk as Buffer);
              total += (chunk as Buffer).length;
              if (total > MAX) return json(413, { error: "overlay too large" });
            }
            const buf = Buffer.concat(chunks);
            const hdr = (n: string) => {
              const v = req.headers[n.toLowerCase()];
              return Array.isArray(v) ? v[0] : v;
            };
            // Cache-only push: refresh the stored snapshot (so a game that
            // (re)connects later replays the CURRENT doc) but DON'T broadcast —
            // already-attached games keep their live-patched state instead of
            // rebuilding. This is what makes live editing smooth: the editor
            // re-syncs the full doc on idle to keep reconnects fresh, without
            // ever disrupting the game you're editing against. Implies
            // transient (never persisted to a pak).
            const cacheOnly = hdr("x-asset-cache-only") === "1";
            overlays.set(hashHex, buf);
            if (!cacheOnly) broadcast(encodeInstall(hashHex, buf));
            // Persist into the active mod pak unless the editor asks for a
            // transient / cache-only push.
            let persistedNow = false;
            if (!cacheOnly && hdr("x-asset-transient") !== "1") {
              persistedNow = await store.write(hashHex, buf, {
                ext: hdr("x-asset-ext"),
                slug: hdr("x-asset-slug"),
                folder: hdr("x-asset-folder"),
                className: hdr("x-asset-class"),
              });
              if (persistedNow) persisted.add(hashHex);
            }
            if (cacheOnly) {
              console.log(`[mod-broker] snapshot ${hashHex} (${buf.length} bytes) -> cached (${wss.clients.size} client(s) undisturbed)`);
            } else {
              console.log(`[mod-broker] install ${hashHex} (${buf.length} bytes)${persistedNow ? " +persist" : ""} -> ${wss.clients.size} client(s)`);
            }
            return json(200, { ok: true, hash: hashHex, bytes: buf.length, persisted: persistedNow, cached: cacheOnly, target: store.activeId });
          }
          if (method === "DELETE") {
            overlays.delete(hashHex);
            broadcast(encodeClear(hashHex));
            if (persisted.has(hashHex)) { await store.remove(hashHex); persisted.delete(hashHex); }
            console.log(`[mod-broker] clear ${hashHex} -> ${wss.clients.size} client(s)`);
            return json(200, { ok: true, hash: hashHex });
          }
          return json(405, { error: "use PUT, POST or DELETE" });
        }

        return json(404, { error: "not found" });
      });
    },
  };
}

// ---------------------------------------------------------------------
// Luau LSP proxy (Monaco <-> luau-lsp over a WebSocket)
// ---------------------------------------------------------------------

/** Bridges a browser WebSocket at `/__lsp` to a `luau-lsp lsp` child
 *  process over stdio (the jsonrpc-ws-proxy pattern). The server is
 *  spawned in the paks dir so its `.luaurc` alias map (`@bulanci`, the
 *  lib aliases) resolves `require`s exactly as the engine does. The
 *  Scripts panel connects here for completion/hover/diagnostics; if the
 *  `luau-lsp` binary isn't installed the editor still works, just
 *  without language intelligence (`/__lsp/info` reports availability). */
function bulanciLuauLsp(): Plugin {
  // Probe once: is the binary on PATH? (cheap `--version`).
  let available = false;
  try {
    const r = spawnSync("luau-lsp", ["--version"], { encoding: "utf-8" });
    available = r.status === 0;
  } catch { available = false; }
  if (!available) {
    console.log("[luau-lsp] binary not found on PATH — Scripts panel runs without LSP (install JohnnyMorganz/luau-lsp to enable)");
  }

  const wss = new WebSocketServer({ noServer: true });

  return {
    name: "bulanci-luau-lsp",
    configureServer(server) {
      server.httpServer?.on("upgrade", (req, socket, head) => {
        let pathname = "";
        try { pathname = new URL(req.url ?? "", "http://localhost").pathname; } catch { /* ignore */ }
        if (pathname !== "/__lsp") return;
        if (!available) { socket.destroy(); return; }
        wss.handleUpgrade(req, socket, head, (ws) => {
          // Bridge the socket to a fresh luau-lsp process. One server per
          // connection keeps document state isolated and lets a crashed
          // server be recovered by reconnecting.
          const wsSocket = toSocket(ws as unknown as WebSocket);
          const connection = createWebSocketConnection(wsSocket);
          let serverProc: ReturnType<typeof createServerProcess> | undefined;
          try {
            serverProc = createServerProcess("luau", "luau-lsp", ["lsp"], { cwd: paksDir });
          } catch (e) {
            console.error("[luau-lsp] spawn failed:", e);
          }
          if (serverProc) {
            forward(connection, serverProc, (message) => message);
            console.log("[luau-lsp] client connected -> spawned luau-lsp lsp");
          } else {
            wsSocket.dispose();
            try { ws.close(); } catch { /* ignore */ }
          }
        });
      });

      server.middlewares.use((req, res, next) => {
        if ((req.url ?? "").split("?")[0] !== "/__lsp/info") return next();
        res.statusCode = 200;
        res.setHeader("Content-Type", "application/json");
        res.setHeader("Cache-Control", "no-store");
        // `root` lets the client mint `file://` URIs the server resolves
        // .luaurc against; `alias` documents the require root.
        res.end(JSON.stringify({ available, root: paksDir, alias: { bulanci: "@bulanci" } }));
      });
    },
  };
}

// `bun run dev` mounts the data plugin so the gallery sees the live
// repo with no Python.  Production builds drop the plugin (the build
// step in `serve.py` / a CI step copies `data/` into `dist/data/`).
export default defineConfig({
  fmt: {},
  plugins: [react(), tailwindcss(), bulanciDataSource(), bulanciWebEngine(), bulanciModBroker(), bulanciLuauLsp()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  server: {
    port: 5173,
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
});
