--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x0000

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("CA434A51-9B74-417C-88B1-2FC1A1643011"))
    engine.set_global(0, engine.str_const("Autobusy"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(0, 0, 800, 14))
    engine.insert_view(engine.create_obstacle(569, 391, 785, 410))
    engine.insert_view(engine.create_obstacle(372, 391, 462, 410))
    engine.insert_view(engine.create_obstacle(353, 301, 372, 409))
    engine.insert_view(engine.create_obstacle(785, 337, 800, 499))
    engine.insert_view(engine.create_obstacle(785, 14, 800, 212))
    engine.insert_view(engine.create_obstacle(12, 499, 800, 515))
    engine.insert_view(engine.create_obstacle(0, 14, 12, 515))
    engine.insert_view(engine.create_obstacle(262, 279, 304, 298))
    engine.insert_view(engine.create_obstacle(231, 293, 259, 303))
    engine.insert_view(engine.create_obstacle(40, 336, 71, 343))
    engine.insert_view(engine.create_obstacle(195, 303, 269, 311))
    engine.insert_view(engine.create_obstacle(160, 311, 241, 319))
    engine.insert_view(engine.create_obstacle(126, 319, 201, 330))
    engine.insert_view(engine.create_obstacle(93, 329, 163, 341))
    engine.insert_view(engine.create_obstacle(19, 341, 141, 356))
    engine.insert_view(engine.create_obstacle(50, 356, 88, 364))
    engine.insert_view(engine.create_obstacle(483, 118, 547, 128))
    engine.insert_view(engine.create_obstacle(491, 126, 575, 131))
    engine.insert_view(engine.create_obstacle(516, 133, 597, 136))
    engine.insert_view(engine.create_obstacle(538, 137, 623, 143))
    engine.insert_view(engine.create_obstacle(560, 144, 644, 150))
    engine.insert_view(engine.create_obstacle(584, 151, 677, 159))
    engine.insert_view(engine.create_obstacle(656, 168, 703, 176))
    engine.insert_view(engine.create_obstacle(620, 160, 733, 168))
    engine.insert_view(engine.create_obstacle(266, 123, 410, 127))
    engine.insert_view(engine.create_obstacle(96, 142, 173, 145))
    engine.insert_view(engine.create_obstacle(95, 135, 246, 142))
    engine.insert_view(engine.create_obstacle(93, 127, 411, 135))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(13, 206, 100006))
    engine.insert_view(engine.create_image(478, 46, 100005))
    engine.insert_view(engine.create_image(92, 39, 100004))
    engine.set_insert_mode(1)
    engine.set_insert_mode(0)
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 701, 420, 781, 490, 14)
        engine.define_trace_area(1, 17, 23, 97, 93, 14)
    end
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x0000(entitySlot, 31, 39)
    elseif _sw == 1 then
        fn_0x0000(entitySlot, 715, 436)
    else
        fn_0x0000(entitySlot, 31, 39)
    end
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
    elseif _sw == 1 then
    end
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local v0, v1, v2, v3 = 0, 0, 0, 0
    v0 = engine.strm_read(streamHandle, 1)
    if v0 == 1 then
        v3 = engine.strm_read(streamHandle, 1)
        v1 = engine.strm_read(streamHandle, 4)
        v2 = engine.strm_read(streamHandle, 4)
        engine.teleport_player_to(v3, v1, v2, 1)
    end
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
function fn_0x0000(p0, p1, p2)
    if engine.teleport_player_to(p0, p1, p2, 0) == 0 then
        return 0
    end
    if engine.is_net() ~= 0 then
        engine.strm_set_size(engine.get_global(3), 0)
        engine.strm_write(engine.get_global(3), 1, 1)
        engine.strm_write(engine.get_global(3), p0, 1)
        engine.strm_write(engine.get_global(3), p1, 4)
        engine.strm_write(engine.get_global(3), p2, 4)
        engine.strm_send(engine.get_global(3))
    end
    return 1
end

