--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 30, engine.str_const("1981-1983"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 30, engine.str_const("Rozvoj bulánčí poezie a prózy."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 50, engine.str_const("1982-1985"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 50, engine.str_const("Hospodářská krize. Začíná se projevovat nedostatek základních potravin a léků.\nVelkou ranou pro bulánčí rasu je rovněž epidemie husího moru."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 83, engine.str_const("12. 7. 1986"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 83, engine.str_const("Zavraždění prezidenta. V noci z 11. na 12.\nčervence je zavražděn umírněný vůdce Bulánků\nŽezlík. Vlády se pokouší zmocnit fanatický\ngenerál Pfühl, jež hlásá nadřazenost rasy s\nbílým draným peřím."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 158, engine.str_const("18. 7. 1986"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 158, engine.str_const("Druhá polštářová válka. Rozpoutává se druhá,\nmnohem krutější a zákeřnější válka. Válka mezi\nBulánky samotnými. Na všech frontách dochází k\nvelkým ztrátám, které plodí stále větší nenávist,\nroztáčející nekonečnou spirálu krvelačné pomsty.\nHeslo \"Oko za oko\" zasadilo tehdy kořeny tomu,\nže se bulánčí rody dodnes neusmířily."), 1, 65711))
    engine.hh_add_child(engine.hcreate_movie(30, 266, 65652, 77826, 77827))
    engine.hh_add_child(engine.hcreate_movie(350, 90, 65605, 77824, 77825))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(206, 276, engine.str_const("24. 8. 1988"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(276, 276, engine.str_const("Olympijské hry. Bulánek Mazlík získává zlatou\nmedaili v letních olympijských hrách za střelbu\nna pohyblivý cíl. Na nějakou dobu tato událost\nsjednocuje znesvářené rody."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(206, 335, engine.str_const("20. 3. 1992"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(276, 335, engine.str_const("První transfuze. Bulánkovi Kapslíkovi je\nprovedena první úspěšná transfuze peří."), 1, 65711))
    return 0
end

