--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("8DCFCC56-35BC-4141-82F9-B46CB402D7C8"))
    engine.set_global(0, engine.str_const("Srdeční záležitost"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(749, 443, 799, 468))
    engine.insert_view(engine.create_obstacle(0, 205, 64, 220))
    engine.insert_view(engine.create_obstacle(64, 22, 103, 56))
    engine.insert_view(engine.create_obstacle(100, 472, 188, 515))
    engine.insert_view(engine.create_obstacle(375, 469, 469, 515))
    engine.insert_view(engine.create_obstacle(549, 467, 635, 515))
    engine.insert_view(engine.create_obstacle(708, 39, 722, 68))
    engine.insert_view(engine.create_obstacle(720, 0, 800, 70))
    engine.insert_view(engine.create_obstacle(437, 34, 526, 68))
    engine.insert_view(engine.create_obstacle(451, 0, 518, 33))
    engine.insert_view(engine.create_obstacle(620, 0, 646, 186))
    engine.insert_view(engine.create_obstacle(630, 204, 727, 227))
    engine.insert_view(engine.create_obstacle(548, 181, 646, 205))
    engine.insert_view(engine.create_obstacle(707, 318, 800, 384))
    engine.insert_view(engine.create_obstacle(542, 320, 635, 342))
    engine.insert_view(engine.create_obstacle(451, 277, 544, 343))
    engine.insert_view(engine.create_obstacle(352, 293, 460, 315))
    engine.insert_view(engine.create_obstacle(351, 291, 377, 515))
    engine.insert_view(engine.create_obstacle(181, 291, 280, 315))
    engine.insert_view(engine.create_obstacle(370, 182, 473, 205))
    engine.insert_view(engine.create_obstacle(180, 142, 279, 163))
    engine.insert_view(engine.create_obstacle(254, 62, 278, 164))
    engine.insert_view(engine.create_obstacle(280, 139, 373, 205))
    engine.insert_view(engine.create_obstacle(0, 289, 181, 354))
    engine.insert_view(engine.create_obstacle(0, 139, 180, 205))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(723, 0, 100013))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(746, 425, 100011), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(545, 446, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(436, 0, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(66, 24, 100012), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(97, 446, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(708, 0, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(377, 446, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(645, 183, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(182, 317, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 205, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(629, 203, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(707, 318, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(451, 277, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(537, 320, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(183, 139, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(621, 83, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(254, 60, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(352, 415, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(621, 0, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(352, 315, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(547, 181, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(375, 182, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 84, 100006), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(280, 139, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(351, 291, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(181, 292, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(88, 290, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(88, 139, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 289, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 139, 100004), 0))
    engine.set_insert_mode(0)
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

