--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("6A2B7D86-A2AF-4471-8BF6-F68DF5B2624E"))
    engine.set_global(0, engine.str_const("Pewnost"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(13, 488, 50, 514))
    engine.insert_view(engine.create_obstacle(681, 478, 717, 498))
    engine.insert_view(engine.create_obstacle(685, 350, 800, 359))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(137, 209, 178, 255), 1))
    engine.insert_view(engine.create_obstacle(133, 202, 143, 234))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(258, 58, 279, 80), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(725, 0, 748, 35), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(743, 85, 768, 110), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(738, 59, 762, 89), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(735, 37, 757, 60), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(731, 0, 761, 41), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(763, 129, 798, 168), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(751, 0, 800, 141), 1))
    engine.insert_view(engine.create_obstacle(659, 234, 670, 263))
    engine.insert_view(engine.create_obstacle(658, 214, 668, 242))
    engine.insert_view(engine.create_obstacle(656, 183, 666, 214))
    engine.insert_view(engine.create_obstacle(654, 151, 666, 180))
    engine.insert_view(engine.create_obstacle(636, 261, 669, 271))
    engine.insert_view(engine.create_obstacle(605, 270, 639, 278))
    engine.insert_view(engine.create_obstacle(579, 277, 609, 285))
    engine.insert_view(engine.create_obstacle(551, 284, 580, 294))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(501, 231, 560, 241), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(386, 228, 498, 243), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(304, 214, 393, 245), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(289, 191, 314, 228), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(277, 157, 319, 198), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(247, 160, 275, 198), 1))
    engine.insert_view(engine.create_obstacle(268, 148, 513, 158))
    engine.insert_view(engine.create_obstacle(357, 147, 661, 157))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(308, 156, 660, 235), 1))
    engine.insert_view(engine.create_obstacle(246, 159, 277, 173))
    engine.insert_view(engine.create_obstacle(666, 372, 677, 385))
    engine.insert_view(engine.create_obstacle(650, 361, 688, 372))
    engine.insert_view(engine.create_obstacle(555, 381, 587, 387))
    engine.insert_view(engine.create_obstacle(586, 373, 621, 380))
    engine.insert_view(engine.create_obstacle(614, 366, 660, 372))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(193, 44, 244, 87), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(3, 78, 140, 119), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(0, 54, 191, 110), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(0, 0, 278, 80), 1))
    engine.insert_view(engine.create_obstacle(281, 0, 294, 11))
    engine.insert_view(engine.create_obstacle(275, 13, 290, 31))
    engine.insert_view(engine.create_obstacle(273, 31, 287, 45))
    engine.insert_view(engine.create_obstacle(268, 46, 282, 71))
    engine.insert_view(engine.create_obstacle(250, 65, 276, 78))
    engine.insert_view(engine.create_obstacle(218, 76, 244, 89))
    engine.insert_view(engine.create_obstacle(195, 86, 219, 97))
    engine.insert_view(engine.create_obstacle(167, 98, 194, 108))
    engine.insert_view(engine.create_obstacle(142, 108, 168, 117))
    engine.insert_view(engine.create_obstacle(49, 119, 83, 131))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(775, 287, 800, 306), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(770, 262, 800, 290), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(766, 248, 793, 266), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(781, 278, 800, 348), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(765, 197, 797, 256), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(763, 170, 800, 222), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(674, 359, 800, 384), 1))
    engine.insert_view(engine.create_obstacle(142, 285, 152, 308))
    engine.insert_view(engine.create_obstacle(138, 259, 151, 287))
    engine.insert_view(engine.create_obstacle(135, 224, 145, 257))
    engine.insert_view(engine.create_obstacle(136, 197, 182, 207))
    engine.insert_view(engine.create_obstacle(160, 188, 194, 198))
    engine.insert_view(engine.create_obstacle(190, 179, 216, 189))
    engine.insert_view(engine.create_obstacle(215, 169, 275, 180))
    engine.insert_view(engine.create_obstacle(17, 292, 36, 308))
    engine.insert_view(engine.create_obstacle(12, 246, 36, 259))
    engine.insert_view(engine.create_obstacle(7, 277, 38, 292))
    engine.insert_view(engine.create_obstacle(16, 308, 42, 324))
    engine.insert_view(engine.create_obstacle(0, 180, 31, 337))
    engine.insert_view(engine.create_obstacle(0, 148, 22, 222))
    engine.insert_view(engine.create_obstacle(23, 129, 47, 153))
    engine.insert_view(engine.create_obstacle(26, 139, 43, 168))
    engine.insert_view(engine.create_obstacle(31, 128, 51, 142))
    engine.insert_view(engine.create_obstacle(11, 185, 33, 206))
    engine.insert_view(engine.create_obstacle(13, 173, 35, 186))
    engine.insert_view(engine.create_obstacle(12, 145, 38, 180))
    engine.insert_view(engine.create_obstacle(0, 119, 37, 166))
    engine.insert_view(engine.create_obstacle(87, 118, 139, 128))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(175, 192, 314, 234), 1))
    engine.set_insert_mode(2)
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 337, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(629, 321, 100004), 0))
    engine.set_insert_mode(0)
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

