--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x0000

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("40DB7B80-6F82-47CA-BC44-081F407013DE"))
    engine.set_global(0, engine.str_const("Ať žijou Bulánci!"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(74, 0, 85, 29))
    engine.insert_view(engine.create_image(7, 46, 100011))
    engine.insert_view(engine.create_image(51, 8, 100011))
    engine.insert_view(engine.create_image(49, 44, 100011))
    engine.insert_view(engine.create_image(4, 8, 100011))
    engine.insert_view(engine.create_image(0, 29, 100011))
    engine.insert_view(engine.create_image(58, 26, 100011))
    engine.insert_view(engine.create_image(28, 51, 100011))
    engine.insert_view(engine.create_image(28, 0, 100011))
    engine.insert_view(engine.create_obstacle(165, 347, 196, 355))
    engine.insert_view(engine.create_obstacle(126, 346, 166, 371))
    engine.insert_view(engine.create_obstacle(66, 485, 104, 515))
    engine.insert_view(engine.create_obstacle(161, 308, 181, 317))
    engine.insert_view(engine.create_obstacle(134, 302, 164, 316))
    engine.insert_view(engine.create_obstacle(106, 299, 137, 316))
    engine.insert_view(engine.create_obstacle(100, 336, 111, 345))
    engine.insert_view(engine.create_obstacle(93, 316, 116, 337))
    engine.insert_view(engine.create_obstacle(110, 315, 201, 349))
    engine.insert_view(engine.create_image(125, 337, 100005))
    engine.insert_view(engine.create_obstacle(680, 174, 715, 198))
    engine.insert_view(engine.create_obstacle(668, 188, 701, 198))
    engine.insert_view(engine.create_obstacle(654, 202, 671, 237))
    engine.insert_view(engine.create_obstacle(720, 230, 738, 267))
    engine.insert_view(engine.create_obstacle(669, 194, 720, 277))
    engine.insert_view(engine.create_obstacle(735, 140, 752, 170))
    engine.insert_view(engine.create_obstacle(736, 129, 769, 143))
    engine.insert_view(engine.create_obstacle(689, 77, 736, 177))
    engine.insert_view(engine.create_obstacle(735, 60, 800, 133))
    engine.insert_view(engine.create_obstacle(359, 273, 376, 289))
    engine.insert_view(engine.create_obstacle(408, 273, 417, 282))
    engine.insert_view(engine.create_obstacle(374, 271, 409, 290))
    engine.insert_view(engine.create_obstacle(397, 210, 413, 223))
    engine.insert_view(engine.create_obstacle(356, 211, 369, 221))
    engine.insert_view(engine.create_obstacle(367, 206, 401, 222))
    engine.insert_view(engine.create_obstacle(323, 225, 342, 230))
    engine.insert_view(engine.create_obstacle(320, 251, 345, 266))
    engine.insert_view(engine.create_obstacle(309, 234, 317, 253))
    engine.insert_view(engine.create_obstacle(316, 230, 341, 258))
    engine.insert_view(engine.create_obstacle(338, 221, 419, 273))
    engine.insert_view(engine.create_obstacle(238, 138, 269, 145))
    engine.insert_view(engine.create_obstacle(221, 163, 229, 170))
    engine.insert_view(engine.create_obstacle(220, 147, 228, 161))
    engine.insert_view(engine.create_obstacle(277, 147, 287, 169))
    engine.insert_view(engine.create_obstacle(228, 143, 279, 180))
    engine.insert_view(engine.create_obstacle(394, 420, 408, 430))
    engine.insert_view(engine.create_obstacle(363, 421, 382, 436))
    engine.insert_view(engine.create_obstacle(457, 368, 470, 384))
    engine.insert_view(engine.create_obstacle(418, 355, 454, 361))
    engine.insert_view(engine.create_obstacle(416, 360, 462, 371))
    engine.insert_view(engine.create_obstacle(408, 370, 460, 392))
    engine.insert_view(engine.create_obstacle(351, 403, 361, 412))
    engine.insert_view(engine.create_obstacle(344, 386, 360, 404))
    engine.insert_view(engine.create_obstacle(359, 378, 408, 425))
    engine.insert_view(engine.create_obstacle(600, 140, 608, 147))
    engine.insert_view(engine.create_obstacle(497, 102, 502, 135))
    engine.insert_view(engine.create_obstacle(600, 104, 609, 114))
    engine.insert_view(engine.create_obstacle(601, 113, 611, 141))
    engine.insert_view(engine.create_obstacle(588, 145, 599, 155))
    engine.insert_view(engine.create_obstacle(537, 154, 580, 164))
    engine.insert_view(engine.create_obstacle(573, 157, 586, 166))
    engine.insert_view(engine.create_obstacle(505, 87, 513, 97))
    engine.insert_view(engine.create_obstacle(542, 161, 575, 171))
    engine.insert_view(engine.create_obstacle(588, 98, 602, 147))
    engine.insert_view(engine.create_obstacle(501, 94, 514, 143))
    engine.insert_view(engine.create_obstacle(513, 85, 591, 159))
    engine.insert_view(engine.create_obstacle(152, 44, 182, 52))
    engine.insert_view(engine.create_obstacle(109, 42, 150, 80))
    engine.insert_view(engine.create_obstacle(81, 0, 191, 46))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(553, 240, 100010))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(108, 45, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(76, 0, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(495, 74, 100006), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(668, 206, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(650, 170, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(730, 69, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(680, 110, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(685, 53, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(730, 33, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(341, 343, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(64, 479, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(132, 294, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(91, 303, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(103, 287, 100005), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(348, 237, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(304, 214, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(348, 194, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(216, 126, 100008), 0))
    engine.set_insert_mode(0)
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 725, 450, 805, 520, 14)
        engine.define_trace_area(1, -5, -5, 75, 65, 14)
    end
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x0000(entitySlot, 9, 11)
    elseif _sw == 1 then
        fn_0x0000(entitySlot, 739, 466)
    else
        fn_0x0000(entitySlot, 9, 11)
    end
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
    elseif _sw == 1 then
    end
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local v0, v1, v2, v3 = 0, 0, 0, 0
    v0 = engine.strm_read(streamHandle, 1)
    if v0 == 1 then
        v3 = engine.strm_read(streamHandle, 1)
        v1 = engine.strm_read(streamHandle, 4)
        v2 = engine.strm_read(streamHandle, 4)
        engine.teleport_player_to(v3, v1, v2, 1)
    end
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
function fn_0x0000(p0, p1, p2)
    if engine.teleport_player_to(p0, p1, p2, 0) == 0 then
        return 0
    end
    if engine.is_net() ~= 0 then
        engine.strm_set_size(engine.get_global(3), 0)
        engine.strm_write(engine.get_global(3), 1, 1)
        engine.strm_write(engine.get_global(3), p0, 1)
        engine.strm_write(engine.get_global(3), p1, 4)
        engine.strm_write(engine.get_global(3), p2, 4)
        engine.strm_send(engine.get_global(3))
    end
    return 1
end

