--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x05b0, fn_0x0000, fn_0x064a, fn_0x06e4

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("311CAC12-DA5E-4275-A8C5-B9EE0815F835"))
    engine.set_global(0, engine.str_const("Western"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(721, 0, 732, 20))
    engine.insert_view(engine.create_obstacle(434, 171, 455, 183))
    engine.insert_view(engine.create_obstacle(460, 170, 478, 193))
    engine.insert_view(engine.create_obstacle(481, 190, 500, 202))
    engine.insert_view(engine.create_obstacle(500, 189, 568, 214))
    engine.insert_view(engine.create_obstacle(480, 163, 617, 189))
    engine.insert_view(engine.create_obstacle(481, 139, 637, 163))
    engine.insert_view(engine.create_obstacle(481, 116, 658, 139))
    engine.insert_view(engine.create_obstacle(481, 91, 674, 116))
    engine.insert_view(engine.create_obstacle(370, 0, 721, 47))
    engine.insert_view(engine.create_obstacle(424, 91, 481, 170))
    engine.insert_view(engine.create_obstacle(315, 149, 356, 159))
    engine.insert_view(engine.create_obstacle(289, 0, 304, 47))
    engine.insert_view(engine.create_obstacle(261, 87, 274, 111))
    engine.insert_view(engine.create_obstacle(253, 112, 275, 134))
    engine.insert_view(engine.create_obstacle(303, 0, 370, 148))
    engine.insert_view(engine.create_obstacle(275, 47, 303, 148))
    engine.insert_view(engine.create_obstacle(482, 463, 503, 473))
    engine.insert_view(engine.create_obstacle(459, 453, 510, 463))
    engine.insert_view(engine.create_obstacle(442, 432, 523, 452))
    engine.insert_view(engine.create_obstacle(456, 412, 541, 431))
    engine.insert_view(engine.create_obstacle(473, 393, 555, 412))
    engine.insert_view(engine.create_obstacle(488, 374, 571, 393))
    engine.insert_view(engine.create_obstacle(502, 354, 587, 373))
    engine.insert_view(engine.create_obstacle(503, 341, 600, 354))
    engine.insert_view(engine.create_obstacle(542, 303, 574, 314))
    engine.insert_view(engine.create_obstacle(527, 292, 541, 316))
    engine.insert_view(engine.create_obstacle(516, 314, 589, 325))
    engine.insert_view(engine.create_obstacle(506, 325, 607, 341))
    engine.insert_view(engine.create_obstacle(269, 263, 321, 273))
    engine.insert_view(engine.create_obstacle(257, 269, 335, 280))
    engine.insert_view(engine.create_obstacle(247, 279, 343, 289))
    engine.insert_view(engine.create_obstacle(262, 322, 321, 329))
    engine.insert_view(engine.create_obstacle(250, 307, 337, 322))
    engine.insert_view(engine.create_obstacle(244, 288, 344, 307))
    engine.insert_view(engine.create_obstacle(152, 191, 188, 218))
    engine.insert_view(engine.create_obstacle(57, 310, 95, 336))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(437, 0, 100012))
    engine.insert_view(engine.create_image(537, 203, 100009))
    engine.insert_view(engine.create_image(0, 348, 100004))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(308, 0, 100011), -18))
    engine.insert_view(engine.set_order_axis(engine.create_image(240, 0, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(433, 241, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(244, 249, 100007), -37))
    engine.insert_view(engine.set_order_axis(engine.create_image(31, 17, 100006), -8))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 105, 100005), -9))
    engine.set_insert_mode(0)
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 8, 9, 88, 79, 14)
        engine.define_trace_area(1, 680, 407, 760, 477, 14)
        engine.define_trace_area(2, 390, 242, 470, 312, 14)
    end
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x05b0(entitySlot)
    elseif _sw == 1 then
        fn_0x064a(entitySlot)
    elseif _sw == 2 then
        fn_0x06e4(entitySlot)
    else
        fn_0x05b0(entitySlot)
    end
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
    elseif _sw == 1 then
    elseif _sw == 2 then
    end
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local v0, v1, v2, v3 = 0, 0, 0, 0
    v0 = engine.strm_read(streamHandle, 1)
    if v0 == 1 then
        v3 = engine.strm_read(streamHandle, 1)
        v1 = engine.strm_read(streamHandle, 4)
        v2 = engine.strm_read(streamHandle, 4)
        engine.teleport_player_to(v3, v1, v2, 1)
    end
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
function fn_0x05b0(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 1)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 694, 423) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 404, 258) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 694, 423) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
function fn_0x0000(p0, p1, p2)
    if engine.teleport_player_to(p0, p1, p2, 0) == 0 then
        return 0
    end
    if engine.is_net() ~= 0 then
        engine.strm_set_size(engine.get_global(3), 0)
        engine.strm_write(engine.get_global(3), 1, 1)
        engine.strm_write(engine.get_global(3), p0, 1)
        engine.strm_write(engine.get_global(3), p1, 4)
        engine.strm_write(engine.get_global(3), p2, 4)
        engine.strm_send(engine.get_global(3))
    end
    return 1
end

-- helper (call-target)
function fn_0x064a(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 1)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 22, 25) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 404, 258) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 22, 25) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
function fn_0x06e4(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 1)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 22, 25) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 694, 423) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 22, 25) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 2 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

