--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 28, engine.str_const("Bulánek"), 2, 65710), 4, {0, 16777215, 14540253, 14540253}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 30, engine.str_const("- vyšší forma života, někdy označována zkratkou E.A.P. (extrémně\n  agresivní polštář) - vybráno z naučného slovníku."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 83, engine.str_const("Důležitá data:"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 123, engine.str_const("10. 8. 1974"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 123, engine.str_const("Statistický průzkum. Na otázku, co je to Bulánek, 87 %\ndotazovaných odpovědělo, že polštář."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 156, engine.str_const("12. 2. 1975"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 156, engine.str_const("Bulánek Uzlík přibíjí svůj protest proti nevolnictví na dveře\nložnice. Tato událost doslova otřásla veřejností i všemi\ndosavadními teoriemi a zároveň dala podnět k pozdější vzpouře\nostatních Bulánků."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 215, engine.str_const("25. 2. 1975"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 215, engine.str_const("Statistický průzkum. Na otázku, co je to Bulánek, 87 %\ndotazovaných odpovědělo, že polštář."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 248, engine.str_const("5. 5. 1975"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 248, engine.str_const("Vzpoura Bulánků (později známá jako Velká květnová revoluce).\nBulánci zpřetrhávají svá \"nevolnická pouta\" a s konečnou\nplatností opouští postele, gauče, palandy, čímž zasazují ránu\nlidské lhostejnosti. V některých ložnicích zůstávají však Bulánci\nz nepochopitelných důvodů dál nehybně ležet.\n\"Pro své mrtvé se vrátíme\" zněla tehdy hesla rozvášněného\nbulánčího davu."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 346, engine.str_const("8. 1. 1977"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 346, engine.str_const("První polštářová válka. Nepokoje v řadách Bulánků ústí v\nprvní ozbrojené konflikty mezi lidmi. Rozpoutává se 1. polštářová\nválka. Armáda Bulánků zahajuje agresivní defensivu na všech\nfrontách a zanechává za sebou jen spálená prostěradla. Nikdo\nnepamatuje větší masakr než k jakému došlo v bitvě u Lupan."), 2, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 418, engine.str_const("1. 1. 1980"), 2, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(110, 418, engine.str_const("Příměří. Na nový rok bylo sjednáno příměří mezi lidmi a\nBulánky. Nepokoje však doznívají ještě dlouho poté."), 2, 65711))
    return 0
end

