--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x0000, fn_0x049c

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("3838938E-851E-4B0F-AF0B-1CB280234F6B"))
    engine.set_global(0, engine.str_const("Tutorial 1"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(737, 366, 787, 383))
    engine.insert_view(engine.create_obstacle(425, 398, 474, 415))
    engine.insert_view(engine.create_obstacle(327, 420, 371, 435))
    engine.insert_view(engine.create_obstacle(321, 137, 367, 150))
    engine.insert_view(engine.create_obstacle(247, 133, 294, 148))
    engine.insert_view(engine.create_obstacle(15, 136, 61, 152))
    engine.insert_view(engine.create_obstacle(127, 307, 175, 333))
    engine.insert_view(engine.create_obstacle(655, 302, 730, 359))
    engine.insert_view(engine.create_obstacle(114, 276, 187, 324))
    engine.insert_view(engine.create_obstacle(0, 92, 77, 143))
    engine.insert_view(engine.create_obstacle(724, 325, 800, 373))
    engine.insert_view(engine.create_obstacle(312, 383, 385, 428))
    engine.insert_view(engine.create_obstacle(413, 363, 489, 407))
    engine.insert_view(engine.create_obstacle(235, 90, 383, 140))
    engine.insert_view(engine.create_obstacle(402, 70, 518, 162))
    engine.insert_view(engine.create_obstacle(516, 310, 632, 399))
    engine.insert_view(engine.create_obstacle(197, 424, 310, 515))
    engine.insert_view(engine.create_image(360, 230, 100006))
    engine.insert_view(engine.create_image(313, 449, 100006))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(671, 0, 100008))
    engine.insert_view(engine.create_image(0, 303, 100007))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(112, 248, 100005), -57))
    engine.insert_view(engine.set_order_axis(engine.create_image(723, 299, 100005), -62))
    engine.insert_view(engine.set_order_axis(engine.create_image(652, 273, 100005), -59))
    engine.insert_view(engine.set_order_axis(engine.create_image(412, 331, 100005), -55))
    engine.insert_view(engine.set_order_axis(engine.create_image(311, 350, 100005), -54))
    engine.insert_view(engine.set_order_axis(engine.create_image(307, 65, 100005), -61))
    engine.insert_view(engine.set_order_axis(engine.create_image(232, 63, 100005), -59))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 67, 100005), -63))
    engine.insert_view(engine.set_order_axis(engine.create_image(194, 395, 100004), -86))
    engine.insert_view(engine.set_order_axis(engine.create_image(514, 282, 100004), -87))
    engine.insert_view(engine.set_order_axis(engine.create_image(400, 44, 100004), -90))
    engine.set_insert_mode(0)
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 312, 444, 392, 514, 14)
        engine.define_trace_area(1, 359, 225, 439, 295, 14)
    end
    engine.insert_bulanci()
    engine.insert_opponent(7, 3, 120, 5)
    engine.insert_opponent(7, 2, 120, 4)
    engine.insert_opponent(7, 2, 120, 1)
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x0000(entitySlot, 373, 241)
    elseif _sw == 1 then
        fn_0x049c(entitySlot)
    else
        fn_0x0000(entitySlot, 373, 241)
    end
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
    elseif _sw == 1 then
    end
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local v0, v1, v2, v3 = 0, 0, 0, 0
    v0 = engine.strm_read(streamHandle, 1)
    if v0 == 1 then
        v3 = engine.strm_read(streamHandle, 1)
        v1 = engine.strm_read(streamHandle, 4)
        v2 = engine.strm_read(streamHandle, 4)
        engine.teleport_player_to(v3, v1, v2, 1)
    end
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
function fn_0x0000(p0, p1, p2)
    if engine.teleport_player_to(p0, p1, p2, 0) == 0 then
        return 0
    end
    if engine.is_net() ~= 0 then
        engine.strm_set_size(engine.get_global(3), 0)
        engine.strm_write(engine.get_global(3), 1, 1)
        engine.strm_write(engine.get_global(3), p0, 1)
        engine.strm_write(engine.get_global(3), p1, 4)
        engine.strm_write(engine.get_global(3), p2, 4)
        engine.strm_send(engine.get_global(3))
    end
    return 1
end

-- helper (call-target)
function fn_0x049c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 3)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 9, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 4 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 4 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 9, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 4 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 4 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 9, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 4 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

