--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 30, engine.str_const("7. 7. 1993"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 30, engine.str_const("Památný den. První Bulánek se prochází po měsíci. \"Cítil jsem se lehký,\njako pírko\", prohlašuje po svém návratu astronaut Uhlík. "), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 63, engine.str_const("8. 11. 1993"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 63, engine.str_const("Převratný vynález. Bratři Čmelíkové, specialisté na genetiku a rozmnožování,\nsestrojují první plně automatizovanou dračku peří."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 96, engine.str_const("1994"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 96, engine.str_const("Populační exploze. Hojné využívání dračky peří\nvede k enormnímu nárůstu bulánčí populace.\nZáhy se však u takto narozených Bulánků\nprojevuje genetická vada řeči, a proto je\ndalší velkovýroba zastavena."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(30, 170, engine.str_const("23. 2. 1995"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(100, 170, engine.str_const("Archeologický nález. Poblíž slovenské obce\nVankúšov jsou nalezeny ostatky Bulánčího\nlovce z doby bronzové. Tento nečekaný objev\npodává nezvratný a zároveň zneklidňující důkaz,\nže bulánčí kultura má mnohem hlubší kořeny,\nnež se vědci domnívali."), 1, 65711))
    engine.hh_add_child(engine.hcreate_movie(30, 266, 65590, 77830, 77831))
    engine.hh_add_child(engine.hcreate_movie(350, 90, 65613, 77828, 77829))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(206, 276, engine.str_const("5. 5. 1995"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(276, 276, engine.str_const("Výročí vzpoury. U příležitosti 20. výročí\nBulánčí vzpoury je uspořádána malá slavnostní\nvzpoura, která přerůstá v ničivý pochod ulicemi.\nIncident musí nakonec řešit pořádková policie."), 1, 65711))
    engine.hh_add_child(engine.hh_set_static_text_style(engine.hh_build_static_text_auto(206, 335, engine.str_const("1995 - 1998"), 1, 65711), 2, {0, 16777215}))
    engine.hh_add_child(engine.hh_build_static_text_auto(276, 335, engine.str_const("Zlatá léta. Období svobody, nespoutaných\nvečírků, květin a pestrobarevného povlečení.\nVšichni vybízejí ke vzájemné lásce a toleranci\nve snaze vytvořit lepší svět."), 1, 65711))
    return 0
end

