--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("271BBE43-1D32-4AF3-8A2C-F24B08C71831"))
    engine.set_global(0, engine.str_const("Bunkers"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_image(207, 0, 100006))
    engine.insert_view(engine.create_obstacle(18, 493, 47, 513))
    engine.insert_view(engine.create_obstacle(201, 491, 230, 515))
    engine.insert_view(engine.create_obstacle(133, 416, 162, 435))
    engine.insert_view(engine.create_obstacle(59, 235, 72, 247))
    engine.insert_view(engine.create_obstacle(403, 66, 427, 91))
    engine.insert_view(engine.create_obstacle(391, 83, 435, 95))
    engine.insert_view(engine.create_obstacle(421, 5, 446, 20))
    engine.insert_view(engine.create_obstacle(416, 14, 445, 35))
    engine.insert_view(engine.create_obstacle(411, 33, 443, 56))
    engine.insert_view(engine.create_obstacle(410, 48, 439, 88))
    engine.insert_view(engine.create_obstacle(589, 135, 800, 167))
    engine.insert_view(engine.create_obstacle(68, 235, 86, 254))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(275, 77, 302, 109), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(292, 133, 322, 164), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(281, 104, 319, 142), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(776, 219, 800, 269), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(742, 221, 787, 269), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(614, 222, 740, 267), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(512, 232, 533, 261), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(534, 222, 615, 260), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(478, 241, 516, 266), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(450, 258, 486, 293), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(437, 274, 456, 313), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(380, 277, 435, 303), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(295, 181, 335, 227), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(286, 150, 332, 192), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(263, 54, 299, 87), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(247, 14, 276, 42), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(256, 41, 293, 55), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(231, 0, 264, 40), 1))
    engine.insert_view(engine.create_obstacle(175, 137, 198, 161))
    engine.insert_view(engine.create_obstacle(160, 149, 180, 170))
    engine.insert_view(engine.create_obstacle(144, 163, 168, 187))
    engine.insert_view(engine.create_obstacle(128, 184, 150, 209))
    engine.insert_view(engine.create_obstacle(111, 197, 133, 223))
    engine.insert_view(engine.create_obstacle(97, 216, 120, 242))
    engine.insert_view(engine.create_obstacle(81, 234, 106, 260))
    engine.insert_view(engine.create_obstacle(593, 382, 613, 407))
    engine.insert_view(engine.create_obstacle(578, 403, 594, 427))
    engine.insert_view(engine.create_obstacle(491, 492, 513, 515))
    engine.insert_view(engine.create_obstacle(511, 475, 530, 496))
    engine.insert_view(engine.create_obstacle(528, 458, 548, 478))
    engine.insert_view(engine.create_obstacle(543, 438, 562, 461))
    engine.insert_view(engine.create_obstacle(556, 421, 576, 444))
    engine.insert_view(engine.create_obstacle(570, 404, 589, 424))
    engine.insert_view(engine.create_image(246, 191, 100005))
    engine.set_insert_mode(2)
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(143, 337, 100009), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(382, 0, 100008), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 337, 100010), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(59, 117, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(477, 366, 100004), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(580, 81, 100007), 0))
    engine.insert_view(engine.set_order_axis(engine.create_image(78, 259, 100009), 0))
    engine.set_insert_mode(0)
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

