--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("280A5615-36D3-49B5-B0AE-D7F566F2D00F"))
    engine.set_global(0, engine.str_const("svět 3005"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(625, 376, 628, 398))
    engine.insert_view(engine.create_obstacle(613, 380, 623, 410))
    engine.insert_view(engine.create_obstacle(546, 380, 611, 411))
    engine.insert_view(engine.create_obstacle(613, 503, 622, 515))
    engine.insert_view(engine.create_obstacle(535, 398, 613, 514))
    engine.insert_view(engine.create_obstacle(353, 379, 425, 414))
    engine.insert_view(engine.create_obstacle(353, 419, 415, 464))
    engine.insert_view(engine.create_obstacle(332, 457, 407, 499))
    engine.insert_view(engine.create_obstacle(243, 480, 322, 505))
    engine.insert_view(engine.create_obstacle(283, 392, 292, 408))
    engine.insert_view(engine.create_obstacle(148, 374, 171, 406))
    engine.insert_view(engine.create_obstacle(163, 376, 239, 426))
    engine.insert_view(engine.create_obstacle(0, 485, 36, 515))
    engine.insert_view(engine.create_obstacle(64, 467, 95, 490))
    engine.insert_view(engine.create_obstacle(95, 480, 124, 502))
    engine.insert_view(engine.create_obstacle(0, 371, 13, 394))
    engine.insert_view(engine.create_obstacle(650, 153, 666, 161))
    engine.insert_view(engine.create_obstacle(583, 153, 607, 166))
    engine.insert_view(engine.create_obstacle(605, 150, 652, 170))
    engine.insert_view(engine.create_obstacle(576, 100, 673, 151))
    engine.insert_view(engine.create_obstacle(486, 112, 567, 165))
    engine.insert_view(engine.create_obstacle(565, 94, 576, 174))
    engine.insert_view(engine.create_obstacle(477, 90, 491, 171))
    engine.insert_view(engine.create_obstacle(399, 158, 455, 170))
    engine.insert_view(engine.create_obstacle(380, 113, 468, 157))
    engine.insert_view(engine.create_obstacle(189, 109, 205, 159))
    engine.insert_view(engine.create_obstacle(199, 109, 273, 168))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(145, 26, 153, 52), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(138, 13, 154, 30), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(205, 9, 215, 24), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(130, 0, 152, 13), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(196, 23, 222, 82), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(152, 0, 204, 86), 1))
    engine.insert_view(engine.create_obstacle(65, 185, 76, 205))
    engine.insert_view(engine.create_obstacle(67, 167, 84, 183))
    engine.insert_view(engine.create_obstacle(62, 140, 92, 166))
    engine.insert_view(engine.create_obstacle(1, 135, 67, 226))
    engine.insert_view(engine.create_obstacle(551, 284, 568, 301))
    engine.set_insert_mode(2)
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(506, 224, 100014), 182))
    engine.insert_view(engine.set_order_axis(engine.create_image(52, 457, 100013), -40))
    engine.insert_view(engine.set_order_axis(engine.create_image(0, 315, 100012), -25))
    engine.insert_view(engine.set_order_axis(engine.create_image(219, 305, 100011), -32))
    engine.insert_view(engine.set_order_axis(engine.create_image(328, 335, 100010), -122))
    engine.insert_view(engine.set_order_axis(engine.create_image(528, 335, 100009), -123))
    engine.insert_view(engine.set_order_axis(engine.create_image(474, 89, 100008), -50))
    engine.insert_view(engine.set_order_axis(engine.create_image(369, 78, 100007), -59))
    engine.insert_view(engine.set_order_axis(engine.create_image(146, 331, 100006), -49))
    engine.insert_view(engine.set_order_axis(engine.create_image(183, 75, 100005), -46))
    engine.insert_view(engine.set_order_axis(engine.create_image(572, 74, 100004), -63))
    engine.set_insert_mode(0)
    engine.insert_bulanci()
    engine.insert_vampires()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

