--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x0565, fn_0x059a, fn_0x063e, fn_0x05d9, fn_0x06f6

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 3)
    engine.set_global(2, engine.str_const("C48AEB13-1BE6-41e1-A50E-7BBA39E43188"))
    if language == 1 then
        engine.set_global(0, engine.str_const("Noční směna"))
        return 0
    end
    engine.set_global(0, engine.str_const("Steel works"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(1024, 1024))
        engine.set_comm_strm(engine.get_global(3))
    end
    if engine.is_server() ~= 0 then
        engine.register_timer(0, 0, 7)
    end
    engine.load_preface(65624)
    engine.set_music(65863, 65538)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65623))
    engine.insert_view(engine.create_anim(701, 180, 3, {65780}))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(129, 99, 65622), -110))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(0, 0, 65621))
    engine.insert_view(engine.create_image(736, 323, 65626))
    engine.insert_view(engine.create_image(551, 425, 65620))
    engine.insert_view(engine.create_image(713, 0, 65625))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(538, -347, 0, {65781}), 6))
    engine.insert_view(engine.create_obstacle(685, 148, 799, 245))
    engine.insert_view(engine.create_obstacle(695, 254, 799, 362))
    engine.insert_view(engine.create_obstacle(0, 0, 27, 23))
    engine.insert_view(engine.create_obstacle(0, 496, 447, 515))
    engine.insert_view(engine.create_obstacle(524, 507, 799, 515))
    engine.insert_view(engine.create_obstacle(641, 0, 743, 60))
    engine.insert_view(engine.create_obstacle(623, 475, 724, 515))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(136, 17, 168, 27), 10))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(579, 20, 610, 30), 11))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(447, 450, 477, 460), 12))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(494, 450, 524, 460), 13))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(26, 390, 36, 431), 14))
    engine.insert_view(engine.create_obstacle(136, 0, 168, 17))
    engine.insert_view(engine.create_obstacle(579, 0, 610, 20))
    engine.insert_view(engine.create_obstacle(447, 460, 524, 515))
    engine.insert_view(engine.create_obstacle(0, 390, 26, 431))
    engine.insert_view(engine.create_obstacle(232, 148, 410, 220))
    engine.insert_view(engine.create_obstacle(200, 190, 232, 220))
    engine.insert_view(engine.create_obstacle(127, 220, 367, 296))
    engine.insert_view(engine.create_obstacle(162, 296, 320, 342))
    engine.insert_view(engine.create_obstacle(220, 240, 300, 370))
    engine.insert_view(engine.create_obstacle(320, 296, 342, 315))
    engine.insert_view(engine.create_obstacle(367, 232, 390, 256))
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    if slot ~= 6 then
        return 0
    end
    if evt == 0 then
        engine.anim_resume(engine.get_slot(6))
        if engine.is_server() ~= 0 then
            engine.timer_set_data(0, 10000)
        end
        return 0
    end
    fn_0x0565()
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    local _sw = slot
    if _sw == 10 then
        fn_0x059a(3, msgHi, msgLoBits, 2, slot)
        return 0
    elseif _sw == 11 then
        fn_0x059a(4, msgHi, msgLoBits, 2, slot)
        return 0
    elseif _sw == 12 then
        fn_0x059a(2, msgHi, msgLoBits, 3, slot)
        return 0
    elseif _sw == 13 then
        fn_0x059a(0, msgHi, msgLoBits, 3, slot)
        return 0
    elseif _sw == 14 then
        fn_0x059a(1, msgHi, msgLoBits, 0, slot)
        return 0
    else
        return 0
    end
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    if engine.is_server() == 0 then
        return 0
    end
    if slotId ~= 0 then
        fn_0x063e(engine.map_get(slotId))
        return 0
    end
    fn_0x06f6()
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local _sw = engine.strm_read(engine.get_global(3), 1)
    if _sw == 0 then
        fn_0x06f6()
        return 0
    elseif _sw == 1 then
        fn_0x063e(engine.strm_read(engine.get_global(3), 2))
        return 0
    else
        return 0
    end
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    fn_0x0565()
    return 0
end

-- helper (call-target)
function fn_0x0565()
    if engine.is_server() ~= 0 then
        engine.timer_set_data(0, ((math.random(0, 6) * 5000) + 30000))
        engine.timer_stop(0)
    end
    return 0
end

-- helper (call-target)
function fn_0x059a(p0, p1, p2, p3, p4)
    if p2 == p3 then
        engine.spawn_at_view(1, p4)
        if engine.is_server() ~= 0 then
            engine.map_set(engine.register_timer(-1, 2000, 2), (p0 + bit32.lshift(p1, 8)))
        end
    end
    return 0
end

-- helper (call-target)
function fn_0x063e(p0)
    local _sw = bit32.band(p0, 255)
    if _sw == 1 then
        fn_0x05d9(592, 32, 3, p0)
    elseif _sw == 2 then
        fn_0x05d9(461, 440, 2, p0)
    elseif _sw == 3 then
        fn_0x05d9(500, 440, 2, p0)
    elseif _sw == 4 then
        fn_0x05d9(38, 409, 1, p0)
    else
        fn_0x05d9(150, 29, 3, p0)
    end
    return 0
end

-- helper (call-target)
function fn_0x05d9(p0, p1, p2, p3)
    local v0 = 0
    v0 = bit32.rshift(p3, 8)
    engine.spawn_enemy_at(p0, p1, p2, v0, 1)
    engine.spawn_at_view(2, (v0 + 10))
    if engine.is_server() ~= 0 then
        if engine.is_net() ~= 0 then
            engine.strm_set_size(engine.get_global(3), 0)
            engine.strm_write(engine.get_global(3), 1, 1)
            engine.strm_write(engine.get_global(3), p3, 2)
            engine.strm_send(engine.get_global(3))
        end
    end
    return 0
end

-- helper (call-target)
function fn_0x06f6()
    engine.play_anim(engine.get_slot(6), 0)
    engine.spawn_at_view(0, 255)
    if engine.is_server() ~= 0 then
        engine.timer_start(0)
        if engine.is_net() ~= 0 then
            engine.strm_set_size(engine.get_global(3), 0)
            engine.strm_write(engine.get_global(3), 0, 1)
            engine.strm_send(engine.get_global(3))
        end
    end
    return 0
end

