--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x06e8, fn_0x06c2, fn_0x0a44, fn_0x0a89, fn_0x0b55, fn_0x0bae, fn_0x0bd6

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 5)
    engine.set_global(2, engine.str_const("C7B4C92B-5196-4b24-A090-0BF090A95DB3"))
    if language == 1 then
        engine.set_global(0, engine.str_const("V zajetí 8-bitu"))
        return 0
    end
    engine.set_global(0, engine.str_const("8-bit"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    engine.set_global(4, 0)
    engine.set_global(5, 0)
    engine.set_global(6, 0)
    engine.set_global(7, 0)
    engine.set_global(8, 0)
    engine.set_global(9, 0)
    engine.set_global(14, 0)
    engine.set_global(13, 0)
    engine.set_global(10, 0)
    engine.set_global(11, 0)
    engine.set_global(12, engine.new_collection())
    engine.coll_insert(engine.get_global(12), -1, engine.get_image(65633))
    engine.coll_insert(engine.get_global(12), -1, engine.get_image(65634))
    engine.coll_insert(engine.get_global(12), -1, engine.get_image(65635))
    engine.coll_insert(engine.get_global(12), -1, engine.get_image(65632))
    if engine.is_net() ~= 0 then
        engine.set_global(11, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(11))
    end
    engine.load_preface(65641)
    engine.set_music(65864, 65536)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65636))
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(58, 250, 65631), -25))
    engine.insert_view(engine.set_order_axis(engine.create_image(576, 80, 65637), -25))
    engine.insert_view(engine.set_order_axis(engine.create_image(300, 106, 65629), -67))
    engine.insert_view(engine.set_order_axis(engine.create_image(133, 55, 65630), -30))
    engine.insert_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(199, 77, 0, {65795, 65798, 65796, 65799, 65794, 65797}), 9), -17))
    engine.insert_view(engine.show_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(175, 22, 0, {65800}), 20), -17)))
    engine.insert_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(54, 49, 0, {65790}), 10), -35))
    engine.insert_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(506, 256, 0, {65792}), 12), -17))
    engine.insert_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(507, 376, 0, {65793}), 14), -17))
    engine.insert_view(engine.set_order_axis(engine.bind_to_slot(engine.create_anim(175, 55, 0, {65791}), 16), -25))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_obstacle(95, 320, 245, 402))
    engine.insert_view(engine.create_obstacle(577, 109, 702, 166))
    engine.insert_view(engine.create_obstacle(303, 150, 422, 257))
    engine.insert_view(engine.create_obstacle(126, 73, 174, 123))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(58, 73, 110, 123), 11))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(522, 262, 598, 305), 13))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(533, 390, 609, 429), 15))
    engine.insert_view(engine.bind_to_slot(engine.create_obstacle(191, 73, 251, 123), 17))
    engine.insert_view(engine.show_view(engine.bind_to_slot(engine.create_obstacle(191, 73, 251, 123), 18)))
    engine.insert_view(engine.show_view(engine.bind_to_slot(engine.create_obstacle(191, 73, 251, 123), 19)))
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 30, 185, 105, 243, 6)
        engine.define_trace_area(1, 442, 67, 515, 131, 6)
        engine.define_trace_area(2, 694, 377, 770, 440, 6)
        engine.define_trace_area(3, 191, 73, 251, 123, 10)
        engine.define_trace_area(4, 200, 128, 243, 322, 8)
        engine.define_trace_area(5, 257, 80, 785, 116, 8)
        engine.define_trace_area(6, 200, 9, 243, 50, 8)
    end
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    engine.set_global(12, engine.free_object(engine.get_global(12)))
    if engine.get_global(11) ~= 0 then
        engine.set_global(11, engine.strm_destroy(engine.get_global(11)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    local _sw = slot
    if _sw == 10 then
        engine.anim_resume(engine.get_slot(10))
        if engine.get_global(3) ~= 9 then
            return 0
        end
        engine.remove_view(engine.get_slot(11), 1)
        engine.set_order_axis(engine.get_slot(10), -120)
        return 0
    elseif _sw == 12 then
        engine.anim_resume(engine.get_slot(12))
        if engine.get_global(4) ~= 4 then
            return 0
        end
        engine.remove_view(engine.get_slot(13), 1)
        engine.set_order_axis(engine.get_slot(12), -120)
        return 0
    elseif _sw == 14 then
        engine.anim_resume(engine.get_slot(14))
        if engine.get_global(5) ~= 4 then
            return 0
        end
        engine.remove_view(engine.get_slot(15), 1)
        engine.set_order_axis(engine.get_slot(14), -120)
        return 0
    elseif _sw == 16 then
        engine.anim_resume(engine.get_slot(16))
        if engine.get_global(6) ~= 2 then
            return 0
        end
        engine.remove_view(engine.get_slot(17), 1)
        engine.set_order_axis(engine.get_slot(16), -120)
        return 0
    elseif _sw == 9 then
        if engine.get_global(10) < 2 then
            engine.show_view(engine.get_slot(18))
            return 0
        end
        if engine.get_global(10) > 3 then
            local _sw5 = evt
            if _sw5 == 0 then
                engine.hide_view(engine.get_slot(19))
                engine.show_view(engine.get_slot(18))
                return 0
            elseif _sw5 == 1 then
                if engine.get_global(10) == 4 then
                    engine.spawn_opponent_ex(260, 96, 1, 9, 2, engine.get_global(12))
                    engine.spawn_at_view(0, 9)
                    return 0
                end
                engine.spawn_opponent_ex(221, 136, 3, 9, 2, engine.get_global(12))
                engine.spawn_at_view(0, 9)
                return 0
            elseif _sw5 == 2 then
                engine.show_view(engine.get_slot(19))
                engine.hide_view(engine.get_slot(18))
                return 0
            else
                engine.show_view(engine.get_slot(18))
                return 0
            end
        end
        local _sw7 = evt
        if _sw7 == 0 then
            engine.hide_view(engine.get_slot(19))
            engine.show_view(engine.get_slot(18))
            return 0
        elseif _sw7 == 1 then
            engine.show_view(engine.get_slot(19))
            engine.hide_view(engine.get_slot(18))
            return 0
        else
            engine.show_view(engine.get_slot(18))
            return 0
        end
    elseif _sw == 20 then
        engine.show_view(engine.get_slot(18))
        engine.set_order_axis(engine.get_slot(20), -120)
        return 0
    else
        return 0
    end
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    if engine.is_server() ~= 0 then
        fn_0x06e8(slot)
    end
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    if math.random(0, 2) ~= 0 then
        return 0
    end
    if engine.get_global(10) == 10 then
        return 0
    end
    if engine.get_global(6) < 2 then
        return 0
    end
    if engine.is_view_kind(engine.get_slot(9)) == 1 then
        return 0
    end
    if engine.get_global(7) ~= 0 then
        return 0
    end
    if fn_0x0bae() == 0 then
        fn_0x0b55(math.random(0, 1))
        return 0
    end
    if engine.get_global(9) == 0 then
        if engine.get_global(8) == 0 then
            fn_0x0b55(math.random(2, 3))
            return 0
        end
        if math.random(0, 3) ~= 0 then
            fn_0x0b55(1)
            return 0
        end
        fn_0x0b55(5)
        return 0
    end
    if math.random(0, 3) ~= 0 then
        fn_0x0b55(0)
        return 0
    end
    fn_0x0b55(4)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x0a89(entitySlot, 1, 2)
        return 0
    elseif _sw == 1 then
        fn_0x0a89(entitySlot, 0, 2)
        return 0
    elseif _sw == 2 then
        fn_0x0a89(entitySlot, 0, 1)
        return 0
    elseif _sw == 3 then
        engine.set_global(7, (engine.get_global(7) + 1))
        return 0
    elseif _sw == 4 then
        engine.set_global(8, (engine.get_global(8) + 1))
        fn_0x0bd6(1, 1)
        return 0
    elseif _sw == 5 then
        engine.set_global(9, (engine.get_global(9) + 1))
        fn_0x0bd6(0, 1)
        return 0
    elseif _sw == 6 then
        engine.set_global(14, (engine.get_global(14) + 1))
        return 0
    else
        return 0
    end
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 3 then
        engine.set_global(7, (engine.get_global(7) - 1))
        return 0
    elseif _sw == 4 then
        engine.set_global(8, (engine.get_global(8) - 1))
        return 0
    elseif _sw == 5 then
        engine.set_global(9, (engine.get_global(9) - 1))
        return 0
    elseif _sw == 6 then
        engine.set_global(14, (engine.get_global(14) - 1))
        return 0
    else
        return 0
    end
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local _sw = engine.strm_read(streamHandle, 1)
    if _sw == 1 then
        fn_0x0b55(engine.strm_read(streamHandle, 1))
        return 0
    elseif _sw == 2 then
        fn_0x06e8(engine.strm_read(streamHandle, 1))
        return 0
    elseif _sw == 3 then
        fn_0x0a44(0, engine.strm_read(streamHandle, 1), 1)
        return 0
    elseif _sw == 4 then
        fn_0x0a44(1, engine.strm_read(streamHandle, 1), 1)
        return 0
    elseif _sw == 5 then
        fn_0x0a44(2, engine.strm_read(streamHandle, 1), 1)
        return 0
    elseif _sw == 6 then
        fn_0x0a44(3, engine.strm_read(streamHandle, 1), 1)
        return 0
    else
        return 0
    end
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    if engine.is_server() ~= 0 then
        engine.register_timer(0, 3000, 6)
    end
    return 0
end

-- helper (call-target)
function fn_0x06e8(p0)
    local v0, v1 = 0, 0
    local _sw = p0
    if _sw == 11 then
        if engine.get_global(3) <= 8 then
            v0 = math.floor(engine.get_global(3) / 3)
            engine.set_global(3, (engine.get_global(3) + 1))
            v1 = math.floor(engine.get_global(3) / 3)
            fn_0x06c2(10, v1, 3)
            if v0 ~= v1 then
                engine.seek_anim(engine.get_slot(10), v0)
                engine.play_anim(engine.get_slot(10), 0)
            end
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), 2, 1)
                engine.strm_write(engine.get_global(11), p0, 1)
                engine.strm_send(engine.get_global(11))
            end
        end
        return 0
    elseif _sw == 13 then
        if engine.get_global(4) <= 3 then
            v0 = math.floor(engine.get_global(4) / 2)
            engine.set_global(4, (engine.get_global(4) + 1))
            v1 = math.floor(engine.get_global(4) / 2)
            fn_0x06c2(12, v1, 2)
            if v0 ~= v1 then
                engine.seek_anim(engine.get_slot(12), v0)
                engine.play_anim(engine.get_slot(12), 0)
            end
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), 2, 1)
                engine.strm_write(engine.get_global(11), p0, 1)
                engine.strm_send(engine.get_global(11))
            end
        end
        return 0
    elseif _sw == 15 then
        if engine.get_global(5) <= 3 then
            v0 = math.floor(engine.get_global(5) / 2)
            engine.set_global(5, (engine.get_global(5) + 1))
            v1 = math.floor(engine.get_global(5) / 2)
            fn_0x06c2(14, v1, 2)
            if v0 ~= v1 then
                engine.seek_anim(engine.get_slot(14), v0)
                engine.play_anim(engine.get_slot(14), 0)
            end
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), 2, 1)
                engine.strm_write(engine.get_global(11), p0, 1)
                engine.strm_send(engine.get_global(11))
            end
        end
        return 0
    elseif _sw == 17 then
        if engine.get_global(6) <= 1 then
            fn_0x06c2(16, engine.get_global(6), 1)
            engine.seek_anim(engine.get_slot(16), engine.get_global(6))
            engine.play_anim(engine.get_slot(16), 0)
            engine.set_global(6, (engine.get_global(6) + 1))
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), 2, 1)
                engine.strm_write(engine.get_global(11), p0, 1)
                engine.strm_send(engine.get_global(11))
            end
        end
        return 0
    elseif _sw == 19 then
        engine.set_global(13, (engine.get_global(13) + 1))
        if engine.get_global(13) > 7 then
            engine.spawn_at_view(2, 9)
            engine.anim_resume(engine.get_slot(9))
            engine.show_view(engine.get_slot(9))
            engine.show_view(engine.get_slot(19))
            engine.hide_view(engine.get_slot(18))
            engine.hide_view(engine.get_slot(20))
            engine.play_anim(engine.get_slot(20), 0)
            engine.set_global(10, 10)
        else
            engine.spawn_at_view(1, 9)
        end
        if engine.is_net() == 1 then
            engine.strm_set_size(engine.get_global(11), 0)
            engine.strm_write(engine.get_global(11), 2, 1)
            engine.strm_write(engine.get_global(11), p0, 1)
            engine.strm_send(engine.get_global(11))
        end
        return 0
    else
        return 0
    end
end

-- helper (call-target)
function fn_0x06c2(p0, p1, p2)
    if p1 == p2 then
        engine.spawn_at_view(4, p0)
        return 0
    end
    engine.spawn_at_view(3, p0)
    return 0
end

-- helper (call-target)
function fn_0x0a44(p0, p1, p2)
    local _sw = p1
    if _sw == 0 then
        return engine.teleport_player_to(p0, 40, 195, p2)
    elseif _sw == 1 then
        return engine.teleport_player_to(p0, 452, 77, p2)
    else
        return engine.teleport_player_to(p0, 704, 387, p2)
    end
end

-- helper (call-target)
function fn_0x0a89(p0, p1, p2)
    local v0 = 0
    if math.random(0, 10) < 5 then
        v0 = p1
        if fn_0x0a44(p0, p1, 0) == 1 then
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), (3 + p0), 1)
                engine.strm_write(engine.get_global(11), v0, 1)
                engine.strm_send(engine.get_global(11))
            end
            return 1
        end
        v0 = p2
        if fn_0x0a44(p0, p2, 0) == 1 then
            if engine.is_net() == 1 then
                engine.strm_set_size(engine.get_global(11), 0)
                engine.strm_write(engine.get_global(11), (3 + p0), 1)
                engine.strm_write(engine.get_global(11), v0, 1)
                engine.strm_send(engine.get_global(11))
            end
            return 1
        end
        return 0
    end
    v0 = p2
    if fn_0x0a44(p0, p2, 0) == 1 then
        if engine.is_net() == 1 then
            engine.strm_set_size(engine.get_global(11), 0)
            engine.strm_write(engine.get_global(11), (3 + p0), 1)
            engine.strm_write(engine.get_global(11), v0, 1)
            engine.strm_send(engine.get_global(11))
        end
        return 1
    end
    v0 = p1
    if fn_0x0a44(p0, p1, 0) == 1 then
        if engine.is_net() == 1 then
            engine.strm_set_size(engine.get_global(11), 0)
            engine.strm_write(engine.get_global(11), (3 + p0), 1)
            engine.strm_write(engine.get_global(11), v0, 1)
            engine.strm_send(engine.get_global(11))
        end
        return 1
    end
    return 0
end

-- helper (call-target)
function fn_0x0b55(p0)
    engine.set_global(10, p0)
    engine.set_anim(engine.get_slot(9), p0, 1)
    engine.play_anim(engine.get_slot(9), 0)
    engine.hide_view(engine.get_slot(18))
    if engine.is_net() == 1 then
        engine.strm_set_size(engine.get_global(11), 0)
        engine.strm_write(engine.get_global(11), 1, 1)
        engine.strm_write(engine.get_global(11), p0, 1)
        engine.strm_send(engine.get_global(11))
    end
    return 0
end

-- helper (call-target)
function fn_0x0bae()
    if engine.get_global(14) > 0 then
        return 0
    end
    if (engine.get_global(8) * engine.get_global(9)) == 0 then
        return 1
    end
    return 0
end

-- helper (call-target)
function fn_0x0bd6(p0, p1)
    if math.random(0, 1) ~= 0 then
        return 0
    end
    if engine.get_global(10) == 10 then
        return 0
    end
    if engine.is_view_kind(engine.get_slot(9)) == 1 then
        return 0
    end
    if engine.get_global(7) ~= 0 then
        return 0
    end
    if engine.get_global(6) < 2 then
        fn_0x0b55(p0)
        return 0
    end
    if p1 == 0 then
        fn_0x0b55(p0)
        return 0
    end
    if fn_0x0bae() == 1 then
        fn_0x0b55((4 + p0))
        return 0
    end
    fn_0x0b55(p0)
    return 0
end

