--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 4)
    engine.set_global(2, engine.str_const("A0A144D0-26B0-4049-A66F-7AE630965103"))
    if language == 1 then
        engine.set_global(0, engine.str_const("Malárie"))
        return 0
    end
    engine.set_global(0, engine.str_const("Malaria"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.register_timer(0, ((math.random(0, 10) * 1000) + 5000), 6)
    engine.load_preface(65640)
    engine.set_music(65869, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65639))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(432, 61, 65627))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(492, 0, 0, {65782}), 6))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(0, 0, 0, {65787}), 7))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(280, 0, 0, {65784}), 8))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(670, 390, 0, {65785}), 9))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(273, 208, 0, {65788}), 10))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(235, 88, 0, {65789}), 11))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(690, 320, 0, {65783}), 12))
    engine.insert_view(engine.create_obstacle(334, 376, 395, 445))
    engine.insert_view(engine.create_obstacle(395, 354, 454, 406))
    engine.insert_view(engine.create_obstacle(120, 0, 312, 77))
    engine.insert_view(engine.create_obstacle(250, 77, 325, 108))
    engine.insert_view(engine.create_obstacle(290, 108, 353, 137))
    engine.insert_view(engine.create_obstacle(586, 237, 651, 284))
    engine.insert_view(engine.create_obstacle(313, 137, 352, 175))
    engine.insert_view(engine.create_image(0, 0, 65628))
    engine.insert_view(engine.bind_to_slot(engine.create_anim(0, 236, 0, {65786}), 13))
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    engine.play_anim(engine.get_slot(6), 0)
    engine.play_anim(engine.get_slot(7), 0)
    engine.play_anim(engine.get_slot(8), 0)
    engine.play_anim(engine.get_slot(9), 0)
    engine.play_anim(engine.get_slot(10), 0)
    engine.play_anim(engine.get_slot(11), 0)
    engine.play_anim(engine.get_slot(12), 0)
    engine.play_anim(engine.get_slot(13), 0)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

