--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- forward declarations (helpers are file-locals)
local fn_0x0239, fn_0x0296

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 6)
    engine.set_global(2, engine.str_const("987EF758-1BD5-4954-B543-767F158B17AF"))
    engine.set_global(0, engine.str_const("Exitus"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(65589)
    engine.set_music(65862, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65638))
    engine.set_insert_mode(2)
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(0, 140, 140, 175), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(140, 110, 180, 135), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(185, 0, 225, 50), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(225, 0, 259, 17), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(123, 129, 157, 150), 1))
    engine.insert_view(engine.enable_fire_through(engine.create_obstacle(0, 175, 17, 200), 1))
    engine.insert_view(engine.create_obstacle(343, 421, 386, 456))
    engine.insert_view(engine.create_obstacle(370, 399, 410, 430))
    engine.insert_view(engine.create_obstacle(385, 368, 441, 409))
    engine.insert_view(engine.create_obstacle(427, 349, 541, 387))
    engine.insert_view(engine.create_obstacle(541, 373, 583, 410))
    fn_0x0239()
    fn_0x0296()
    engine.set_insert_mode(1)
    engine.insert_bulanci()
    engine.insert_vampires()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
function fn_0x0239()
    if math.random(0, 5) ~= 0 then
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_image(625, 0, 65583))
    end
    if math.random(0, 5) ~= 0 then
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_image(678, 250, 65584))
    end
    return 0
end

-- helper (call-target)
function fn_0x0296()
    if math.random(0, 5) ~= 6 then
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(404, 56, 65574))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(404, 56, 65573), -25))
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_obstacle(413, 93, 549, 138))
        engine.insert_view(engine.create_obstacle(428, 134, 486, 167))
    end
    if math.random(0, 5) ~= 6 then
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(664, 113, 65580))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(664, 113, 65575), -20))
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_obstacle(667, 259, 713, 297))
    end
    if math.random(0, 5) ~= 6 then
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(82, 237, 65577))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(82, 237, 65576), -20))
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_obstacle(130, 277, 178, 334))
        engine.insert_view(engine.create_obstacle(96, 321, 138, 359))
    end
    if math.random(0, 5) ~= 6 then
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(294, 361, 65579))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(294, 361, 65578), -25))
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_obstacle(311, 406, 346, 446))
    end
    if math.random(0, 5) ~= 6 then
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(50, 71, 65582))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(50, 71, 65581), -25))
        engine.set_insert_mode(2)
        engine.insert_view(engine.create_obstacle(67, 114, 110, 155))
    end
    return 0
end

