<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Editor</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Editor.Data.lang.xml" />
    <EmbeddedResource Include="Editor.Data.lang.xml" LogicalName="Editor.Data.lang.xml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="zlib.net">
      <HintPath>..\zlib.net.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="NAudio">
      <HintPath>..\NAudio.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>