#ifndef _BULANCI_GLOBALS_H
#define _BULANCI_GLOBALS_H

#define GLUE(a, b) a##b
#define STATIC_ASSERT(cond) typedef char GLUE(static_assertion_failed, __LINE__)[(cond) ? 1 : -1]

typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned int uint;
typedef unsigned long ulong;

typedef __int64 longlong;
typedef unsigned __int64 ulonglong;

/*
 * Curated Win32 / DirectX typedef stubs.
 *
 * `scripts/ghidra/GenerateMapping.java` preserves typedef names whose
 * base type is a primitive or a struct (`HRESULT`, `DWORD`, `BOOL`,
 * `WAVEFORMATEX`, `GUID`, ...) so they read naturally in mapping.csv
 * and the generated stubs. We pre-declare the most common ones here
 * so the stubs compile against the vendored MSVC8 + DXSDK without
 * having to pull in the full Windows headers in every translation
 * unit. Typedefs not listed here are forward-declared by the stub
 * generator as `struct Name;` - that's fine because every stub body
 * is empty and the parameter is only ever held by pointer.
 *
 * Keep this list short: each entry adds friction if you ever bring
 * in the real `windows.h`. Anything project-specific belongs in its
 * own header.
 */
typedef int BOOL;
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef long HRESULT;
typedef char CHAR;
typedef wchar_t WCHAR;
typedef int errno_t;
typedef void *PVOID;
typedef void *LPVOID;

#define DWORD_PTR DWORD

#define NULL 0
#define TRUE 1
#define FALSE 0

/*
 * STUB_BODY() - marks an unmatched function body in the splat-style src/
 * tree.  We can't use sotn/pokeemerald's `INCLUDE_ASM(folder, name)` trick
 * because the MSVC linker can't pull external `.s` fragments at link time:
 * every stub TU still has to provide a real C++ body for its symbol.
 *
 * `scripts/sync_units.py` recognises any function block whose body starts
 * with `STUB_BODY(` as "not yet matched" and may rewrite the signature
 * line when Ghidra moves the function to a new namespace.  Once you hand-
 * write a matching body, the STUB_BODY marker disappears and `sync_units`
 * leaves the block alone (only the `// !FUNC <addr>` markers are migrated
 * verbatim if the namespace assignment changes again).
 *
 * The macro itself is a no-op so the stub TU links cleanly.  Returning a
 * default-constructed value of an arbitrary scalar/pointer return type is
 * done by the generator on the line following STUB_BODY when needed.
 */
#define STUB_BODY(...) ((void)0)

/*
 * Externs for every data symbol the ExportDelinker'd target objects
 * reference (DAT_xxx, LAB_xxx, PTR_xxx_xxxxxxxx, s_xxx_xxxxxxxx, ...).
 * Hand-matched bodies that need to return / store / dereference one of
 * those globals can refer to it by name, e.g.
 *
 *     void* CFoo::FUN_xxxx() { return &DAT_004b3b20; }
 *
 * The header is regenerated by
 *   `python scripts/internal/extract_externs.py`
 * after `configure.py` rebuilds the target .obj's.
 */
#include "bulanci/_externs.h"

#endif
