--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1000)
    engine.set_global(2, engine.str_const("C4F1A65C-5057-4D19-B707-F3FF4A008B74"))
    engine.set_global(0, engine.str_const("Bludiště"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(3, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(3, engine.strm_create_mem(4096, 4096))
        engine.set_comm_strm(engine.get_global(3))
    end
    engine.load_preface(100001)
    engine.set_music(100003, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 100002))
    engine.insert_view(engine.create_obstacle(623, 207, 657, 235))
    engine.insert_view(engine.create_obstacle(52, 242, 91, 460))
    engine.insert_view(engine.create_obstacle(56, 214, 88, 246))
    engine.insert_view(engine.create_obstacle(52, 0, 89, 212))
    engine.insert_view(engine.create_obstacle(353, 76, 385, 101))
    engine.insert_view(engine.create_obstacle(148, 297, 185, 515))
    engine.insert_view(engine.create_obstacle(244, 419, 554, 458))
    engine.insert_view(engine.create_obstacle(237, 265, 277, 350))
    engine.insert_view(engine.create_obstacle(331, 270, 368, 378))
    engine.insert_view(engine.create_obstacle(482, 267, 522, 378))
    engine.insert_view(engine.create_obstacle(611, 233, 651, 515))
    engine.insert_view(engine.create_obstacle(709, 265, 747, 515))
    engine.insert_view(engine.create_obstacle(613, 162, 800, 204))
    engine.insert_view(engine.create_obstacle(461, 60, 800, 102))
    engine.insert_view(engine.create_obstacle(349, 0, 396, 70))
    engine.insert_view(engine.create_obstacle(238, 0, 284, 69))
    engine.insert_view(engine.create_obstacle(243, 165, 555, 203))
    engine.insert_view(engine.create_obstacle(143, 0, 182, 212))
    engine.set_insert_mode(2)
    engine.set_insert_mode(1)
    engine.insert_view(engine.set_order_axis(engine.create_image(620, 206, 100004), 0))
    engine.set_insert_mode(0)
    if engine.is_server() ~= 0 then
        engine.define_trace_area(0, 177, 450, 257, 520, 14)
        engine.define_trace_area(1, 77, -5, 157, 65, 14)
        engine.define_trace_area(2, 387, 289, 467, 359, 14)
        engine.define_trace_area(3, 641, 450, 721, 520, 14)
        engine.define_trace_area(4, 725, 450, 805, 520, 14)
        engine.define_trace_area(5, 725, 96, 805, 166, 14)
        engine.define_trace_area(6, 725, -5, 805, 65, 14)
        engine.define_trace_area(7, 174, -5, 254, 65, 14)
        engine.define_trace_area(8, 279, -5, 359, 65, 14)
    end
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(3) ~= 0 then
        engine.set_global(3, engine.strm_destroy(engine.get_global(3)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
        fn_0x042c(entitySlot)
    elseif _sw == 1 then
        fn_0x05bc(entitySlot)
    elseif _sw == 2 then
        fn_0x074c(entitySlot)
    elseif _sw == 3 then
        fn_0x08dc(entitySlot)
    elseif _sw == 4 then
        fn_0x0a6c(entitySlot)
    elseif _sw == 5 then
        fn_0x0bfc(entitySlot)
    elseif _sw == 6 then
        fn_0x0d8c(entitySlot)
    elseif _sw == 7 then
        fn_0x0f1c(entitySlot)
    elseif _sw == 8 then
        fn_0x10ac(entitySlot)
    else
        fn_0x042c(entitySlot)
    end
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    local _sw = traceId
    if _sw == 0 then
    elseif _sw == 1 then
    elseif _sw == 2 then
    elseif _sw == 3 then
    elseif _sw == 4 then
    elseif _sw == 5 then
    elseif _sw == 6 then
    elseif _sw == 7 then
    elseif _sw == 8 then
    end
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local v0, v1, v2, v3 = 0, 0, 0, 0
    v0 = engine.strm_read(streamHandle, 1)
    if v0 == 1 then
        v3 = engine.strm_read(streamHandle, 1)
        v1 = engine.strm_read(streamHandle, 4)
        v2 = engine.strm_read(streamHandle, 4)
        engine.teleport_player_to(v3, v1, v2, 1)
    end
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- helper (call-target)
local function fn_0x042c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x0000(p0, p1, p2)
    if engine.teleport_player_to(p0, p1, p2, 0) == 0 then
        return 0
    end
    if engine.is_net() ~= 0 then
        engine.strm_set_size(engine.get_global(3), 0)
        engine.strm_write(engine.get_global(3), 1, 1)
        engine.strm_write(engine.get_global(3), p0, 1)
        engine.strm_write(engine.get_global(3), p1, 4)
        engine.strm_write(engine.get_global(3), p2, 4)
        engine.strm_send(engine.get_global(3))
    end
    return 1
end

-- helper (call-target)
local function fn_0x05bc(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x074c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x08dc(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x0a6c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x0bfc(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x0d8c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x0f1c(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 293, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

-- helper (call-target)
local function fn_0x10ac(p0)
    local v0, v1 = 0, 0
    v0 = math.random(0, 7)
    v1 = v0
    while true do
        local _sw = v1
        if _sw == 0 then
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 1 then
            if fn_0x0000(p0, 91, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 2 then
            if fn_0x0000(p0, 401, 305) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 3 then
            if fn_0x0000(p0, 655, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 4 then
            if fn_0x0000(p0, 739, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 5 then
            if fn_0x0000(p0, 739, 112) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 6 then
            if fn_0x0000(p0, 739, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        elseif _sw == 7 then
            if fn_0x0000(p0, 188, 11) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        else
            if fn_0x0000(p0, 191, 466) == 1 then
                return 1
            end
            v1 = (v1 + 1)
            if v1 == 8 then
                v1 = 0
            end
            if v1 ~= v0 then
                continue
            end
            return 0
        end
    end
end

