--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 1)
    engine.set_global(2, engine.str_const("0DDB62C1-2E2E-430c-A914-73AD2669796A"))
    if language == 1 then
        engine.set_global(0, engine.str_const("Na dobrou noc"))
        return 0
    end
    engine.set_global(0, engine.str_const("Bedtime story"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.set_global(12, 0)
    if engine.is_net() ~= 0 then
        engine.set_global(12, engine.strm_create_mem(1024, 1024))
        engine.set_comm_strm(engine.get_global(12))
    end
    engine.set_global(4, 0)
    engine.load_preface(65848)
    engine.set_music(65868, 65537)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65619))
    if engine.set_global(3, math.random(0, 1)) == 1 then
        place_bunny_on_log(195, 364)
        place_gun_mouse(124, 283, 580)
        place_butterfly_decor(309, 50)
        place_bird_in_nest(576, 245)
        place_bush_decor(67, 85)
        engine.insert_bulanci()
        return 0
    end
    place_bunny_on_log(568, 360)
    place_gun_mouse(227, 103, 800)
    place_butterfly_decor(417, 113)
    place_bird_in_nest(154, 306)
    place_bush_decor(61, 127)
    engine.insert_bulanci()
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    if engine.get_global(12) ~= 0 then
        engine.set_global(12, engine.strm_destroy(engine.get_global(12)))
    end
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    local v0 = 0
    local _sw = slot
    if _sw == 4 then
        if bit32.band(engine.get_global(4), 1) == 1 then
            return 0
        end
        v0 = math.random(0, 3)
        if v0 == 1 then
            engine.spawn_at_view(0, 4)
        end
        engine.set_anim(engine.get_slot(4), v0, 1)
        return 0
    elseif _sw == 6 then
        if bit32.band(engine.get_global(4), 2) == 2 then
            return 0
        end
        engine.set_anim(engine.get_slot(6), math.random(0, 3), 1)
        return 0
    elseif _sw == 8 then
        engine.set_anim(engine.get_slot(8), math.random(0, 2), 1)
        return 0
    elseif _sw == 9 then
        if bit32.band(engine.get_global(4), 4) == 4 then
            return 0
        end
        v0 = 0
        if engine.get_global(7) >= 4 then
            v0 = 1
        end
        local _sw = engine.get_global(7)
        if _sw == 1 then
            engine.set_global(11, 1)
            if engine.is_server() == 0 then
                return 0
            end
            engine.timer_set_data(0, (math.random(3, 15) * 1000))
            engine.timer_stop(0)
            return 0
        elseif _sw == 2 then
            if engine.is_server() == 0 then
                return 0
            end
            mimic_spawn_closeup(v0)
            return 0
        elseif _sw == 5 then
            engine.set_global(11, 1)
            if engine.is_server() == 0 then
                return 0
            end
            engine.timer_set_data(0, (math.random(3, 15) * 1000))
            engine.timer_stop(0)
            return 0
        elseif _sw == 6 then
            if engine.is_server() == 0 then
                return 0
            end
            mimic_spawn_closeup(v0)
            return 0
        else
            if engine.is_server() == 0 then
                return 0
            end
            if v0 == 0 then
                if engine.get_global(10) < 1 then
                    mimic_spawn_closeup(v0)
                    return 0
                end
                mimic_spawn_init(v0)
                return 0
            end
            if engine.get_global(9) < 1 then
                mimic_spawn_closeup(v0)
                return 0
            end
            mimic_spawn_init(v0)
            return 0
        end
    else
        return 0
    end
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    if engine.is_server() ~= 0 then
        mimic_dispatch_event(slot)
    end
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    local _sw = slotId
    if _sw == 0 then
        engine.timer_start(0)
        mimic_trigger(math.random(0, 1))
        return 0
    else
        return 0
    end
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    if bit32.band(engine.get_global(4), 4) == 4 then
        return 0
    end
    if traceId == 0 then
        engine.set_global(9, (engine.get_global(9) + 1))
        if math.random(0, 3) == 0 then
            mimic_trigger(1)
        end
        return 0
    end
    engine.set_global(10, (engine.get_global(10) + 1))
    if math.random(0, 3) ~= 0 then
        return 0
    end
    mimic_trigger(0)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    if bit32.band(engine.get_global(4), 4) == 4 then
        return 0
    end
    if traceId == 0 then
        engine.set_global(9, (engine.get_global(9) - 1))
        return 0
    end
    engine.set_global(10, (engine.get_global(10) - 1))
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    local _sw = engine.strm_read(streamHandle, 1)
    if _sw == 0 then
        mimic_dispatch_event(engine.strm_read(streamHandle, 1))
        return 0
    elseif _sw == 1 then
        mimic_trigger(engine.strm_read(streamHandle, 1))
        return 0
    elseif _sw == 2 then
        mimic_spawn_init(engine.strm_read(streamHandle, 1))
        return 0
    elseif _sw == 3 then
        mimic_spawn_closeup(engine.strm_read(streamHandle, 1))
        return 0
    else
        return 0
    end
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

-- BUTTERFLY decor on bed-night level "Na dobrou noc" / "Bedtime story". ALWAYS present — no
-- presence roll (fn@0x1e7 has no Rand). Inserts butterfly trio anim 65764..65766 bound to slot 1,
-- plus images 65643 (body, +8/+141 offset) and 65642 (base, order axis -39), 1 obstacle
-- (27,97)-(175,133), 1 obstacle bounds at (27,180)-(180,216). Per catalog:
-- "level_bedtime_butterfly_fly_a/b/c" in levels/bedtime_story/decor.
local function place_butterfly_decor(x, y)
    local v0 = 0
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image((x + 8), (y + 141), 65643))
    engine.set_insert_mode(1)
    v0 = engine.set_order_axis(engine.create_image(x, y, 65642), -39)
    engine.insert_view(engine.set_obstacle_bounds(v0, 27, 180, 180, 216))
    engine.set_insert_mode(2)
    engine.insert_view(engine.translate_to(engine.create_obstacle(27, 97, 175, 133), x, y))
    engine.insert_view(engine.set_anim_frame(engine.bind_to_slot(engine.create_anim((x + 50), (y + 50), 1, {65764, 65765, 65766}), 8), 1))
    return 0
end

-- BROWN BUNNY on log platform (level_bedtime_bunny_clip_*). 1/8 chance of being absent (Rand 0..7,
-- absent iff ==0). Inserts 6 obstacle bumps (the "log platform" decorative shape: 79,50)-(112,80),
-- (2,58)-(23,108), (23,44)-(42,108), (42,28)-(66,91), (66,14)-(87,69), (87,0)-(134,42) translated
-- by (x,y); 1 image 65609 (the LOG); 5-frame bunny anim 65759..65763 bound to slot 6 (clip A=8f
-- idle, B=5f static, C=20f idle, D=25f decapitation/death, E=20f idle). Slot 6 position offset:
-- anim at (x+49, y-15).
local function place_bunny_on_log(x, y)
    local v0 = 0
    if math.random(0, 7) ~= 0 then
        engine.set_insert_mode(2)
        engine.insert_view(engine.bind_to_slot(engine.translate_to(engine.create_obstacle(79, 50, 112, 80), x, y), 7))
        engine.insert_view(engine.translate_to(engine.create_obstacle(2, 58, 23, 108), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(23, 44, 42, 108), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(42, 28, 66, 91), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(66, 14, 87, 69), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(87, 0, 134, 42), x, y))
        engine.set_insert_mode(0)
        engine.insert_view(engine.create_image(x, y, 65609))
        v0 = engine.create_anim((x + 49), (y + -15), 1, {65759, 65760, 65761, 65763, 65762})
        engine.bind_to_slot(v0, 6)
        engine.insert_view(v0)
    end
    return 0
end

-- GREY MOUSE WITH RIFLE (level_bedtime_mouse_*). 1/10 chance of being absent (Rand 0..9, absent
-- iff ==0). Sets globals 5/6/7/9/10/11=0. If server: defines 2 danger zones (0=(0,y-3)-(x,y+27),
-- 1=(x+66,y-3)-(arg3,y+27)), registers timer 0. Inserts 3 obstacles (36,0)-(45,14), (5,0)-(36,58),
-- (36,14)-(59,58) translated by (x,y); 1 image 65606 (the bush/cover the mouse hides behind, order
-- axis -25); 8-frame mouse anim 65767..65774 bound to slot 9 (clips 0..7 = pop/hide/shoot/death
-- for left and right, facing). Anim position offset: (x+17, y-29). Slot 9 = the gun-mouse's slot
-- in the mimic flow.
local function place_gun_mouse(x, y, danger_w)
    local v0 = 0
    if math.random(0, 9) ~= 0 then
        engine.set_global(5, x)
        engine.set_global(6, y)
        engine.set_global(7, 0)
        engine.set_global(9, 0)
        engine.set_global(10, 0)
        engine.set_global(11, 0)
        if engine.is_server() ~= 0 then
            engine.define_danger_zone(0, 0, (y + -3), x, (y + 27))
            engine.define_danger_zone(1, (x + 66), (y + -3), danger_w, (y + 27))
            engine.register_timer(0, 0, 7)
        end
        engine.set_insert_mode(2)
        engine.insert_view(engine.set_global(8, engine.translate_to(engine.create_obstacle(36, 0, 45, 14), x, y)))
        engine.insert_view(engine.translate_to(engine.create_obstacle(5, 0, 36, 58), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(36, 14, 59, 58), x, y))
        engine.set_insert_mode(1)
        engine.insert_view(engine.set_order_axis(engine.create_image(x, y, 65606), -25))
        v0 = engine.create_anim((x + 17), (y + -29), 1, {65767, 65768, 65769, 65770, 65771, 65772, 65773, 65774})
        engine.bind_to_slot(engine.set_order_axis(v0, 35), 9)
        engine.insert_view(v0)
    end
    return 0
end

-- BIRD IN A NEST (level_bedtime_bird_nest_*). 1/8 chance of being absent (Rand 0..7, absent iff
-- ==0). Inserts 4 obstacles (106,20)-(122,36), (7,35)-(63,83), (63,55)-(134,98), (49,20)-(93,35)
-- translated by (x,y); 1 image 65607 (the nest, order axis -25); 5-frame bird anim 65775..65779
-- bound to slot 4 (clip A=first of [65775..65779] @ fn@0x04e1 @+0x0589, B=2nd, C=3rd, D=12f idle,
-- E=10f death/gore). Anim position offset: (x+82, y+1). Slot 4 = the bird's slot in the mimic
-- flow.
local function place_bird_in_nest(x, y)
    local v0 = 0
    if math.random(0, 7) ~= 0 then
        engine.set_insert_mode(2)
        engine.insert_view(engine.bind_to_slot(engine.translate_to(engine.create_obstacle(106, 20, 122, 36), x, y), 5))
        engine.insert_view(engine.translate_to(engine.create_obstacle(7, 35, 63, 83), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(63, 55, 134, 98), x, y))
        engine.insert_view(engine.translate_to(engine.create_obstacle(49, 20, 93, 35), x, y))
        engine.set_insert_mode(1)
        v0 = engine.set_order_axis(engine.create_image(x, y, 65607), -25)
        engine.insert_view(v0)
        v0 = engine.create_anim((x + 82), (y + 1), 1, {65775, 65776, 65777, 65779, 65778})
        engine.bind_to_slot(engine.set_order_axis(v0, 50), 4)
        engine.insert_view(v0)
    end
    return 0
end

-- BERRY BUSH decor (level_bedtime_bush_*). 1/7 chance of being absent (Rand 0..6, absent iff ==0).
-- Inserts 1 image 65608 with order axis -40, sets obstacle bounds (9,23)-(90,60). No anim, no
-- obstacles, no danger zone, no timer. Pure decor.
local function place_bush_decor(x, y)
    local v0 = 0
    if math.random(0, 6) ~= 0 then
        engine.set_insert_mode(1)
        v0 = engine.set_order_axis(engine.create_image(x, y, 65608), -40)
        engine.insert_view(engine.set_obstacle_bounds(v0, 9, 23, 90, 60))
    end
    return 0
end

-- SERVER-SIDE mimic-triggered spawn. Calls fn@0x8ab to position the slot-9 mimic, sets g_anim_7 =
-- side*4+2, sets slot-9 anim. If side==1: spawn enemy at (g_pos5+65, g_pos6+10) facing right. If
-- side==0: spawn enemy at (g_pos5-10, g_pos6+10) facing left. Then spawnAtView(4, 9). Server-only:
-- binds g_global8 to slot 10, broadcasts to clients via fn@0x978(1, side).
local function mimic_spawn_init(side)
    mimic_position(side)
    engine.set_global(7, ((side * 4) + 2))
    engine.set_anim(engine.get_slot(9), engine.get_global(7), 1)
    if side == 1 then
        engine.spawn_enemy_at((engine.get_global(5) + -10), (engine.get_global(6) + 10), 0, 9, 1)
    else
        engine.spawn_enemy_at((engine.get_global(5) + 65), (engine.get_global(6) + 10), 1, 9, 1)
    end
    engine.spawn_at_view(4, 9)
    if engine.is_server() ~= 0 then
        engine.bind_to_slot(engine.get_global(8), 10)
        mimic_net_broadcast_init(1, side)
    end
    return 0
end

-- SERVER-SIDE close-up variant. Calls fn@0x8ab to position, sets g_anim_7 = side*4+1, sets slot-9
-- anim. Server-only: binds g_global8 to slot 255 (free), broadcasts via fn@0x978(2, side).
local function mimic_spawn_closeup(side)
    mimic_position(side)
    engine.set_global(7, ((side * 4) + 1))
    engine.set_anim(engine.get_slot(9), engine.get_global(7), 1)
    if engine.is_server() ~= 0 then
        engine.bind_to_slot(engine.get_global(8), 255)
        mimic_net_broadcast_init(2, side)
    end
    return 0
end

-- positions slot-9 mimic based on side. If side==0: (g_pos5+13, g_pos6-30). Else: (g_pos5+13,
-- g_pos6-25).
local function mimic_position(side)
    if side == 0 then
        engine.translate_to(engine.get_slot(9), (engine.get_global(5) + 13), (engine.get_global(6) + -25))
        return 0
    end
    engine.translate_to(engine.get_slot(9), (engine.get_global(5) + 13), (engine.get_global(6) + -30))
    return 0
end

-- master mimic trigger. If server AND g_state.11==0: call mimic_position(side), set g_anim_7 =
-- side*4, set slot-9 anim, clear g_state.11, broadcast via fn@0x978(0, side).
local function mimic_trigger(side)
    if engine.is_server() == 0 then
        mimic_position(side)
        engine.set_global(7, (side * 4))
        engine.set_anim(engine.get_slot(9), engine.get_global(7), 1)
        engine.set_global(11, 0)
        mimic_net_broadcast_init(0, side)
    else
        if engine.get_global(11) ~= 0 then
            mimic_position(side)
            engine.set_global(7, (side * 4))
            engine.set_anim(engine.get_slot(9), engine.get_global(7), 1)
            engine.set_global(11, 0)
            mimic_net_broadcast_init(0, side)
        end
    end
    return 0
end

-- client-side mirror of fn@0x09af case dispatch. Writes [0, slot] to global stream 12 and sends.
local function mimic_net_broadcast_event(slot)
    if engine.is_net() == 1 then
        engine.strm_set_size(engine.get_global(12), 0)
        engine.strm_write(engine.get_global(12), 0, 1)
        engine.strm_write(engine.get_global(12), slot, 1)
        engine.strm_send(engine.get_global(12))
    end
    return 0
end

-- broadcasts the init-event: writes [type+1, side] to global stream 12 and sends. Type 1 =
-- side-init (calls fn@0x7b5), type 2 = closeup (calls fn@0x85e).
local function mimic_net_broadcast_init(type, side)
    if engine.is_net() == 1 then
        engine.strm_set_size(engine.get_global(12), 0)
        engine.strm_write(engine.get_global(12), (type + 1), 1)
        engine.strm_write(engine.get_global(12), side, 1)
        engine.strm_send(engine.get_global(12))
    end
    return 0
end

-- SERVER-ONLY event handler dispatching on slot id: 5 = BIRD head-pop (g_state|=1, bindToSlot
-- slot5 255, anim slot4 frame 4, spawnAtView(2,4), broadcast); 7 = BUTTERFLY (g_state|=2,
-- bindToSlot slot7 255, anim slot6 frame 4, spawnAtView(1,6), broadcast); 10 = MOUSE (g_state|=4,
-- bindToSlot g8 255, g_anim_7++, anim slot9, spawnAtView(3,9), broadcast).
local function mimic_dispatch_event(slot)
    local _sw = slot
    if _sw == 5 then
        engine.set_global(4, bit32.bor(engine.get_global(4), 1))
        engine.bind_to_slot(engine.get_slot(5), 255)
        engine.set_anim(engine.get_slot(4), 4, 1)
        engine.spawn_at_view(2, 4)
        mimic_net_broadcast_event(5)
        return 0
    elseif _sw == 7 then
        engine.set_global(4, bit32.bor(engine.get_global(4), 2))
        engine.bind_to_slot(engine.get_slot(7), 255)
        engine.set_anim(engine.get_slot(6), 4, 1)
        engine.spawn_at_view(1, 6)
        mimic_net_broadcast_event(7)
        return 0
    elseif _sw == 10 then
        engine.set_global(4, bit32.bor(engine.get_global(4), 4))
        engine.bind_to_slot(engine.get_global(8), 255)
        engine.set_global(7, (engine.get_global(7) + 1))
        engine.set_anim(engine.get_slot(9), engine.get_global(7), 1)
        engine.spawn_at_view(3, 9)
        mimic_net_broadcast_event(10)
        return 0
    else
        return 0
    end
end

