--!nonstrict
-- Generated by asm_to_luau.py from the curated *.script.asm.
-- DO NOT EDIT BY HAND: edit the .asm and regenerate. Luau has no goto;
-- control flow is reconstructed as if/elseif/else + while/break/continue.
local engine = require("engine")

-- writes globals 0/1/2 = name/type/GUID for the level/help/history picker
function GetInfo(language)
    engine.set_global(1, 2)
    engine.set_global(2, engine.str_const("6A080067-362A-478d-B9EC-68F54424001B"))
    if language == 1 then
        engine.set_global(0, engine.str_const("Vybíjená"))
        return 0
    end
    engine.set_global(0, engine.str_const("Dj Slaughter"))
    return 0
end

-- fires once during CBulanci construction; level scene setup happens here
function OnInit()
    engine.load_preface(65847)
    engine.set_music(65861, 0)
    engine.set_insert_mode(0)
    engine.insert_view(engine.create_image(0, 0, 65846))
    engine.insert_view(engine.create_anim(448, 81, 3, {65752}))
    engine.insert_view(engine.create_anim(463, 63, 3, {65753}))
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_obstacle(0, 0, 800, 160))
    engine.insert_view(engine.create_obstacle(0, 160, 40, 233))
    engine.insert_view(engine.create_obstacle(0, 233, 20, 310))
    engine.insert_view(engine.create_obstacle(670, 160, 800, 180))
    engine.insert_view(engine.create_obstacle(760, 180, 800, 300))
    engine.insert_view(engine.create_obstacle(775, 300, 800, 365))
    engine.set_insert_mode(1)
    engine.insert_bulanci()
    engine.set_insert_mode(2)
    engine.insert_view(engine.create_image(0, 0, 65557))
    return 0
end

-- fires once during CGaming destruction; resource teardown
function OnDeinit()
    return 0
end

-- fires when a CBitmap sub-view emits an event (animation frame end, click/hit). slot = view.@0x70
-- = its CGaming slot, evt = the event code
function OnBitmapEvt(slot, evt)
    return 0
end

-- fires when CExplosion / net-msg-0x0f spawns or moves a slot via `FUN_00417e80` and msg 0xd7
-- reaches it. slot = destination slot, msgHi/msgLo = the upper/lower halves of the spawn parameter
function OnSlotPlaced(slot, msgHi, msgLoBits)
    return 0
end

-- companion to OnSlotPlaced: fires on a *second* slot when its occupant gets displaced by a
-- OnSlotPlaced event (msg 0xd8). slot = the displaced slot, byParam = the slot that displaced it
function OnSlotDisplaced(slot, byParam)
    return 0
end

-- fires when a `RegisterTimer(slotId, delay, flags)` countdown (opcodes 68..72; timer table at
-- `this+0x440`) expires; the slot id passed back is the same slotId originally registered
function OnTimer(slotId)
    return 0
end

-- fires when a player/entity *enters* a `DefineTraceArea` rectangle. traceId = the first arg
-- passed to DefineTraceArea, entitySlot = the 0..3 player slot (or 0x88-N for slots 4..7) that
-- crossed the boundary
function OnEnter(traceId, entitySlot)
    return 0
end

-- fires when a player/entity *leaves* a `DefineTraceArea` rectangle (symmetric to OnEnter, same
-- argument shape)
function OnLeave(traceId, entitySlot)
    return 0
end

-- fires from `CGame::ProcessNetMessage` case 0x15 with a stream handle. Scripts typically
-- `StrmRead(handle, 1)` the leading opcode byte and switch on it to dispatch their own RPC
-- sub-protocol
function OnNetCustom(streamHandle)
    return 0
end

-- fires from `CGaming::FUN_0041c140(true)` whenever the level transitions from paused/loaded to
-- running (level start, post-pause resume). Music is started and engine-side timer slots 1/2 are
-- armed right after this returns
function OnGameStart()
    return 0
end

