"""Generate `include/bulanci/_externs.h` from the target COFFs.

Every `build/orig/bulanci/*.obj` produced by ExportDelinker has COFF
relocations referencing data symbols that aren't defined in any of our
.objs: `DAT_xxx` (raw data globals), `LAB_xxx` (code labels jumped to
from another function), `PTR_xxx_xxxxxx` (IAT thunks for DLL imports),
`s_xxx_xxxx` (string literals), etc.

A C++ function body like

    void* CFoo::FUN_xxxx() { return &DAT_004b3b20; }

can only produce a matching COFF relocation if `DAT_004b3b20` is a
visible symbol in our compilation unit.  This script writes one big
`extern "C" unsigned char NAME;` block covering every such name so
hand-matched bodies can reference them by name.

Linker name matters: MSVC adds a leading `_` to C-linkage data
symbols in 32-bit mode.  `demangle_obj_symbols.py` strips that prefix
back off, so the final COFF symbol name agrees with ExportDelinker's
form (no underscore).

We skip:
  * `Class::method` and `Namespace::name` style names - those are
    defined in some other .obj already.
  * `*::vftable*` - these need member-pointer / RTTI handling, not
    plain `extern unsigned char`.  TODO: separate header.
  * `DLL.dll::Symbol` style import refs - these go through the IAT
    via `PTR_*` thunks, which we *do* declare.
"""

import argparse
import re
import struct
import sys
from collections import defaultdict
from pathlib import Path

HEADER = """\
// AUTO-GENERATED by scripts/internal/extract_externs.py - do not edit by hand.
//
// Externs for every data symbol the ExportDelinker'd target objects
// reference but don't define.  Including this file lets a hand-matched
// stub write `return &DAT_xxxx;` and produce a relocation that pairs
// against the original .obj.
//
// All entries are declared as `unsigned char` so the resulting COFF
// relocation type is a plain 32-bit absolute DIR32 in both objects.
// Cast the address in the function body to whatever type the function
// actually returns: `return reinterpret_cast<T*>(&DAT_xxxx);`.

#ifndef BULANCI_EXTERNS_H
#define BULANCI_EXTERNS_H

#ifdef __cplusplus
extern "C" {
#endif

"""

FOOTER = """\

#ifdef __cplusplus
}
#endif

#endif
"""


def parse_obj(path):
    data = path.read_bytes()
    n_sections = struct.unpack_from("<H", data, 2)[0]
    sym_tbl_off = struct.unpack_from("<I", data, 8)[0]
    n_syms = struct.unpack_from("<I", data, 12)[0]
    opthdr = struct.unpack_from("<H", data, 16)[0]
    sec_tbl = 20 + opthdr
    section_kinds = []
    for i in range(n_sections):
        s_off = sec_tbl + 40 * i
        name = data[s_off:s_off + 8].rstrip(b"\x00").decode("latin1", "replace")
        section_kinds.append(name)
    strtbl = sym_tbl_off + 18 * n_syms
    out = []
    i = 0
    while i < n_syms:
        off = sym_tbl_off + 18 * i
        if data[off:off + 4] == b"\x00\x00\x00\x00":
            name_off = struct.unpack_from("<I", data, off + 4)[0]
            end = data.index(b"\x00", strtbl + name_off)
            name = data[strtbl + name_off:end].decode("latin1", "replace")
        else:
            name = data[off:off + 8].rstrip(b"\x00").decode("latin1", "replace")
        section_num = struct.unpack_from("<h", data, off + 12)[0]
        storage_cls = data[off + 16]
        n_aux = data[off + 17]
        out.append((name, section_num, storage_cls, section_kinds))
        i += 1 + n_aux
    return out


# Symbol-name patterns we own:
# - DAT_xxxxxxxx                       raw data globals
# - LAB_xxxxxxxx                       code labels referenced from
#                                      another function (jump targets,
#                                      jump-table slots, SEH handlers)
# - PTR_<api>_xxxxxxxx                 IAT thunk for DLL import
# - s_<chars>_xxxxxxxx                 string literal
# - IMAGE_DOS_HEADER_xxxxxxxx          PE header reference (rare)
# - switchD_xxxxxxxx                   MSVC switch jump dispatch label
# - switchdataD_xxxxxxxx               jump table data
# - thunk_FUN_xxxxxxxx                 trivial trampolines
# - <name>_xxxxxxxx                    other Ghidra-named single-token data
OWNED_RE = re.compile(
    r"^("
    r"DAT_[0-9a-fA-F]{8}|"
    r"LAB_[0-9a-fA-F]{8}|"
    r"PTR_.+_[0-9a-fA-F]{8}|"
    r"s_.+_[0-9a-fA-F]{8}|"
    r"IMAGE_DOS_HEADER_[0-9a-fA-F]{8}|"
    r"switchD_[0-9a-fA-F]{8}|"
    r"switchdataD_[0-9a-fA-F]{8}|"
    r"thunk_FUN_[0-9a-fA-F]{8}"
    r")$"
)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dir", default="build/orig/bulanci",
                        help="Directory of target .obj files.")
    parser.add_argument("--out", default="include/bulanci/_externs.h",
                        help="Header to write.")
    args = parser.parse_args()

    obj_dir = Path(args.dir)
    out_path = Path(args.out)
    defined = set()
    referenced = defaultdict(set)
    for p in sorted(obj_dir.glob("*.obj")):
        for name, sec, sc, _ in parse_obj(p):
            if sec > 0:
                defined.add(name)
            elif sec == 0 and sc == 2:
                referenced[name].add(p.stem)

    externs = sorted(n for n in referenced
                     if n not in defined and OWNED_RE.match(n))
    # Group for readability in the generated header.
    buckets = defaultdict(list)
    for n in externs:
        prefix = n.split("_", 1)[0] + "_"
        if not OWNED_RE.match(prefix + "00000000"):
            # Names like `switchdataD_xxxxxxxx` and `thunk_FUN_xxxxxxxx`
            # share their first underscore with content; key them by
            # the segment up to the trailing hex group instead.
            prefix = re.sub(r"_[0-9a-fA-F]{8}$", "_", n)
        buckets[prefix].append(n)

    body = []
    for prefix in sorted(buckets):
        names = buckets[prefix]
        body.append(f"/* {prefix} ({len(names)}) */")
        for n in names:
            body.append(f"extern unsigned char {n};")
        body.append("")

    out = HEADER + "\n".join(body) + FOOTER
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out)
    print(f"wrote {out_path}: {len(externs)} extern(s) across "
          f"{len(buckets)} bucket(s)")


if __name__ == "__main__":
    sys.exit(main())
